### PR TITLE
Closes #10324: Add extension method for decrypting credit card number.

### LINKED ISSUE #10324: Expose a helper function for decrypting card numbers
Needed for Fenix issue: https://github.com/mozilla-mobile/fenix/issues/18275

### PR DESCRIPTION
**Pull request by mcarare**
### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Comment by gabrielluong** [comment]
I don't we want to expose the decrypt function publicly. I would instead add a helper function in the storage to help check for duplicates. That way we can potentially reuse it.

**Comment by mcarare** [comment]
@gabrielluong Something like this?

**Comment by gabrielluong** [comment]
> @gabrielluong Something like this?

@mcarare Ya, I don't know if it needs to be an extension function tho. Looking at this, it makes me wonder what was preventing you from calling `getCreditCardCrypto` in Fenix and then doing the `decrypt`.

**Comment by mcarare** [comment]
@gabrielluong I was already doing that, but you suggested exposing a method in A-C.

**Comment by gabrielluong** [comment]
> @gabrielluong I was already doing that, but you suggested exposing a method in A-C.
> 
> LE: see here: https://github.com/mozilla-mobile/fenix/blob/1820448df67eda79007e9dfb343f718cf7d0335a/app/src/main/java/org/mozilla/fenix/settings/creditcards/CreditCardValidator.kt#L37

Ah sorry, I think I wasn't looking into this deep enough since it was a draft. My general thoughts are that we can always migrate `isDuplicate` into AC when there is a need to use this in multiple places, but we probably don't need to do this right now.

**Pull request closed without merging**
