### PR TITLE
Closes #6092: Add download link in context menu.

### LINKED ISSUE #6092: Add download link in context menu
Currently there is no option to download the file through a link.  Add an option to download file using the context menu.

### PR DESCRIPTION
**Pull request by rocketsroger**
---

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- [ ] **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- [ ] **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Comment by rocketsroger** [comment]
device-2020-03-12-114210

**Comment by rocketsroger** [comment]
@betsymi Please review the string for the new added option in context menu.  The current string is "Download link".  This use case is if the user long tap on a link to download the target of the link.

**Comment by betsymi** [comment]
`Download link` is good for this string. 

> @betsymi Please review the string for the new added option in context menu. The current string is "Download link". This use case is if the user long tap on a link to download the target of the link.

**Comment by rocketsroger** [comment]
bors r=psymoon

**Pull request merged**
