### PR TITLE
Close #11462: Allow to choose the restore location of a tab in the tabstray.

### LINKED ISSUE #11462: Allow to choose the restore location of a tab
Actually, recently closed tabs are restored at the top of the list by default.
To fix [mozilla-mobile/fenix:#22372](https://github.com/mozilla-mobile/fenix/issues/22372), we should leave the choice for the restore location `(TOP, END, AT_INDEX)`.

Happy New Year, good health and have fun🙂

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19020)

### PR DESCRIPTION
**Pull request by Choucroute-melba**
Added optional parameters for `TabsUseCases.RestoreUseCase` that allow the browser to choose the restore location of a tab in the tabstray. Default value is `RestoreLocation.END`.

This closes mozilla-mobile/fenix#22372

### Pull Request checklist

- [X] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [X] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [X] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/main/docs/changelog.md) or does not need one
-  [X] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/main/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Review by jonalmeida — COMMENTED** [review]
This change looks good to me, but I'm not sure about changing the default RestoreLocation to END. I've left a comment on the Fenix issue for now to clarify before we land this.

**Review by csadilek — COMMENTED** [review]
Going over older PRs. The change here looks good, but in order to land this in A-C, we'd need unit test coverage, and I think we should not change the default.

We can continue the discussion on the Fenix issue.

**Comment by csadilek** [comment]
If still desired, please re-open this PR against the new [repo](https://github.com/mozilla-mobile/firefox-android) with https://github.com/mozilla-mobile/android-components/pull/11468#pullrequestreview-1144672966 addressed. Thank you for your contribution!

**Comment by gabrielluong** [comment]
Hey @Choucroute-melba, we're tidying up the remaining opened PR in this repo since this project moved to a new repository. It is now developed and maintained at: https://github.com/mozilla-mobile/firefox-android.

**Pull request closed without merging**
