### PR TITLE
For #6237 - Add tests for InlineAutocompleteEditText's TextChangeList…

### PR DESCRIPTION
**Pull request by codrut-topliceanu**
[For #6237](https://github.com/mozilla-mobile/android-components/issues/6237)

---

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks.
- [x] **Tests**: This PR includes thorough tests.
- [x] **Changelog**: This PR does not need one.
- [x] **Accessibility**: The code in this PR does not include any user facing features.

### After merge
- [ ] **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- [ ] **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Comment by codrut-topliceanu** [comment]
Added tests as @rocketsroger asked, unfortunately I discovered that [my fix](https://github.com/mozilla-mobile/android-components/pull/6139) doesn't handle all the cases. I will create another issue to address that. :(

**Comment by rocketsroger** [comment]
> Added tests as @rocketsroger asked, unfortunately I discovered that [my fix](https://github.com/mozilla-mobile/android-components/pull/6139) doesn't handle all the cases. I will create another issue to address that. :(

Please assign me as reviewer when you have the PR up.  thanks!

**Comment by rocketsroger** [comment]
bors r=rocketsroger

**Comment by codrut-topliceanu** [comment]
Here is the [new issue I promised](https://github.com/mozilla-mobile/android-components/issues/6276). Sorry it took so long.

**Pull request merged**
