### PR TITLE
Issue #7441: Remove unused ThumbnailsUseCase

### LINKED ISSUE #7441: Remove unused ThumbnailsUseCase
We removed the usage of `ThumbnailsUseCase` in #7313. While we might want to consider keeping ThumbnailsUseCase for more generic usage, we should remove it as a parameter from `TabsTrayPresenter`, `TabsFeature` and `TabsTrayFragment` since it is not needed anymore.

### PR DESCRIPTION
**Pull request by gabrielluong**
---

Fixes #7441

### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Comment by jonalmeida** [comment]
Thanks for the cleanup! I think there's a mistake on my part here: instead of removing the use case, in my PR that added the ThumbnailLoader, I should have used the use case instead. This would have gotten rid of that weird if-else check that we added into the Fenix TabsTrayViewHolder.

I like the idea of having use cases where it makes sense, but I'm open to alternatives too!

**Comment by gabrielluong** [comment]
> Thanks for the cleanup! I think there's a mistake on my part here: instead of removing the use case, in my PR that added the ThumbnailLoader, I should have used the use case instead. This would have gotten rid of that weird if-else check that we added into the Fenix TabsTrayViewHolder.
> 
> I like the idea of having use cases where it makes sense, but I'm open to alternatives too!

Do you mean you want to wrap ThumbnailLoader into the ThumbnailUseCase constructor and have the use case functions call load?

**Comment by gabrielluong** [comment]
bors r=jonalmeida

**Comment by gabrielluong** [comment]
bors retry

**Pull request merged**
