### PR TITLE
Closes #7917 - Update all 3 telemetry options with FHR value in migra…

### LINKED ISSUE #7917: Migration telemetry settings
If a Fennec user has disabled FHR in their privacy settings, we want to disable all 3 telemetry options (usage & technical data, marketing data, experiment) in Fenix during the migration.

### PR DESCRIPTION
**Pull request by ekager**
…tion

---

### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Comment by grigoryk** [comment]
I've tested this locally with a migration build, and it behaves correctly: with FHR off in Fennec, all three options under the Data Collection menu are disabled after the migration. With FHR on in Fennec, all three options are enabled.

**Comment by grigoryk** [comment]
Actually, just realized that we also likely want to run a follow-up migration for users we already migrated... I'll comment on that later tonight.

**Comment by grigoryk** [comment]
We retain Fennec's old pref file during an upgrade, so fixing this for the affected users is just a matter of re-running the (fixed) migration. I've bumped the settings migration version to v2 (which will trigger a re-run), and retested with the following scenarios:

For the affected users (already migrated with v1):
- Original (v1) settings migration applied while FHR=off. Fenix has Telemetry off, Marketing/Experiments=on. Installing an update with the new v2 migration, after startup Telemetry, Marketing and Experiments are all off.
- Original (v1) settings migration applied while FHR=on. Fenix has Telemetry,Marketing/Experiments=on. Installing an update with the new v2 migration, after startup Telemetry, Marketing and Experiments are all on.

For the non-affected users (not yet migrated, v2 will be their first encounter with the settings migration):
- When FHR is off in Fennec, after an update Telemetry/Marketing/Experiments=off
- When FHR is on in Fennec, after an update Telemetry/Marketing/Experiments=on

**Comment by grigoryk** [comment]
Also verified that we should do correct thing with handling these pref flips: settings migration happens before we initialize telemetry/marketing/experiment systems, so when v2 runs and flips them to 'off', these systems won't be enabled during startup.

**Comment by pocmo** [comment]
Uplifted to 52.

**Pull request merged**
