### PR TITLE
Closes #7930: Use fallback url over market intent if user preference is not to launch in external app

### LINKED ISSUE #7930: Firefox offers to open the Play Store for a given intent: URL, while Chrome redirects to another page
As seen in https://github.com/webcompat/web-bugs/issues/55998, Firefox seems to not be falling back to the same URL Chrome does for this `intent:` link:
```
intent://hotel/Jetwing Blue/247454?adults=2&af_deeplink=true&af_dp=agoda%3A%2F%2Fhotel%2FJetwing%20Blue%2F247454&af_force_dp=true&af_r=https%3A%2F%2Fwww.agoda.com%2Fjetwing-blue%2Fhotel%2Fnegombo-lk.html&af_web_id=f975673a-6824-4be6-8d07-cdf13ee6314a-o&campaign=Property_Sharing&checkIn=2020-08-02&checkOut=2020-08-03&childs=0&cid=1770664&los=1&media_source=Mobile_App&rooms=1&site_id=1770664#Intent;scheme=agoda;package=com.agoda.mobile.consumer;S.browser_fallback_url=https://www.agoda.com/jetwing-blue/hotel/negombo-lk.html?childs=0&af_dp=agoda%253A%252F%252Fhotel%252FJetwing%2520Blue%252F247454&los=1&checkOut=2020-08-03&pid=Mobile_App&adults=2&cid=1770664&checkIn=2020-08-02&c=Property_Sharing&rooms=1&site_id=1770664;S.market_referrer=af_tranid%3Dwnb_-PURtEzhwA4a81lsqA%26af_r%3Dhttps%3A%2F%2Fwww.agoda.com%2Fjetwing-blue%2Fhotel%2Fnegombo-lk.html%26childs%3D0%26af_dp%3Dagoda%253A%252F%252Fhotel%252FJetwing%2520Blue%252F247454%26los%3D1%26checkOut%3D2020-08-03%26pid%3DMobile_App%26adults%3D2%26af_web_id%3Df975673a-6824-4be6-8d07-cdf13ee6314a-o%26cid%3D1770664%26checkIn%3D2020-08-02%26c%3DProperty_Sharing%26rooms%3D1%26site_id%3D1770664;l.appsflyer_click_ts=1596134718926;end
```

That is, Chrome redirects to `https://www.agoda.com/jetwing-blue/hotel/negombo-lk.html?childs=0&af_dp=agoda%3A%2F%2Fhotel%2FJetwing%20Blue%2F247454&los=1&checkOut=2020-08-03&pid=Mobile_App&adults=2&cid=1770664&checkIn=2020-08-02&c=Property_Sharing&rooms=1&site_id=1770664`, while Firefox shows a blank page and offers to open the Play Store.

### PR DESCRIPTION
**Pull request by rocketsroger**
---

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Comment by hakkikaancaliskan** [comment]
Does this will also fix https://github.com/mozilla-mobile/fenix/issues/12746?

**Comment by hakkikaancaliskan** [comment]
Nope, not fixing but at least opens website instead of opening play store while 'open in app' option turned off.

**Comment by rocketsroger** [comment]
> Does this will also fix [mozilla-mobile/fenix#12746](https://github.com/mozilla-mobile/fenix/issues/12746)?
> Edit: I'm trying this locally

That looks like a opposite issue.  This one is trying to fix the issue that if the user preference is not to open in app, we load the fallback URL.  I'll have to look at the other one to see what's the cause.

**Comment by hakkikaancaliskan** [comment]
> > Does this will also fix [mozilla-mobile/fenix#12746](https://github.com/mozilla-mobile/fenix/issues/12746)?
> > Edit: I'm trying this locally
> 
> That looks like a opposite issue. This one is trying to fix the issue that if the user preference is not to open in app, we load the fallback URL. I'll have to look at the other one to see what's the cause.

Actually on that issue [https://ty.gl/j08whdcd](https://ty.gl/j08whdcd) link opens play store regardless of open in app option. With this pr now opens link in browser while open in app option OFF. But opens play store when open in app option on (should open trendyol app). Means this pr fixes half of the https://github.com/mozilla-mobile/fenix/issues/12746.

**Comment by rocketsroger** [comment]
> Edit 2: changing place of marketplaceIntent and fallbackUrl fixes problem but breaks others. Idk how to solve properly. That's all i can do :(

Is this with `Open links in apps` off?

**Comment by hakkikaancaliskan** [comment]
> > Edit 2: changing place of marketplaceIntent and fallbackUrl fixes problem but breaks others. Idk how to solve properly. That's all i can do :(
> 
> Is this with `Open links in apps` off?

Nope, open links in apps on. When off, there is no problem now with this pr.

**Comment by rocketsroger** [comment]
> > > Does this will also fix [mozilla-mobile/fenix#12746](https://github.com/mozilla-mobile/fenix/issues/12746)?
> > > Edit: I'm trying this locally
> > 
> > 
> > That looks like a opposite issue. This one is trying to fix the issue that if the user preference is not to open in app, we load the fallback URL. I'll have to look at the other one to see what's the cause.
> 
> Actually on that issue https://ty.gl/j08whdcd link opens play store regardless of open in app option. With this pr now opens link in browser while open in app option OFF. But opens play store when open in app option on (should open trendyol app). Means this pr fixes half of the [mozilla-mobile/fenix#12746](https://github.com/mozilla-mobile/fenix/issues/12746).

I see,  thanks for clarifying.  Yes, this is what this patch should do.  If the user have 'Open links in apps' off then we should load the playstore site in browser.  I'll look into the other issue when the user have the preference on.

**Comment by rocketsroger** [comment]
bors r=psymoon

**Pull request merged**
