### PR TITLE
Second batch of new proton icons

### PR DESCRIPTION
**Pull request by Amejia481**
Fenix related PR https://github.com/mozilla-mobile/fenix/pull/19355
 
Updated icons:
- [x] lightbulb (`Report site issue` menu item)
- [x] more-vertical
- [x] chevron-right (next to `Add-ons` menu item)
- [x] chevron-up (inside `Find in page`)
- [x] chevron-down (within `Find in page` and `Saved logins`)
- [x] lock-blocked

https://user-images.githubusercontent.com/773158/116875511-0c7a3f80-abe9-11eb-917c-d1750da4fa2b.mp4

### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Comment by cadeyrn** [comment]
@Amejia481 At the beginning of your video it can be seen that the padlock icon moves a bit depending of the state (secure / unsecure). This should probably not happen.

**Comment by Amejia481** [comment]
> @Amejia481 At the beginning of your video it can be seen that the padlock icon moves a bit depending on the state (secure / insecure). This should probably not happen.

Thanks for catching this, it looks like the original svg icons were drawn in slight different positions. @brampitoyo could help us to confirm that.



https://user-images.githubusercontent.com/773158/116884254-85cb5f80-abf4-11eb-979a-a826c08285b7.mp4

**Review by wisniewskit — APPROVED** [review]
LGTM on the webcompat-reporter change. We should just also make sure the manifest.json version is also updated here: https://github.com/mozilla-mobile/android-components/blob/bfaf514793dd20f9f12d3f551f9ff3e470f52727/components/feature/webcompat-reporter/src/main/assets/extensions/webcompat-reporter/manifest.json#L6

**Comment by Amejia481** [comment]
> LGTM on the webcompat-reporter change. We should just also make sure the manifest.json version is also updated here:
> 
> https://github.com/mozilla-mobile/android-components/blob/bfaf514793dd20f9f12d3f551f9ff3e470f52727/components/feature/webcompat-reporter/src/main/assets/extensions/webcompat-reporter/manifest.json#L6

Thanks, I completely forgot that updating the icon counts as updating the extension 😅

**Review by gabrielluong — APPROVED** [review]

**Comment by Amejia481** [comment]
@Mergifyio backport releases/75.0

**Pull request merged**
