### PR TITLE
 Update GeckoView (beta) to 81.0.20200901203141 for AC 57.0.1

### PR DESCRIPTION
**Pull request by jonalmeida**
---

Corrected the `releases/57.0` branch to be cut from the `v57.0.0` tag.

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Comment by jonalmeida** [comment]
@rocketsroger r? again please. 🙂

**Review by rocketsroger — APPROVED** [review]
Looks good this time 👍

**Comment by jonalmeida** [comment]
bors r=rocketsroger

**Comment by jonalmeida** [comment]
bors retry

**Pull request merged**
