### PR TITLE
Import telemetry library into components/service/telemetry

### PR DESCRIPTION
**Pull request by pocmo**

### CODE REVIEW

**Comment by pocmo** [comment]
@csadilek Not worth reviewing every line of code again, I guess. But wanted you to see this.

**Comment by pocmo** [comment]
I wonder why this doesn't show up in the coverage report. The library came with tests and had 90+% coverage.

**Comment by csadilek** [comment]
@pocmo the jacoco config is fine. We're getting a nice bump in coverage from this lib :). I will poke around a bit and merge this in a bit.

**Comment by csadilek** [comment]
@pocmo Two comments:

- Are we sure we want to publish this using org.mozilla.components.**service**.telemetry i.e. we're not using components.**browser** or components.**feature**.

- We need to update the README as well.

Also, I am confused why this branch didn't update / rebase without conflicts as all the latest commits have been there. I will take a look.

**Comment by csadilek** [comment]
@pocmo Ah, makes sense. Since we want to retain the original history, we want these commits interleaved with the ones already on master. So, while a FF merge was possible, we can't rebase, of course :). So, for this PR we will have to use a merge commit, but that's not enabled on GitHub. Let's just push your branch to master directly :). 💥 🔥

**Comment by pocmo** [comment]
> Are we sure we want to publish this using org.mozilla.components.service.telemetry i.e. we're not using components.browser or components.feature.

That's a good question. We cannot re-use the old ID because then we would suddenly go from 1.2.0 to 0.5. I wanted to use something that is more future-proof assuming that org.mozilla.components.* will get very crowded. But maybe we should just delay this (once we change *all* components) and just go with org.mozilla.components.telemetry for now. I'll update the PR and push to master.

**Comment by pocmo** [comment]
Merged!

**Pull request closed without merging**
