### PR TITLE
Update to application-services v77.0.1

### PR DESCRIPTION
**Pull request by jdragojevic**
- release notes from 77.0.0 https://github.com/mozilla/application-services/releases/tag/v77.0.0
  - minor updates for logins component
  - ⚠️ breaking change from nimbus to support feature-api
  - needs https://github.com/mozilla-mobile/fenix/pull/19605 to resolve

### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Review by travis79 — APPROVED** [review]

**Comment by csadilek** [comment]
bors try

**Comment by jonalmeida** [comment]
bors ping

**Review by csadilek — APPROVED** [review]
Thanks to @jonalmeida and @jhugman for helping w/ manual smoke testing. We didn't find any problems. Let's 🚢 !

**Comment by jdragojevic** [comment]
Thank you all for being super responsive and moving this forward!!!!

**Pull request merged**
