### PR TITLE
TrackingProtectionIconView: Always call updateIcon() to initialize.

### PR DESCRIPTION
**Pull request by pocmo**
We never called `updateIcon` on init. That meant that the TP icon had no content description. In Fenix we didn't notice this since we always override the icons and that causes an update too.

### CODE REVIEW

**Review by Amejia481 — APPROVED** [review]
Let's address the test failure 


```
DisplayToolbarTest. tracking protection and separator views become visible when states ON OR ACTIVE are set to siteTrackingProtection
```

Looks like the [test, it's expecting icons are GONE by default](https://github.com/mozilla-mobile/android-components/blob/4908f87ac726f69d6814b45e2ea42637cbdb331c/components/browser/toolbar/src/test/java/mozilla/components/browser/toolbar/display/DisplayToolbarTest.kt#L126), maybe we can address this by changing the default state of [ON_NO_TRACKERS_BLOCKED](https://github.com/mozilla-mobile/android-components/blob/4908f87ac726f69d6814b45e2ea42637cbdb331c/components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/display/TrackingProtectionIconView.kt#L33) to `OFF_GLOBALLY`, I noticed, it was changed on https://github.com/mozilla-mobile/android-components/commit/4be7cd4957785e4574558fcf401775435cb9ba2e from `OFF_GLOBALLY` to `ON_NO_TRACKERS_BLOCKED`, I was about to change the PR, but  I'm not sure if it was intentional.

**Comment by pocmo** [comment]
Hm, yeah, there's some overlap in who's managing the visibility status. Display toolbar does it based on whether the indicator is added. And the view itself does it too based on the tracking protection status.

**Comment by pocmo** [comment]
Just setting the default to OFF would break another test. Instead I opted for a different version: Setting no default (`null`). With that we always react to whatever state we get. This seems to work in Focus as well as Fenix.

**Comment by Amejia481** [comment]
👍🏽

**Pull request merged**
