### PR TITLE
Upgrade to Glean v43.0.2

### PR DESCRIPTION
**Pull request by badboy**
See https://github.com/mozilla/glean/releases/v43.0.2 for details

---

~~[Requires a new Gecko nightly first](https://bugzilla.mozilla.org/show_bug.cgi?id=1750544)~~

### CODE REVIEW

**Comment by badboy** [comment]
The m-c patch is landing now, so the next nightly will have it (if it sticks). This PR will PROBABLY not be necessary anymore, because of https://github.com/mozilla-mobile/relbot/pull/67.
I'll keep it open for the changelog entry though and check back in tomorrow.

**Comment by badboy** [comment]
Glean update in #11568

**Comment by csadilek** [comment]
Landed in https://github.com/mozilla-mobile/android-components/pull/11569.

**Comment by badboy** [comment]
This adds a changelog entry. Do we not want to have that? (We probably won't do that going forward for every update)

**Review by csadilek — APPROVED** [review]

**Pull request merged**
