### PR TITLE
Closes #5684: Intermittent failures in WebExtensionBrowserMenuItemTest

### LINKED ISSUE #5684: Intermittent test failures in WebExtensionBrowserMenuItemTest
The tests `bind` and `fallbackToDefaultIcon` fail because we're not joining on the job that loads the icon. The `MainScope.launch` block might execute after we verify in the test.

### PR DESCRIPTION
**Pull request by csadilek**

### CODE REVIEW

**Comment by psymoon** [comment]
bors r=Amejia481, psymoon

**Comment by csadilek** [comment]
bors retry

**Comment by Amejia481** [comment]
bors retry

**Comment by Amejia481** [comment]
bors retry

**Pull request merged**
