### PR TITLE
Issue #8124: Re-enable failing SearchEngineStorageTest

### PR DESCRIPTION
**Pull request by jonalmeida**
---

I ran each test combinations below 2000+ times and didn't get it to fail any more. Let's try to re-enable it and see if this is still an issue:
 - `SearchEngineStorageTest` x 5000 times
 - `loadSearchEngineList successfully loads after saving` x 2000 times
 - `feature-search` x 5000 times (which is about 200 times for each of the 23 tests).

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Comment by jonalmeida** [comment]
Of course, the one time I run it in CI it fails. 🤣

**Comment by jonalmeida** [comment]
Ha, I didn't noticed this earlier: we were not awaiting the nested async function.

**Comment by jonalmeida** [comment]
It bothers me that I can't reproduce this locally either way. 🤔

**Comment by jonalmeida** [comment]
Ping @pocmo :)

**Comment by pocmo** [comment]
Still changing some bits in that area. Will take a look eventually. :)

**Review by pocmo — APPROVED** [review]
Rebased it and used `GlobalScope` instead of creating a new one for each load. Ran it a bunch of times too. Looks good. 👍

**Comment by pocmo** [comment]
Heh, of course it failed on taskcluster 😅 

I would like to try again without the async. Locally I tested this too and didn't run into any issues.

**Pull request closed without merging**
