### PR TITLE
Closes #1388: Update tracking protection lists

### LINKED ISSUE #1388: Update tracking protection lists in browser-engine-system
Lists are here: https://github.com/mozilla-services/shavar-prod-lists

We took the list from Focus. Focus has never updated the list since we launched it. So we should definitely do that in the component soonish. Gecko comes with its own lists.

### PR DESCRIPTION
**Pull request by dnarcese**
According to corresponding lists in https://github.com/mozilla-services/shavar-prod-lists

---

FFTV needs the updated lists https://github.com/mozilla-mobile/firefox-tv/issues/2730
### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- [ ] **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- [ ] **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Comment by dnarcese** [comment]
Nevermind, I need to combine the new list with the old list :)

**Comment by dnarcese** [comment]
Re-opening this: after some investigation, it seems that updating the lists should actually work.

**Comment by Amejia481** [comment]
@dnarcese I updated the PR, the new list added new categories (`Fingerprinting`, `Cryptomining`) that we weren't handling.

After this pr is merged https://github.com/mozilla-mobile/android-components/pull/4430 this will be green.

**Comment by Amejia481** [comment]
bors r=amejia481

**Comment by Amejia481** [comment]
bors retry

**Pull request merged**
