### PR TITLE
Upgrade to Glean v39.0.0

### PR DESCRIPTION
**Pull request by badboy**
This also adjusts sync-telemetry to use the non-deprecated form of
events now.

### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Comment by badboy** [comment]
This will require minimal changes in Fenix to not fail on the deprecated code:

```patch
diff --git app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
index 74f49ccfa..d8bbc649a 100644
--- app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
+++ app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
@@ -99,10 +99,12 @@ private class EventWrapper<T : Enum<T>>(
             null
         }

+        @Suppress("DEPRECATION")
         this.recorder(extras)
     }
 }

+@Suppress("DEPRECATION")
 private val Event.wrapper: EventWrapper<*>?
     get() = when (this) {
         is Event.OpenedApp -> EventWrapper(
diff --git app/src/main/java/org/mozilla/fenix/telemetry/TelemetryLifecycleObserver.kt app/src/main/java/org/mozilla/fenix/telemetry/TelemetryLifecycleObserver.kt
index ec86ae2f4..7ebf78503 100644
--- app/src/main/java/org/mozilla/fenix/telemetry/TelemetryLifecycleObserver.kt
+++ app/src/main/java/org/mozilla/fenix/telemetry/TelemetryLifecycleObserver.kt
@@ -35,6 +35,7 @@ class TelemetryLifecycleObserver(
         val lastState = pausedState ?: return
         val currentState = createTabState()

+        @Suppress("DEPRECATION")
         EngineMetrics.foregroundMetrics.record(mapOf(
             MetricsKeys.backgroundActiveTabs to lastState.activeEngineTabs.toString(),
             MetricsKeys.backgroundCrashedTabs to lastState.crashedTabs.toString(),
```

**Review by Dexterp37 — APPROVED** [review]

**Review by rfk — APPROVED** [review]
LGTM from a sync perspective, thanks!

**Comment by csadilek** [comment]
@badboy Unfortunately, we have to back out this change. There are quite a few breaking changes in Fenix that @pocmo and I couldn't figure out how to fix quickly. We're also trying to land an upgrade so this is unfortunate timing.

Also it looks like you deprecated, but still broke the API, which is not good :).
```
2021-06-08T15:13:48.3732130Z e: /home/runner/work/fenix/fenix/app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt: (109, 39): Type mismatch: inferred type is Map<Events.appOpenedKeys, String>? but Map<Events.appOpenedKeys, String> was expected
2021-06-08T15:13:48.3735487Z e: /home/runner/work/fenix/fenix/app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt: (113, 47): Type mismatch: inferred type is Map<Events.appReceivedIntentKeys, String>? but Map<Events.appReceivedIntentKeys, String> was expected
2021-06-08T15:13:48.3738939Z e: /home/runner/work/fenix/fenix/app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt: (117, 49): Type mismatch: inferred type is Map<Events.appOpenedAllStartupKeys, String>? but Map<Events.appOpenedAllStartupKeys, String> was expected
2021-06-08T15:13:48.3742403Z e: /home/runner/work/fenix/fenix/app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt: (121, 45): Type mismatch: inferred type is Map<Events.searchBarTappedKeys, String>? but Map<Events.searchBarTappedKeys, String> was expected
2021-06-08T15:13:48.3763977Z e: /home/runner/work/fenix/fenix/app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt: (125, 40): Type mismatch: inferred type is Map<Events.enteredUrlKeys, String>? but Map<Events.enteredUrlKeys, String> was expected
2021-06-08T15:13:48.3767865Z e: /home/runner/work/fenix/fenix/app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt: (131, 47): Type mismatch: inferred type is Map<Events.performedSearchKeys, String>? but Map<Events.performedSearchKeys, String> was expected
2021-06-08T15:13:48.3777530Z e: /home/runner/work/fenix/fenix/app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt: (151, 47): Type mismatch: inferred type is Map<SearchShortcuts.selectedKeys, String>? but Map<SearchShortcuts.selectedKeys, String> was expected
2021-06-08T15:13:48.3784685Z e: /home/runner/work/fenix/fenix/app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt: (155, 44): Type mismatch: inferred type is Map<mozilla.components.service.glean.private.NoExtraKeys /* = mozilla.telemetry.glean.private.NoExtraKeys */, String>? but Map<mozilla.components.service.glean.private.NoExtraKeys /* = mozilla.telemetry.glean.private.NoExtraKeys */, String> was expected
2021-06-08T15:13:48.3791690Z e: /home/runner/work/fenix/fenix/app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt: (158, 44): Type mismatch: inferred type is Map<mozilla.components.service.glean.private.NoExtraKeys /* = mozilla.telemetry.glean.private.NoExtraKeys */, String>? but Map<mozilla.components.service.glean.private.NoExtraKeys /* = mozilla.telemetry.glean.private.NoExtraKeys */, String> was expected
2021-06-08T15:13:48.3800975Z e: /home/runner/work/fenix/fenix/app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt: (161, 40): Type mismatch: inferred type is Map<mozilla.components.service.glean.private.NoExtraKeys /* = mozilla.telemetry.glean.private.NoExtraKeys */, String>? but Map<mozilla.components.service.glean.private.NoExtraKeys /* = mozilla.telemetry.glean.private.NoExtraKeys */, String> was expected
2021-06-08T15:13:48.3808030Z e: /home/runner/work/fenix/fenix/app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt: (164, 44): Type mismatch: inferred type is Map<mozilla.components.service.glean.private.NoExtraKeys /* = mozilla.telemetry.glean.private.NoExtraKeys */, String>? but Map<mozilla.components.service.glean.private.NoExtraKeys /* = mozilla.telemetry.glean.private.NoExtraKeys */, String> was expected
....
```

In general, we ask that a Fenix PR is opened in case breaking changes can't be avoided. Thanks!

**Comment by badboy** [comment]
Noticed the revert. Yeah, not sure how that happened. I took this for a test run. Will check that tomorrow and make sure we can cleanly land that in Fenix.

**Comment by csadilek** [comment]
@badboy ok, thank you!

**Pull request merged**
