### PR TITLE
For mozilla-mobile/fenix#12632: Align search suggestion and search text

### PR DESCRIPTION
**Pull request by hakkikaancaliskan**
This is just a small pr for aligning search text and suggestion text, also aligns icons.

Screenshot_20200716-145421_Firefox_Preview

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Comment by hakkikaancaliskan** [comment]
@brampitoyo Could you please verify this small alignment?
suggestion icon margin start was 20dp, I've changed it to 16. So all fixed.

**Comment by brampitoyo** [comment]
@hakkikaancaliskan This looks just perfect to me. Thanks very much for proactively making these tiny changes that all amount to a great, polished experience. Seriously, thank you!

**Comment by hakkikaancaliskan** [comment]
> @hakkikaancaliskan This looks just perfect to me. Thanks very much for proactively making these tiny changes that all amount to a great, polished experience. Seriously, thank you!

You're welcome :)
I'm really happy to work with you guys.

**Comment by hakkikaancaliskan** [comment]
@NotWoods r+?

**Comment by hakkikaancaliskan** [comment]
@pocmo ready to land?

**Pull request merged**
