### PR TITLE
Import strings from android-l10n

### PR DESCRIPTION
**Pull request by Pike**
State: mozilla-l10n/android-l10n@413e05dba427ef8cbf9e5272ae5cc3b3ccdf91d3

In addition to the regular updates, this also add new locales, in support of Fenix and Lockwise: Bulgarian, Danish, Hungarian, Norwegian (both variants), Tamil, Turkish, Vietnamese.

CC @Delphine

### CODE REVIEW

**Comment by pocmo** [comment]
We could either check if this is a typo and needs fixing or disable the lint check 🤔

**Comment by Pike** [comment]
I can see that both ways. Over to @Delphine to reach out.

**Comment by Delphine** [comment]
Reached out to Havar, waiting to hear back!

**Comment by Delphine** [comment]
Localizers should have updated this in all instances on Pontoon (it is in fact a mispelling, although sometimes accepted, we should thus avoid using it). 
So we should be good to go!

**Comment by pocmo** [comment]
Thank you! In this case let's keep the `Typos` check for now.

@Pike Can you craft a new import? :)

**Comment by Pike** [comment]
> @Pike Can you craft a new import? :)

Just pushed an update.

**Pull request merged**
