### PR TITLE
Update Glean to include new upload mechanism (& gzip)

### PR DESCRIPTION
**Pull request by badboy**
---

### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Comment by badboy** [comment]
bors r=brizental

**Comment by pocmo** [comment]
```
[task 2020-06-03T11:42:39.981Z] > Task :ktlint
[task 2020-06-03T11:42:39.981Z] /builds/worker/checkouts/src/components/service/glean/src/main/java/mozilla/components/service/glean/net/ConceptFetchHttpUploader.kt:13:1: Unused import
[task 2020-06-03T11:42:39.981Z] /builds/worker/checkouts/src/components/service/glean/src/main/java/mozilla/components/service/glean/net/ConceptFetchHttpUploader.kt:14:1: Unused import
```

**Comment by badboy** [comment]
> ```
> [task 2020-06-03T11:42:39.981Z] > Task :ktlint
> [task 2020-06-03T11:42:39.981Z] /builds/worker/checkouts/src/components/service/glean/src/main/java/mozilla/components/service/glean/net/ConceptFetchHttpUploader.kt:13:1: Unused import
> [task 2020-06-03T11:42:39.981Z] /builds/worker/checkouts/src/components/service/glean/src/main/java/mozilla/components/service/glean/net/ConceptFetchHttpUploader.kt:14:1: Unused import
> ```

Gnah. Thanks for the notice. Thought I did run that. Will fix it locally, run the lints and push again.

**Comment by badboy** [comment]
bors r=brizental

**Comment by badboy** [comment]
bors r=brizental

One more try, ran both lint and tests locally.

**Pull request merged**
