### PR TITLE
Closes #7384: Truncated add-on title in AddonsManagerAdapter

### LINKED ISSUE #7384: [Bug] Truncated add-on title in add-ons manager
## Steps to reproduce
1. Open the Add-ons manager
2. Check the titles of the listed Add-ons

### Expected behavior
Properly displayed title for each Add-on

### Actual behavior
Truncated "Google search fix" web extension title

### Device information

* Android device: 
• Google Pixel 3a (Android 10)
• OnePlus A3 (Android 6.0.1)

* Fenix version: Debug build from Master

### Notes
❗ Noticed on the OnePlus A3 that swiping through the listed Add-ons, the title for both **HTTPS everywhere** and **Privacy Possum** get truncated as well  

► Video

### PR DESCRIPTION
**Pull request by Amejia481**
---

### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Comment by Amejia481** [comment]
> Tested this and the problem with this approach is that if the title is too long, the 'allow in private browsing' icon will disappear. Check the screenshots below. Also, I saw in the issue that on first scroll `HTTPS Everywhere` was not truncated, but after a second scroll it was. Maybe it's also a recycling issue?
> Old code 	Your code
>  	

Thanks, I will take a look at it :)

**Comment by Amejia481** [comment]
I'm not sure what could be causing dynamic the truncated effect on the old code, but some that brings my attention is that we have two items (the `textview` and the `imageview`),  the `weightSum` was equal to 1, as the test textview was having the total weight (`1`) and the image have a weight of 0, not sure if it is related to that.

**Comment by Amejia481** [comment]
As we want to have the `TextView`  `maxWith` to **be the total space available when the** `image` is `gone` and the when the `image` is visible, we want the `TextView`  `maxWith` to **be the total space available minus the width of the image**, we can do it programmatically [when biding the add-on data](https://github.com/mozilla-mobile/android-components/blob/d1b050feeaac5b693cb325832394a9085e596ee0/components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt#L205). @ValentinTimisica what do you think?

**Comment by ValentinTimisica** [comment]
Sounds good. You can try that and then we'll see if it works as expected.

**Comment by Amejia481** [comment]
@ValentinTimisica I updated the pr @jonalmeida found a nicer way to fix the issue, instead of using the                  `android:layout_width="0dp"`, it's better to indicate the width  `android:layout_width="wrap_content` as described i[n the android guide](https://developer.android.com/guide/topics/ui/layout/linear)

**Comment by Amejia481** [comment]
bors r=jonalmeida

**Pull request merged**
