### PR TITLE
Update Mockito to 3.5.13.

### PR DESCRIPTION
**Pull request by pocmo**
Trying again. Previously: #8560.

### CODE REVIEW

**Comment by pocmo** [comment]
```
[task 2020-10-14T08:51:02.788Z] w: /builds/worker/checkouts/src/components/browser/awesomebar/src/test/java/mozilla/components/browser/awesomebar/BrowserAwesomeBarTest.kt: (70, 13): 'verifyZeroInteractions(vararg Any!): Unit' is deprecated. Deprecated in Java
[task 2020-10-14T08:51:02.788Z] w: /builds/worker/checkouts/src/components/browser/awesomebar/src/test/java/mozilla/components/browser/awesomebar/BrowserAwesomeBarTest.kt: (71, 13): 'verifyZeroInteractions(vararg Any!): Unit' is deprecated. Deprecated in Java
```

**Comment by pocmo** [comment]
> java.lang.IllegalStateException: Could not initialize plugin: interface org.mockito.plugins.MockMaker (alternate: null)

Looks like this could require the new gradle version that we had to back out again?

**Comment by pocmo** [comment]
Alright, let's try again, now that we updated Gradle and the Android plugin.

**Comment by pocmo** [comment]
> [task 2020-10-19T09:41:11.421Z] Execution failed for task ':support-test:mergeDebugAndroidTestJavaResource'.
> [task 2020-10-19T09:41:11.421Z] > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
> [task 2020-10-19T09:41:11.421Z]    > More than one file was found with OS independent path 'win32-x86-64/attach_hotspot_windows.dll'.

🤔 ❓

**Comment by pocmo** [comment]
Some still seem to fail with:
> java.lang.IllegalStateException: Could not initialize plugin: interface org.mockito.plugins.MockMaker (alternate: null)

**Comment by pocmo** [comment]
Maybe. Some day.

**Comment by jonalmeida** [comment]
I ran into this as well and read online that adding the transitive bytebuddy dependency directly into the projects dependencies, but I didn't personally have success with that. 😕

**Comment by pocmo** [comment]
Saw that 3.5.15 was released.

But this seems to fail with a wild error. Not sure how that is related.

> [task 2020-10-21T10:55:19.990Z] > Task :browser-engine-gecko:build_condas
[task 2020-10-21T10:55:19.990Z] > Task :browser-engine-gecko:build_conda_envs SKIPPED
[task 2020-10-21T10:55:19.990Z] > Task :browser-engine-gecko:build_pythons SKIPPED
[task 2020-10-21T10:55:19.990Z] > Task :browser-engine-gecko:build_pythons_from_zip SKIPPED
[task 2020-10-21T10:55:19.990Z] > Task :browser-engine-gecko:build_virtual_envs SKIPPED
[task 2020-10-21T10:55:19.990Z] > Task :browser-engine-gecko:build_envs
[task 2020-10-21T10:55:20.090Z] 
[task 2020-10-21T10:55:20.090Z] FAILURE: Build failed with an exception.
[task 2020-10-21T10:55:20.090Z] 
[task 2020-10-21T10:55:20.090Z] * What went wrong:
[task 2020-10-21T10:55:20.090Z] Execution failed for task ':support-sync-telemetry:Bootstrap_CONDA_'Miniconda3''.
[task 2020-10-21T10:55:20.090Z] > Process 'command 'bash'' finished with non-zero exit value 1

**Comment by jonalmeida** [comment]
FYI: I'm no longer running into this issue on the latest Android Studio (Canary 14)

**Pull request closed without merging**
