### PR TITLE
Close #7461: Add share image context menu

### LINKED ISSUE #7461: Context Menu: Add share image option
Needed for https://github.com/mozilla-mobile/focus-android/issues/4527.

We don't have GV support for retrieving the Bitmap for this, so we share the source URI instead.

GV bug filed: https://bugzilla.mozilla.org/show_bug.cgi?id=1647568

### PR DESCRIPTION
**Pull request by jonalmeida**
---

Fixes #7461 for https://github.com/mozilla-mobile/focus-android/issues/4527.

Filed bug for getting a better behaviour from GV: https://bugzilla.mozilla.org/show_bug.cgi?id=1647568
### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Comment by jonalmeida** [comment]
> Should we use the download feature for this? Looks good otherwise

I left that note in the GV bug as well. It seemed a bit odd to me to have to do re-download an image we already have in web content so I opted for matching the current Focus behaviour for now. Depending on the result of the GV bug, we can amend this.

**Comment by jonalmeida** [comment]
bors r=NotWoods

**Comment by pocmo** [comment]
The actual sharing is #3648, I think. Focus distinguishes between the two too:
https://github.com/mozilla-mobile/focus-android/blob/master/app/src/main/java/org/mozilla/focus/menu/context/WebContextMenu.kt#L239-L258

I wonder if sharing the image URL would find more targets if we had a mime type for the intent. But looks like Focus didn't have that either and GV doesn't give us one. We could only guess it from the file extension.

**Comment by jonalmeida** [comment]
> This dropped of the list because that requires a "download" step before sharing and we didn't have anything for that in place. :)

@pocmo would that mean downloading the image to share is reasonable solution? My preference is to get something from GV but thinking about it more, that probably is harder for them to reason about with other mime types.

**Pull request merged**
