### PR TITLE
Close #6601: Update targetSdkVersion to 29

### LINKED ISSUE #6601: Update compile and target SDK to 29
With the Android 11 (SDK 30) soon to be released, we would be two versions below that.

We should update our `compileSdkVersion` and `targetSdkVersion` in `Config.kt` to 29 sooner than later.

### PR DESCRIPTION
**Pull request by jonalmeida**
---

This didn't cause any breaking API changes as I expected, but let's see what bors thinks.

I recall we had to make sure our clients had updated either their compile or target SDK as well the last time we did this, but I'll need to verify.

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Comment by jonalmeida** [comment]
I found this [Fire TV issue](https://github.com/mozilla-mobile/firefox-tv/issues/991) when we needed to update to 28 immediately. There doesn't seem to be any information there about consumers needing to update as well.

Robolectric hasn't updated to support API 29 (I tried version 4.3), so instead I offered for forcing it  to target 28 first.

I wonder if there are any other considerations to make that I'm missing.. cc @pocmo maybe?

**Comment by pocmo** [comment]
> I wonder if there are any other considerations to make that I'm missing.. cc @pocmo maybe?

I'd just try building Fenix and RB with that locally, if you haven't. Just to make sure there are no surprises once this hits nightly. Maybe even do a local publish and/or kdoc run to make sure that still works too.

CC @JohanLorenzo This is maybe an example of a change (SDK version) that may need new dependencies and the change is not in one of the defined files? But then again I am not even sure if we cache the SDK yet since that is not a "gradle dependency" and downloaded by the android plugin as needed.

**Comment by JohanLorenzo** [comment]
Great to know. Thanks for highlighting this, @pocmo. If I understand this PR correctly, then we can track `buildSrc/src/main/java/Config.kt`. If this file changes, the SDK will be downloaded and cached once more. 

I think that's a good-enough solution. What do you think?

**Comment by jonalmeida** [comment]
> I'd just try building Fenix and RB with that locally, if you haven't. Just to make sure there are no surprises once this hits nightly. Maybe even do a local publish and/or kdoc run to make sure that still works too.

I verified that kdocs generate as well - I hadn't done that. Thanks!

> If I understand this PR correctly, then we can track buildSrc/src/main/java/Config.kt. If this file changes, the SDK will be downloaded and cached once more.

That sounds like a great idea to me.

**Comment by JohanLorenzo** [comment]
Great!

Could you change https://github.com/mozilla-mobile/android-components/blob/9dfa58613e995577e7e9a6acb3187f51c2a76390/taskcluster/ci/toolchain/android.yml#L27 to be 

```yaml
      resources:
          - buildSrc/src/main/java/Config.kt
```
?

This way, this file is going to be tracked :)

**Comment by jonalmeida** [comment]
> Great!
> 
> Could you change
> 
> https://github.com/mozilla-mobile/android-components/blob/9dfa58613e995577e7e9a6acb3187f51c2a76390/taskcluster/ci/toolchain/android.yml#L27
> to be
> 
> ```yaml
>       resources:
>           - buildSrc/src/main/java/Config.kt
> ```
> 
> ?
> 
> This way, this file is going to be tracked :)

Done, thanks!

**Comment by jonalmeida** [comment]
bors r=pocmo

**Pull request merged**
