### PR TITLE
Upgrade Application Services to v61.0.4

### PR DESCRIPTION
**Pull request by eoger**
Fixes https://github.com/mozilla-mobile/android-components/issues/7435

### CODE REVIEW

**Comment by st3fan** [comment]
@grigoryk is this good to land?

**Comment by jonalmeida** [comment]
bors try

**Comment by jonalmeida** [comment]
bors retry

**Comment by grigoryk** [comment]
UI tests are happy; i'll do a quick local test run, and will merge this.

**Comment by thomcc** [comment]
Should use 61.0.5 now -- I can submit a PR for it if needed. The only difference is that it fixes the issue where we spammed error logging too much (https://github.com/mozilla/application-services/issues/3254)

**Comment by grigoryk** [comment]
`61.0.6` is available now.

**Comment by grigoryk** [comment]
bors try

**Comment by thomcc** [comment]
> 61.0.6 is available now.

Ah, nice catch, I forgot we did a point release just for automation reasons.

**Comment by grigoryk** [comment]
bors retry

**Comment by grigoryk** [comment]
bors cancel

**Comment by grigoryk** [comment]
bors retry

**Comment by grigoryk** [comment]
bors try

**Comment by pocmo** [comment]
Now bors should be happy.

bors r+

**Pull request merged**
