### PR TITLE
Upgrades appservices to 86.2.0

### PR DESCRIPTION
**Pull request by tarikeshaq**
Upgrades application services to 86.1.0. It's a non-breaking change with some improvement and bug fixes.

We're hoping to get this in for v95

Changelog:
# v86.1.0 (_2021-10-27_)

[Full Changelog](https://github.com/mozilla/application-services/compare/v86.0.0...v86.1.0)

### What's New

  - Rollouts: allows winning branch promotion and targeting rollouts of features. [#4567](https://github.com/mozilla/application-services/pull/4567).
    - for both Android and iOS.

### What's fixed
  - Fixed a bug in iOS where the installation date would be set to start of EPOCH ([#4597](https://github.com/mozilla/application-services/pull/4597))
  - Fixed a bug in Android where we were missing disqualification events after a global opt-out ([#4606](https://github.com/mozilla/application-services/pull/4606))

## Push

  - We've changed how the push database is opened, which should mean we now automatically handle
    some kinds of database corruption.

### What's changed
  - The bundled version of Glean has been updated to v42.0.1.
    See [the Glean Changelog](https://github.com/mozilla/glean/blob/v42.0.1/CHANGELOG.md) for full details.
    (Note there is a breaking change in Rust, but that doesn't impact consumers of Application Services)

### CODE REVIEW

**Comment by jonalmeida** [comment]
bors try

**Comment by tarikeshaq** [comment]
We released 86.2.0, so updated this PR to update to that instead! In addition to the changelog above, the changelog for 86.2.0:
# v86.2.0 (_2021-11-02_)

[Full Changelog](https://github.com/mozilla/application-services/compare/v86.1.0...v86.2.0)

## Push
### What's Changed
  - We've changed the database schema to avoid confusion about the state of subscriptions and
    in particular, avoid `SQL: UNIQUE constraint failed: push_record.channel_id` errors
    reported in [#4575](https://github.com/mozilla/application-services/issues/4575). This is
    technically a breaking change as a dictionary described in the UDL changed, but in practice,
    none of our consumers used it, so we are not declaring it as breaking in this context.

## Logins

### What's New

  - Added support for recording telemetry when the logins encryption key needs to be regenerated.
  
  cc @bendk

**Comment by jonalmeida** [comment]
bors try

**Review by eliserichards — APPROVED** [review]
Tested this new version with Fenix, looks good to me 👍

**Comment by eliserichards** [comment]
I'm confirming with the rest of the team before we merge this @tarikeshaq

**Review by jonalmeida — APPROVED** [review]
I tested a fresh and existing install with push without any bugs. I actually think this solved a push bug with web content too!

r+ and let's land it!

**Pull request merged**
