### PR TITLE
Closes #1314: Make AwesomeBar styleable.

### LINKED ISSUE #1314: Make AwesomeBar stylable
Just so that it can fit visually into other apps.

### PR DESCRIPTION
**Pull request by pocmo**

### CODE REVIEW

**Comment by Amejia481** [comment]
There're some CI errors.

  **| Android Components - Module :browser-awesomebar |**
 ```
Task :browser-awesomebar:testDebugUnitTest
mozilla.components.browser.awesomebar.SuggestionsAdapterTest > onCreateViewHolder() will create view holder matching layout id FAILED
    java.lang.NullPointerException at SuggestionsAdapterTest.kt:130
mozilla.components.browser.awesomebar.SuggestionViewHolderTest > DefaultViewHolder sets title and description FAILED
    java.lang.NullPointerException at SuggestionViewHolderTest.kt:27
mozilla.components.browser.awesomebar.SuggestionViewHolderTest > ChipsSuggestionViewHolder adds views for chips FAILED
    java.lang.NullPointerException at SuggestionViewHolderTest.kt:80
mozilla.components.browser.awesomebar.SuggestionViewHolderTest > Clicking on a chip invokes callback FAILED
    java.lang.NullPointerException at SuggestionViewHolderTest.kt:107
mozilla.components.browser.awesomebar.SuggestionViewHolderTest > Clicking on default suggestion view invokes callback FAILED
    java.lang.NullPointerException at SuggestionViewHolderTest.kt:47
19 tests completed, 5 failed
> Task :browser-awesomebar:testDebugUnitTest FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':browser-awesomebar:testDebugUnitTest'.
> There were failing tests. See the report at: file:///build/android-components/components/browser/awesomebar/build/reports/tests/testDebugUnitTest/index.html

```
**|Android Components - Module :browser-engine-gecko-nightly|**   

```
> Task :support-utils:transformClassesAndResourcesWithPrepareIntermediateJarsForDebug
w: -Xcoroutines has no effect: coroutines are enabled anyway in 1.3 and beyond
e: /build/android-components/components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt: (405, 46): Object is not abstract and does not implement abstract member public abstract fun onContentPermissionRequest(p0: GeckoSession!, p1: String!, @GeckoSession.PermissionDelegate.Permission p2: Int, p3: GeckoSession.PermissionDelegate.Callback!): Unit defined in org.mozilla.geckoview.GeckoSession.PermissionDelegate
e: /build/android-components/components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt: (406, 9): 'onContentPermissionRequest' overrides nothing
> Task :browser-engine-gecko-nightly:compileDebugKotlin FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':browser-engine-gecko-nightly:compileDebugKotlin'.
> Compilation error. See log for more details
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
```

**Comment by pocmo** [comment]
Oh, I'll fix up the tests to get this into the release.

**Comment by pocmo** [comment]
Merging for the release!

@Amejia481 Since this wasn't approved yet: Please file an issue if there's something you are not happy with and I'll address that in the next sprint. :)

**Comment by Amejia481** [comment]
👍

**Pull request merged**
