### PR TITLE
Closes #4917: Adds onCancelDownload callback 

### LINKED ISSUE #4917: showDialog called every time the app resumes after a download is processed.
If a user closes the download prompt, we're still presenting it again if they pause and resume the app.

I'm investigating this.

### PR DESCRIPTION
**Pull request by sblatz**
---

🤦‍♂ 
### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- [ ] **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- [ ] **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Comment by jonalmeida** [comment]
FYI: emojis fail PRs on taskcluster. ❌ 👎 😢

**Comment by sblatz** [comment]
@csadilek 
> @sblatz do we have an issue filed in Fenix for download UI tests? If not let's file one. :)

yes, we do: https://github.com/mozilla-mobile/fenix/issues/6363

> Actually, this looks like we can test in SimpleDownloadDialogFragmentTest to make sure we call cancel when the close button is hit?

Adding this test now.

**Comment by sblatz** [comment]
@csadilek ready for review again 😄

**Pull request merged**
