### PR TITLE
For #12853 - Add component for support features

### LINKED ISSUE #12853: Create component for support features
Based on the discussion [here](https://github.com/mozilla-mobile/android-components/pull/11889#discussion_r964249718), we should create a new component to contain all the support features.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21684)

### PR DESCRIPTION
**Pull request by Alexandru2909**
Added component for support features which hold functionality.

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/main/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/main/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### GitHub Automation
Fixes #12853

### CODE REVIEW

**Review by jonalmeida — COMMENTED** [review]
Thanks! This is the right idea, but let's use a better descriptive name - I'm not confident that 'support-features' is good enough.

When it comes to naming things I eventually lead to pinging @csadilek for suggestions. 😄

**Comment by hneiva** [comment]
> Thanks! This is the right idea, but let's use a better descriptive name - I'm not confident that 'support-features' is good enough.

+1

**Review by csadilek — CHANGES_REQUESTED** [review]
I don't have all context here, but it seems this is for the slow script observer feature? If so, can't this just live in [feature-session](https://github.com/mozilla-mobile/android-components/tree/main/components/feature/session/src/main/java/mozilla/components/feature/session)? This seems like a better place for it which has multiple features of a similar shape.

`support-features` kind of breaks the existing design/pattern:
- Feature components provide "Combined components to implement feature-specific use cases."
- Support components provide "generic helper code."

Combining these two doesn't seem right. Either it's a concrete re-usable feature if it has sufficient functionality then it's `feature-slow-script` or it's part of `feature-session`. :)

**Comment by jonalmeida** [comment]
> Either it's a concrete re-usable feature if it has sufficient functionality then it's `feature-slow-script` or it's part of `feature-session`.

The idea was find a place for the features like `ServiceWorkerSupport` and the new `SlowLoadingFeature`. You're right that we should just be using the `feature-session` component instead of trying to find another generic component that hold both of these.

@Alexandru2909 what do you think? I think I've lead you astray here - sorry!

**Comment by Alexandru2909** [comment]
The slow script observer does indeed connect an (concept) engine implementation with the browser session, as `feature-session` is described

Thank you all for your input, I'll make the changes to use `feature-session` in the slow script observer PR and close this one.

**Pull request closed without merging**
