### PR TITLE
Update application-services to v72.1.0

### PR DESCRIPTION
**Pull request by rfk**
This includes an updated version of nimbus-sdk, which fixes as bug with reading persisted data on from disk that is currently affecting Fenix nightly users. (Although IIUC it's only "affecting" them by preventing them from participating in experiments, it's not showing up as user-visible bustage).

This also fixes the library loading logic in the autofill component, meaning the workaround from https://github.com/mozilla/application-services/issues/3874 is no longer required. (The renaming of the autofill package came along as part of that fix, and puts it inline with other appservices packages).

### CODE REVIEW

**Review by travis79 — APPROVED** [review]
Thanks @rfk!

**Comment by grigoryk** [comment]
bors try

**Review by grigoryk — APPROVED** [review]
Thanks, Ryan!

I'll wait for the `try` run to come back green before landing.

**Comment by st3fan** [comment]
@grigoryk is this good to go?

**Comment by st3fan** [comment]
bors try

**Pull request merged**
