### PR TITLE
Upgrade Glean to v29.1.0

### PR DESCRIPTION
**Pull request by badboy**
---

### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Comment by mdboom** [comment]
It will change the range of acceptable values on GV metrics at the upper end of the range.  This will result in fewer errors when they overflow, and more correct results, and I think this is what we want.

At the lower end, incoming milliseconds could never be less than one millisecond anyway, so there is no change.

**Comment by Dexterp37** [comment]
> 
> 
> It will change the range of acceptable values on GV metrics at the upper end of the range. This will result in fewer errors when they overflow, and more correct results, and I think this is what we want.
> 
> At the lower end, incoming milliseconds could never be less than one millisecond anyway, so there is no change.

Cool, thanks @mdboom - so we don't expect any disruption in things that are already being collected, right?

**Comment by mdboom** [comment]
> Cool, thanks @mdboom - so we don't expect any disruption in things that are already being collected, right?

Nope.  Should be no disruption.  It didn't touch the multiplication of values or anything, just increased the maximum.

**Comment by Dexterp37** [comment]
> 
> 
> > Cool, thanks @mdboom - so we don't expect any disruption in things that are already being collected, right?
> 
> Nope. Should be no disruption. It didn't touch the multiplication of values or anything, just increased the maximum.

Lovely! @badboy let's get this party started then! 🎸

**Comment by badboy** [comment]
bors r=Dexterp37

**Pull request merged**
