### PR TITLE
Close #8471: Use transaction annotation for addAllPinnedSites

### LINKED ISSUE #8471: Perma failure: test-android-feature-top-sites : testAddingAllDefaultSites
https://firefox-ci-tc.services.mozilla.com/tasks/bPNz_VmqTDSEA3NX6Mnp5A/runs/0/logs/https%3A%2F%2Ffirefox-ci-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FbPNz_VmqTDSEA3NX6Mnp5A%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log

https://console.firebase.google.com/project/moz-android-components-230120/testlab/histories/bh.9f526cd30412cc12/matrices/5172220622059758972

It looks like the test just hangs and never completes?

### PR DESCRIPTION
**Pull request by jonalmeida**
Our use of withTransaction doesn't seem to work well with our testing
strategy for Room. It's easier to test and follow the code if we use the
DAO design pattern everywhere instead.

---

Close #8471

~@pocmo maybe we merge this if the UI test failures are not blocking the release?~ the PR to disable the test was merged.

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Comment by jonalmeida** [comment]
bors try

**Comment by jonalmeida** [comment]
Rebased on master to re-enable the tests as well.

**Comment by jonalmeida** [comment]
bors try

**Comment by jonalmeida** [comment]
Two rounds of try it's looking good. 👍

**Review by gabrielluong — APPROVED** [review]

**Review by gabrielluong — COMMENTED** [review]
Don't we need to re-enable the test too?

**Pull request merged**
