### PR TITLE
Update Android Gradle Plugin to version 3.5.3.

### PR DESCRIPTION
**Pull request by pocmo**
3.5.2 -> 3.5.3.

### CODE REVIEW

**Comment by pocmo** [comment]
bors r=psymoon

**Comment by Amejia481** [comment]
bors retry

**Comment by pocmo** [comment]
bors retry

**Comment by jonalmeida** [comment]
bors retry

**Comment by jonalmeida** [comment]
bors retry

**Comment by jonalmeida** [comment]
bors retry

external-content duckduckgo com

**Pull request merged**
