### PR TITLE
Run taskgraph generation with Python 3

### PR DESCRIPTION
**Pull request by ahal**

### CODE REVIEW

**Comment by ahal** [comment]
The `build-docker-image-ui-tests` seems to be perma failing. I suspect it's failing due to updating to the latest taskgraph (rather than the Python 3 conversion). Maybe I should split that into a separate PR.

**Comment by ahal** [comment]
Actually that task doesn't appear to be scheduled on other PRs, so it's also possible it's been busted for awhile and no one noticed.

**Comment by ahal** [comment]
I pushed a [dummy change](https://github.com/mozilla-releng/staging-android-components/commit/fe01829940e3c58dbfee7cb0587ab45978c2ed72) to staging-android-components to see if `build-docker-image-ui-tests` fails without upgrading taskgraph, and [it does](https://firefox-ci-tc.services.mozilla.com/tasks/drqkTFxqSYuo-mSl6JEUZw).

So I'm quite certain it's unrelated to this PR. Maybe it's something we need to fix before this can merge though? I'll request review at any rate.

**Review by escapewindow — APPROVED** [review]

**Comment by jonalmeida** [comment]
Shot in the dark: @ahal the toolchain task seems to be failing as well, which may be related to the ui-tests tasks failing as well?

**Comment by ahal** [comment]
Hm, that only started failing on this latest rebase. I haven't seen it fail prior to this run (the `build-docker-image-ui-tests` task still appears to be perma-fail on master).

**Pull request merged**
