### PR TITLE
The Play/Pause button should remain displayed on the media notification

### PR DESCRIPTION
**Pull request by iorgamgabriel**
### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/main/docs/changelog.md) or does not need one
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/main/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Comment by iorgamgabriel** [comment]
https://user-images.githubusercontent.com/8118371/177516693-95b53050-6bcf-4941-a32d-9eb32da1e057.mp4

**Comment by rocketsroger** [comment]
There is an issue with the change.  Currently when a video is paused, the user can swipe the notification away.  However, with this change, as long as there is a in progress video tab open (could be multiple) the user cannot swipe away the notification unless they close the tab(s).

**Comment by iorgamgabriel** [comment]
I reproduced the bug . Thank you very much for the info . I will fix it .

**Comment by rocketsroger** [comment]
> I reproduced the bug . Thank you very much for the info . I will fix it . @rocketsroger

Thanks!

**Comment by iorgamgabriel** [comment]
https://user-images.githubusercontent.com/8118371/177740922-fbcf6133-ddae-492c-a07c-bbc6b3193313.mp4


https://user-images.githubusercontent.com/8118371/177740965-7b0c37e4-de8f-4a21-bc56-587a1efcc06d.mp4

**Comment by iorgamgabriel** [comment]
I checked you can swipe the notification away if it's not expanded both for play or pause . This is the same behaviour like on main branch , I didn't changed that . I attached two videos

**Comment by iorgamgabriel** [comment]
On the main branch you can remove the notification because you stop the service when the user press "Stop" from notification. 
Because you stop the  service when the user press "Stop" and you start it when he press "Play" this bug is happening and the notification  flicks . 
I don't think it's a good idea to start and stop the service every time . @rocketsroger

**Comment by rocketsroger** [comment]
> I don't think it's a good idea to start and stop the service every time . @rocketsroger

Agreed that starting and stopping is causing us a lot of trouble.  Unfortunately, the requirement is to allow the user to swipe away the notification when they are not actively playing a media.  Please understand that if a user is unable to swipe a way the media notification and the only way is to close Fenix completely or close all media tabs then it's not acceptable.

**Pull request closed without merging**
