### PR TITLE
Uniffi sync manager / Upgrade to A-S 87.1.0

### PR DESCRIPTION
**Pull request by bendk**
Updating the a-c code to work with the new UniFFI Sync Manager API

Definitely don't merge this one, it's based on a-s code that hasn't merged yet as well as #11217.

### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/main/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/main/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Comment by bendk** [comment]
I think this one might be ready to merge.  It brings in the new UniFFIed sync manager API.  I'm not sure why some of the CI is failing, but it seems like it might be temporary to me.

**Comment by eliserichards** [comment]
bors try

**Review by eliserichards — APPROVED** [review]
Looks good! I tested with Fenix and everything seems to be working as expected 👍

**Comment by eliserichards** [comment]
We're going to wait to land this until: 
* [86.2.1 is landed](https://github.com/mozilla-mobile/android-components/pull/11353)
* We cut a new release for 87.X.X

**Comment by eliserichards** [comment]
Just did another round of testing with AS 87.1.0 and everything looks great! Let's get this merged 🙌

**Comment by eliserichards** [comment]
Looks like there were some "unexpected failures". Let's try again..

**Comment by eliserichards** [comment]
@mergifyio rebase

**Pull request merged**
