### PR TITLE
Closes #5606: Re-use sessionToken during FxA migration

### LINKED ISSUE #5606: Fennec migration: Connected devices shows the same device with both Fennec and Fenix after migration
STR: 
1. Connect to sync on Fennec. Check the devices list on desktop, in account settings.
2. Migrate to Fenix.
3. Check the devices list on desktop, in account settings.

Expected results:
The device list shows the current mobile device only once. 

Actual results:
The list still shows the device both with Fennec and Fenix: https://www.screencast.com/t/aOAYlRMquh

### PR DESCRIPTION
**Pull request by grigoryk**
---

### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- [ ] **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- [ ] **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Comment by grigoryk** [comment]
Tested this out locally, both in an offline fxa migration mode (✈️ turned on), and regular migration. In both cases, default and custom device names from Fennec were retained, and `Devices & apps` section lists the same device (no new ones created) after the migration.

**Comment by pocmo** [comment]
Looks good. But seems to break tests in `support-migration`?

**Comment by rfk** [comment]
> In both cases, default and custom device names from Fennec were retained,
> and Devices & apps section lists the same device (no new ones created) after the migration.

@grigoryk that's great! Did you happen to notice whether it also fixes the "I got a weird email from Firefox Accounts about a new sign-in" problem? I expect it will, but nice to confirm.

**Comment by grigoryk** [comment]
> @grigoryk that's great! Did you happen to notice whether it also fixes the "I got a weird email from Firefox Accounts about a new sign-in" problem? I expect it will, but nice to confirm.

@rfk it does indeed!

**Comment by grigoryk** [comment]
bors r=pocmo

**Pull request merged**
