### PR TITLE
Closes #5284: Adds progress bar to downloads

### LINKED ISSUE #5284: Show progress of download on notification
For fenix https://github.com/mozilla-mobile/fenix/issues/4525

### PR DESCRIPTION
**Pull request by sblatz**
---

### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- [ ] **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- [ ] **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Comment by sblatz** [comment]
I've run the CI on this a few times now and it doesn't seem to have any intermittent out of memory issues or test failures 😄 

Thanks @jonalmeida, @pocmo, & @csadilek for all of your help getting this work done.

**Comment by sblatz** [comment]
bors r=csadilek

**Comment by csadilek** [comment]
Unrelated failure in ui-fonts.

**Comment by sblatz** [comment]
bors retry

**Comment by csadilek** [comment]
bors retry

**Pull request merged**
