### PR TITLE
For #7512 - Set parent session as selected session in NewTabSearchUse…

### PR DESCRIPTION
**Pull request by ekager**
…Case

---

### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Comment by ekager** [comment]
Meh good point. Was trying to keep it simple but that's impossible 😢

**Comment by ekager** [comment]
bors r=NotWoods

**Comment by ekager** [comment]
bors retry

**Comment by jonalmeida** [comment]
@ekager it looks like something needs to be fixed on the failing components:

```
[task 2020-06-26T17:55:55.863Z] > Task :feature-awesomebar:compileDebugKotlin FAILED
[task 2020-06-26T17:55:55.863Z] e: /builds/worker/checkouts/src/components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/SearchSuggestionProvider.kt: (195, 35): Cannot access class 'mozilla.components.browser.session.Session'. Check your module classpath for missing or conflicting dependencies
[task 2020-06-26T17:55:55.863Z] e: /builds/worker/checkouts/src/components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/SearchSuggestionProvider.kt: (223, 31): Cannot access class 'mozilla.components.browser.session.Session'. Check your module classpath for missing or conflicting dependencies
[task 2020-06-26T17:55:55.962Z] 
```

**Comment by ekager** [comment]
bors retry

**Pull request merged**
