### PR TITLE
For #12384 - Add optional filter for top frecent sites

### PR DESCRIPTION
**Pull request by Alexandru2909**
### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/main/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/main/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Review by gabrielluong — APPROVED** [review]

**Comment by Amejia481** [comment]
@Alexandru2909 is this ready for landing? :)

**Comment by Alexandru2909** [comment]
> @Alexandru2909 is this ready for landing? :)

I want to wait for https://github.com/mozilla-mobile/fenix/pull/25766  to be approved since this PR contains breaking changes.

**Comment by Amejia481** [comment]
Awesome, I'll review it!

**Comment by Amejia481** [comment]
I reviewed and approved ✅ the Fenix PR. Could we also add an entry to the change log as this is introducing a breaking change :)

**Pull request merged**
