### PR TITLE
For #7833: Generate concept-menu items for addons 

### PR DESCRIPTION
**Pull request by NotWoods**
Down the line, we can change the menu so that it just responds to browser state updates instead of having a couple of components change the menu themselves. This is part of that work for addons. No changelog yet as this is just groundwork for later.

Addons previously used global maps to cache view holders, but that's not needed with the concept-menu API.

---

Builds on #8237

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Comment by jonalmeida** [comment]
Adding Arturo for a second set of eyes on the WebExtension changes.

**Review by Amejia481 — COMMENTED** [review]
Let's fix the conflicting files and continue with the review :)

**Review by jonalmeida — APPROVED** [review]
This looks good to me functionally although, I'm more keen for @Amejia481 's final review.

I think I'm going to be taking over this work and Tiger has already addressed the previous feedback.

**Review by Amejia481 — APPROVED** [review]
🚢 !

**Pull request merged**
