### PR TITLE
For #2740. Update detekt to 1.0.0-RC14.

### PR DESCRIPTION
**Pull request by dector**
The latest version is `1.0.0-RC15` but it's [crashing for now](https://github.com/arturbosch/detekt/issues/1686#issuecomment-502116166) (reproduced on my environment).

#### 1.0.0-RC13 [changes](https://arturbosch.github.io/detekt/changelog-rc.html#rc13)

  - Removed `*Spek.kt` from `test-pattern` because of:
    > Files matching .*/androidTest/.* and *Spek.kt are now part of the test-pattern by default.

  - Updated baseline because of changed implementation:
    > LongMethod and LargeClass rules got refactored and now count source lines of code and not statements anymore. You may need to change your defaults.
  - __(Probably limits should be increased for for `LongMethod` and `LargeClass`)__

### Pull Request checklist
- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] ~~**Tests**: This PR includes thorough tests or an explanation of why it does not~~
- [x] ~~**Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one~~
- [x] ~~**Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features~~

### CODE REVIEW

**Comment by dector** [comment]
@pocmo `detekt 1.0.0-RC13` introduced _(breaking)_ change:

> LongMethod and LargeClass rules got refactored and now count source lines of code and not statements anymore. You may need to change your defaults.

However, [arturbosch writes:](https://github.com/arturbosch/detekt/pull/1448)

> With this change, our thresholds may be to restrictive with (150 & 20 lines). Pmd has defaults of 1000 for LargeClass and 100 for LongMethod.
> 
> There are anecdotal evidence here and here that in Kotlin you write ~40% less code. Therefore, how about defaults of 600 and 60?

**Comment by pocmo** [comment]
Sounds good. But we'll have to regenerate the baseline on top of master (where the file was deleted) to resolve the conflict.

**Comment by dector** [comment]
@pocmo Sorry, forgot to leave comment when rebased.

**Comment by pocmo** [comment]
Argh. After merging some other PRs first this one is not passing anymore since the baseline file is not covering everything now. :(

**Comment by dector** [comment]
Recreated baseline.

**Comment by pocmo** [comment]
Awesome, thank you, @dector. This time I'll quickly merge it. :)

**Pull request merged**
