### PR TITLE
Closes #4618. Publish `tooling-detekt` package into maven repository.

### LINKED ISSUE #4618: Publish `tooling-detekt` to maven repository for internal usage.
And let other projects use it.

For [mozilla-mobile/fenix/3880](https://github.com/mozilla-mobile/fenix/issues/3880)

### PR DESCRIPTION
**Pull request by dector**
---

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] ~~**Tests**: This PR includes thorough tests or an explanation of why it does not~~
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [x] ~~**Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features~~

### After merge
- [ ] **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- [ ] **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Comment by dector** [comment]
Not updating changelog intentionally as we are using detekt rules internally. Should I do it anyway?

**Comment by jonalmeida** [comment]
@dector after adding a changelog entry, you can comment with `bors r=jonalmeida` and that would auto-land the PR with my r+.

Thank you for the plugin, it's uber cool! :)

**Comment by dector** [comment]
@jonalmeida My pleasure. ^_^

**Comment by dector** [comment]
Updated module `README` file with rules description.

**Comment by dector** [comment]
bors r=jonalmeida

**Comment by Amejia481** [comment]
bors r=jonalmeida

**Pull request merged**
