### PR TITLE
Closes #1072: Make Keystore class open.

### LINKED ISSUE #1072: DataProtect: Make `Keystore` class `open` for client tests
We need to mock the `Keystore` class in DataProtect for our tests. To do this, the class needs to be `open` rather than `final`.

### PR DESCRIPTION
**Pull request by pocmo**
CC @linuxwolf

### CODE REVIEW

**Comment by linuxwolf** [comment]
@sashei how may of the methods within do you need to be `open`?  My preference would be to keep that set to a minimum ...

**Comment by sashei** [comment]
specifically `encryptBytes` and `decrypteBytes` would be good.

**Comment by pocmo** [comment]
Oh, sorry, I forgot that the method will be `final` too. I'll open up the two methods and land.

**Comment by pocmo** [comment]
@sashei @linuxwolf I updated the PR and opened up encryptBytes() and decryptBytes() too. Will this help you with testing?

Another options may be that we introduce an interface that `Keystore` implements and Lockbox code just cares about the interface which will be easier to mock. But would that be worth it?

**Comment by sashei** [comment]
@pocmo I think the implementation details are up to you. I'm generally opposed to interfaces for the sake of interfaces but if you feel the pattern makes sense here we're happy to take advantage of it for testing!!

**Pull request merged**
