### PR TITLE
Upgrade Application Services to v60.0.0

### PR DESCRIPTION
**Pull request by gabrielluong**
---

### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Comment by gabrielluong** [comment]
bors r=eoger

**Comment by gabrielluong** [comment]
bors retry

**Comment by jonalmeida** [comment]
We're going to try running some UI tests on this upgrade from our automation. 🙂

**Comment by jonalmeida** [comment]
bors try

**Comment by grigoryk** [comment]
> ## try
> 
> Build succeeded:
> 
>     * [complete-push](https://github.com/mozilla-mobile/android-components/runs/732805312)

Nice! This ran the `ui-test-browser` set of tests on devices, which launch sample-browser and open some tabs.
Now that sample-browser is built using megazord and places storage, this exercised our megazord setup and A-C/A-S stack end-to-end, at least on the configured set of APIs/devices. Currently that's pretty limited, e.g. we don't run API21 tests, but that's easy to change.

**Comment by grigoryk** [comment]
bors try

**Comment by grigoryk** [comment]
bors try

**Comment by grigoryk** [comment]
Also note that ui tests are currently not blocking (e.g. `complete-push` does not depend on them). So for now, make sure to look at the actual result of the job.

Above, I've accidentally specified illegal device model for the api version. Let's try this with a Nexus6/21 combo.

**Comment by grigoryk** [comment]
Nice, "basic sanity check" UI tests now successfully run on API28,21.

**Pull request merged**
