### PR TITLE
Use `android-components-g` Taskcluster worker type.

### PR DESCRIPTION
**Pull request by ncalexan**

### CODE REVIEW

**Comment by grigoryk** [comment]
@ncalexan is is currently waiting for https://github.com/mozilla-mobile/android-components/pull/1588 to land?

**Comment by ncalexan** [comment]
> @ncalexan is is currently waiting for #1588 to land?

I've completely lost track of this work, and I can't parse the question.  I think the releng folks (@JohanLorenzo and @mitchhentges) added dedicated a-c worker types, which should address the caching, so my earlier PR might not be needed anymore.

**Comment by grigoryk** [comment]
@ncalexan we're still using shared `github-worker` for all of the tasks our decision task schedules.

**Comment by grigoryk** [comment]
@ncalexan scope of https://github.com/mozilla-mobile/android-components/pull/1588 changes doesn't seem to extend to changing how actual module tasks are scheduled, either.

**Comment by grigoryk** [comment]
I've ended up doing this in https://github.com/mozilla-mobile/android-components/pull/1638, along with other tweaks.

**Pull request closed without merging**
