### PR TITLE
Update application-services to v67.2.0

### PR DESCRIPTION
**Pull request by rfk**
In theory this should resolve a crasher and a perf issues with the Nimbus SDK, since it transitively pulls in an updated version of Nimbus.

I manually a build of Fenix using this PR with local app data from an older version, and confirmed that it does not have the "JSON Error" crash noticed by @csadilek in #9177. I also tried running it with the network disabled (actually, running in the emulator and yanking the network cable on the host machine) and it reported the failure to fetch experiments to adb logcat, but didn't seem to crash or otherwise misbehave.

### CODE REVIEW

**Comment by jonalmeida** [comment]
Toolchain task is failing because we're running out of memory in CI as documented here: https://github.com/mozilla-mobile/android-components/pull/9178

```
[task 2020-12-10T06:37:06.996Z] warn: removing resource mozilla.components.browser.thumbnails.test:string/mozac_browser_errorpages_page_title without required default value.
[task 2020-12-10T06:37:06.996Z] 
[task 2020-12-10T06:37:06.996Z] ----- End of the daemon log -----
[task 2020-12-10T06:37:06.996Z] 
[task 2020-12-10T06:37:06.996Z] JVM crash log found: file:///builds/worker/checkouts/src/hs_err_pid1677.log
[task 2020-12-10T06:37:07.001Z] 
[task 2020-12-10T06:37:07.001Z] FAILURE: Build failed with an exception.
[task 2020-12-10T06:37:07.001Z] 
[task 2020-12-10T06:37:07.001Z] * What went wrong:
[task 2020-12-10T06:37:07.001Z] Gradle build daemon disappeared unexpectedly (it may have been killed or may have crashed)
[task 2020-12-10T06:37:07.001Z] 
```

**Comment by rfk** [comment]
> Toolchain task is failing because we're running out of memory in CI 

Do you think this is something specific to the appservices update, or unrelated?

**Comment by jonalmeida** [comment]
> > Toolchain task is failing because we're running out of memory in CI
> 
> Do you think this is something specific to the appservices update, or unrelated?

It seems to have been unrelated. I've pushed a change that should fix this. See https://github.com/mozilla-mobile/android-components/pull/9178#issuecomment-742436726 for details.

**Comment by jonalmeida** [comment]
@csadilek and I did some testing with this PR when the device was in the bad state and we didn't see any crashes. Also did a smoke test for everything else.

**Review by jonalmeida — APPROVED** [review]

**Comment by jonalmeida** [comment]
Blerg, since the previous [build worked](https://firefox-ci-tc.services.mozilla.com/tasks/groups/LNXBHoBxSP2zuEBJuNZ32w) with this fix, we're going to retry it again.

**Pull request merged**
