### PR TITLE
fenix issue 18798

### PR DESCRIPTION
**Pull request by ryg-git**
### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Comment by ryg-git** [comment]
I opened this pull request because I was working on issue [#18798](https://github.com/mozilla-mobile/fenix/issues/18798) of [fenix repository](https://github.com/mozilla-mobile/fenix),
I found out that sometimes some websites fetch articles (`readerable` content) after url location
change and while fetching show loading screen like in case of [telegram.hr](https://telegram.hr/) as described in the
issue. Therefore I thought checking if the page is `readerable` is necessary after every `engineSessionState` 
change, this resolves the issue but if there is even better way to fix the issue or something I missed while 
opening the PR please let me know.

**Comment by eliserichards** [comment]
This seems to behave the same on desktop, so it is likely a site-specific issue. We may not want to move forward with this PR as it will likely break other pages 😕

**Review by csadilek — CHANGES_REQUESTED** [review]
Thanks for investigating, @ryg-git.

Unfortunately, there's no clean and reliable way to fix this as part of the Android component here. I've added some more details in https://github.com/mozilla-mobile/fenix/issues/18798#issuecomment-823624605 with a link to the upstream repository we should file this against.

The change here introduces additional complexity (and is also affecting all page loads) to work around a timing issue with this particular site's readability detection. The fact that you see better results with this change is due to running an additional check at a later point in time which is not going to work reliably on all devices.

Let's file an upstream issue instead and see if this can be fixed / worked around. Then it will work on Desktop as well.

**Comment by ryg-git** [comment]
Yes it definitely does make sense move the issue upstream since issue exists on other platforms also, thanks for the review.

**Comment by csadilek** [comment]
Thanks again @ryg-git, I will close this PR then.

**Pull request closed without merging**
