### PR TITLE
Issue #5989: Create LocationService interface and make MozillaLocatioService implement it.

### PR DESCRIPTION
**Pull request by pocmo**
---

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- [x] **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- [x] **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Comment by pocmo** [comment]
@boek This allows us to use a dummy location provider in builds that shouldn't talk to MLS. Nevertheless I think we should figure out what code is making those requests - since `SearchEngineManager` should only try once. 🤔

**Comment by jonalmeida** [comment]
We can land this when the conflicts in the changelog are fixed.

**Comment by pocmo** [comment]
Rebased!

**Comment by pocmo** [comment]
bors r=jonalmeida

**Pull request merged**
