### PR TITLE
Update changelog device constellation API entry [ci skip]

### PR DESCRIPTION
**Pull request by jonalmeida**
---

### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- [ ] **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- [ ] **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Comment by Amejia481** [comment]
@jonalmeida this PR is moving back to 9.0.0 the entry below,  it should be in 10.0.0  as this pr did https://github.com/mozilla-mobile/android-components/pull/4171
```
 **feature-toolbar**
  * Toolbar Menu is now closed on exiting the app.
```

**Comment by jonalmeida** [comment]
@Amejia481 oops, bad conflict resolution on my part, thanks!

**Comment by Amejia481** [comment]
No worries 👍

**Pull request merged**
