### PR TITLE
Import strings from android-l10n.

### PR DESCRIPTION
**Pull request by Pike**
State: mozilla-l10n/android-l10n@d10506f5697e7c2a286d4934755404bd768246fa

### CODE REVIEW

**Comment by Amejia481** [comment]
There is a lint issue on TC
```
> Task :lib-crash:jacocoTestReport
> Task :lib-crash:test
> Task :support-base:prepareLintJarForPublish
> Task :support-ktx:prepareLintJarForPublish
> Task :support-utils:prepareLintJarForPublish

> Task :lib-crash:lintRelease
Wrote HTML report to file:///build/android-components/components/lib/crash/build/reports/lint-results-release.html
Wrote XML report to file:///build/android-components/components/lib/crash/build/reports/lint-results-release.xml

> Task :lib-crash:lintRelease FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':lib-crash:lintRelease'.
> Lint found errors in the project; aborting build.
  
  Fix the issues identified by lint, or add the following to your build script to proceed with errors:
  ...
  android {
      lintOptions {
          abortOnError false
      }
  }
  ...
  
  Errors found:
  
  /build/android-components/components/lib/crash/src/main/res/values/strings.xml:25: Error: Inconsistent number of arguments in formatting string mozac_lib_send_crash_report_in_progress; found both 0 and 1 [StringFormatCount]
      <string name="mozac_lib_send_crash_report_in_progress">Sending crash report to %1$s</string>
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      /build/android-components/components/lib/crash/src/main/res/values-es/strings.xml:22: Conflicting number of arguments here
  


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

```

**Comment by Pike** [comment]
I've opened https://github.com/mozilla-l10n/android-l10n/pull/86 to have a conversation.

While this is an obvious bug, there's also l10n habits like rewording phrases to avoid brand names, that benefit from not having to use an argument.

**Comment by Pike** [comment]
This should include the fixes from the PR over in `android-l10n`.

**Comment by pocmo** [comment]
bors retry

**Pull request merged**
