### PR TITLE
Close #4819: Update Firebase Cloud Messaging version

### LINKED ISSUE #4819: Update Firebase Cloud Messaging dependencies to 25.0.0+
There were breaking changes involved in 19.0.0 that provided better support for Kotlin<sup>[1]</sup>, bettter API annotations, and also stability/bug fixes.

Current version: 17.3.4

[1]: https://firebase.google.com/support/release-notes/android#2019-06-17

### PR DESCRIPTION
**Pull request by jonalmeida**
Fenix requires a breaking API change: https://github.com/mozilla-mobile/fenix/pull/16191

I've tested this change in Fenix by receiving a web content-based push message and received a Send Tab from Firefox Sync.

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Review by pocmo — APPROVED** [review]

**Comment by jonalmeida** [comment]
I refuse.

**Comment by jonalmeida** [comment]
external-content duckduckgo com

**Comment by jonalmeida** [comment]
external-content duckduckgo com

**Comment by jonalmeida** [comment]
To safely land this upgrade, we put up a change recover from send tab failures, but that [doesn't seem to be happening](https://github.com/mozilla-services/autopush/issues/1445#issuecomment-736969390). 😕 

What we do know now is that getting a new update token call won't effect existing subscriptions though, so maybe we can go ahead with this either way.

**Comment by jonalmeida** [comment]
external-content duckduckgo com

**Comment by jonalmeida** [comment]
external-content duckduckgo com

**Comment by jonalmeida** [comment]
external-content duckduckgo com

**Pull request merged**
