### PR TITLE
Upgrade to A-S 84.0.0 (resolves push and places breaking changes)

### PR DESCRIPTION
**Pull request by tarikeshaq**
fixes https://github.com/mozilla/application-services/issues/4425

Quick Summary: We are `uniffi`ing the push component 🎉 !  This PR is to get feedback on the impact on android components the upcoming breaking changes on https://github.com/mozilla/application-services/pull/4431 will have

NOTE: that PR is not merged yet, intentionally for two reasons:
- There is already a bunch of breaking changes on `application-services`'s main, we will probably cut a release to resolve those first
- To gather feedback here on the breaking changes there in case anything needs to change

## Summary of changes
- `PushAPI` is gone, replaced directly by `PushManager`
- `channelID` becomes `channelId` in all the API calls and types, looks like this aligns better with what android components does 😄!
- `PushError` becomes `PushException`, as so do all its variants
- `decrypt` returns a `List<Byte>` instead of a `ByteArray`, all I needed to add on the android components side is a `.toByteArray` and it works ok

~~To make the project build and tests to run on my local application-services, I had to fix the breaking changes in application services, I separated them into their own commit. **The only relevant commit for feedback is the second one!**~~ rebased this on top of the latest main with the fixes.

I can't add reviewers, but CC: @jonalmeida

### CODE REVIEW

**Review by jonalmeida — COMMENTED** [review]
Wonderful! This looks less daunting than I expected. 😅

**Comment by jonalmeida** [comment]
Wonderful! This looks less daunting than I expected. 😅

> I can't add reviewers, but CC: @jonalmeida

Codeowners notifies the right people. :)

**Review by grigoryk — APPROVED** [review]
Looks good to me.

Let's turn this into a "Upgrade to A-S 84.0.0" PR. I can push changes from https://github.com/mozilla-mobile/android-components/pull/10976 to this branch.

**Review by grigoryk — APPROVED** [review]

**Comment by grigoryk** [comment]
```
[task 2021-09-14T04:36:54.189Z]   TEST: BrowserAwesomeBar forwards input to providers
[task 2021-09-14T04:36:54.189Z]     [Robolectric] mozilla.components.browser.awesomebar.BrowserAwesomeBarTest.BrowserAwesomeBar forwards input to providers: sdk=28; resources=binary
[task 2021-09-14T04:36:54.189Z]     I/MonitoringInstr: Instrumentation started!
[task 2021-09-14T04:36:54.289Z]   FAILURE
[task 2021-09-14T04:36:54.289Z] 
[task 2021-09-14T04:36:54.290Z] java.lang.AssertionError: expected:<4> but was:<3>
[task 2021-09-14T04:36:54.290Z] 	at org.junit.Assert.fail(Assert.java:88)
[task 2021-09-14T04:36:54.290Z] 	at org.junit.Assert.failNotEquals(Assert.java:834)
[task 2021-09-14T04:36:54.290Z] 	at org.junit.Assert.assertEquals(Assert.java:118)
[task 2021-09-14T04:36:54.290Z] 	at org.junit.Assert.assertEquals(Assert.java:144)
[task 2021-09-14T04:36:54.290Z] 	at mozilla.components.browser.awesomebar.BrowserAwesomeBarTest$BrowserAwesomeBar forwards input to providers$1.invokeSuspend(BrowserAwesomeBarTest.kt:80)
```

**Pull request merged**
