### PR TITLE
Rename RemoteTabsFeature to SyncTabsFeature

### PR DESCRIPTION
**Pull request by espertus**
This addresses issue #5272.

---

I did not add tests because this is just a rename. 
### Pull Request checklist

- [X] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [X] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [X] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [X] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- [ ] **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- [ ] **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Comment by eoger** [comment]
Thanks! I believe there was a mention of Remote Tabs in `README.md` that you missed :)
Do we also want to rename `RemoteTabsStorage`?

**Comment by jonalmeida** [comment]
> Do we also want to rename `RemoteTabsStorage`?

Oh, maybe I wrongfully suggested this to @espertus [in the issue](https://github.com/mozilla-mobile/android-components/issues/5272#issuecomment-567688841)?

**Comment by espertus** [comment]
> Thanks! I believe there was a mention of Remote Tabs in `README.md` that you missed :)

Good catch! Fixed.

> Do we also want to rename `RemoteTabsStorage`?

As @jonalmeida commented, he told me in issue #5385 not to. I am happy to do whatever you two decide.

**Comment by jonalmeida** [comment]
> As @jonalmeida commented, he told me in issue #5385 not to. I am happy to do whatever you two decide.

Edouard is on PTO. If he feels strongly about this, we can always add a follow-up.

If you could fix the changelog conflict, let's get it merged then! :)

**Comment by espertus** [comment]
Thanks for completing the review. I'm on vacation. Unless you want to
change and merge this yourself, I will look at it in the new year.

**Comment by espertus** [comment]
The failures don't seem to be related to my changes, but I'd welcome others' opinions.

**Pull request merged**
