### PR TITLE
 Closes #4490: Resized icons on the toolbar. 

### LINKED ISSUE #4490: Re-size icons in the toolbar
Issues to address:

1. Reduced visibility of the URL
2. Unused space on the three dotted menu
3. Better distribution of the space on custom tabs

___________

### 1. Reduced visibility of the URL
As we added the new tracking protection icon on the toolbar, we didn't distributed the space accordingly to not affect the visible portion of the url.

Fennec vs Fenix on OnePlus 5T (the red lines represent 25% and 75% of total width)
image
image

____________

### 2. Unused space on the three dotted menu

The three dot menu has a lot of unused space, as you can see in the image below

image

The issue here is that we are doubling the padding, between **the right tab counter and left three dotted menu**, creating a huge gap between them.

image

This is caused because the tab counter adds the same amount of padding to the right as the three dotted menu adds to the left ( tab counter right padding 16dp + three dotted menu left padding 16dp = **32dp** padding between them instead of **16dp**).

____________

### 3. Better distribution of the space on custom tabs

As you can seen in the image below we are not doing a smart use for the space in custom tab, there is a lot of space that can be redistributed, to show more url and title.

image

Related issues: https://github.com/mozilla-mobile/fenix/issues/4560, https://github.com/mozilla-mobile/fenix/issues/3727 and https://github.com/mozilla-mobile/fenix/issues/5480

### PR DESCRIPTION
**Pull request by Amejia481**
Related https://github.com/mozilla-mobile/android-components/issues/1514
**Updated pics**

**Now**
image

**Before**
image

**Now**
image

**Before**
image

---

### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- [ ] **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- [ ] **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Comment by cadeyrn** [comment]
So much better! ❤️ Could the space between the tab counter and the three dots icon also be reduced or does this change not belong to this PR?

**Comment by Amejia481** [comment]
Is this better?
**Now**
image

**Before**
image

**Comment by cadeyrn** [comment]
Perfect! 😊

**Pull request merged**
