### PR TITLE
Closes #4311: Remove Top and Bottom Padding Causing Issues with Text Alignment and Clipping

### LINKED ISSUE #1442: Add Setting for reading/setting GeckoView user agent
So far we could only do that for WebView. But now we can read and set the user agent for GeckoView builds too:

* https://bugzilla.mozilla.org/show_bug.cgi?id=1454444
* https://bugzilla.mozilla.org/show_bug.cgi?id=1507369

### LINKED ISSUE #4311: [Bug] EditToolBar Text is not Vertically Centered if Toolbar Size is Set to 40dp
Currently EditToolBar Works well when toolbar size is set to 56dp or above.  However, when it is set to less than 56dp, the text is no longer centered.

### PR DESCRIPTION
**Pull request by rocketsroger**
…Alignment and Clipping

---

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- [ ] **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- [ ] **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Comment by rocketsroger** [comment]
Left image is the fixed version.  Right image is the original.  Font was changed to largest to reproduce the issue.
image

**Comment by jonalmeida** [comment]
The linked issue seems unrelated. I think you were referencing a Fenix issue?

**Comment by rocketsroger** [comment]
> The linked issue seems unrelated. I think you were referencing a Fenix issue?

You're right.  This issue is on the Fenix side.  I'll open a A-C issue and change the commit message to point to the new one.  Thanks,

**Comment by rocketsroger** [comment]
> I wonder if it makes sense to also add ellipses as well for smaller screens. Notice the last 's' in 'address' is hidden.

Sure I'll look into adding that.  Thanks,

**Comment by jonalmeida** [comment]
> > I wonder if it makes sense to also add ellipses as well for smaller screens. Notice the last 's' in 'address' is hidden.
> 
> Sure I'll look into adding that. Thanks,

I filed https://github.com/mozilla-mobile/android-components/issues/4312 for this. We can still merge this and do that later since it's not related to this bug. :)

**Comment by rocketsroger** [comment]
> I filed #4312 for this. We can still merge this and do that later since it's not related to this bug. :)

Cool thanks,

**Pull request merged**
