### PR TITLE
Closes #7013 fix mozac_browser_engine_system_auth_message description comment

### LINKED ISSUE #7013: Fix mozac_browser_engine_system_auth_message description comment
Related issue https://github.com/mozilla-mobile/android-components/pull/6883#discussion_r420798867

### PR DESCRIPTION
**Pull request by Amejia481**
cc: @flodolo

---

### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Comment by flodolo** [comment]
Please only change en-US, Pontoon will take care of the comments.

Also, I don't think we support getting localization changes back in automation.

**Comment by Amejia481** [comment]
👍

**Comment by Amejia481** [comment]
@flodolo updated :)

**Comment by Amejia481** [comment]
bors r=psymoon

**Pull request merged**
