### PR TITLE
Closes #10241: Stop announcing loading to accessibility when progress is at max

### LINKED ISSUE #10241: Announce "loading" in accessibility only when progress has not finished
Currently we announce loading to accessibility when progress is at 100%.  This is caused by short loading that goes straight to 100%.  Visibility this is not an issue because the progress bar is not visible at 100%.  However, for Talkback users this is very noticeable when they keep hearing "loading" between paragraphs/lines.

Stop announcing "loading" to accessibility when progress is at 100%.
This is for https://github.com/mozilla-mobile/fenix/issues/17080

### PR DESCRIPTION
**Pull request by rocketsroger**
### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Review by pocmo — APPROVED** [review]
Technically this looks good.

CC @eeejay - who may know better whether this has any drawbacks.

**Comment by eeejay** [comment]
I don't have a working dev setup for this. The fix looks right. I am assuming you have verified this with manual testing that TalkBack still says "loading" when needed?

**Comment by rocketsroger** [comment]
> I don't have a working dev setup for this. The fix looks right. I am assuming you have verified this with manual testing that TalkBack still says "loading" when needed?

Yes, I've tested the normal case of loading a site.  Talkback still stays "loading" when needed.  Thanks!

**Comment by rocketsroger** [comment]
Refreshing my query I can see that after moving to IO thread we are not getting a little under 30% of null pings.  It's still better than the original 75-80% but there's definitely a race here.

**Pull request merged**
