### PR TITLE
Issue #12939: Address all ktlint issues

### LINKED ISSUE #12939: Address all ktlint issues
After updating ktlint, we simply added all the existing ktlint issues with the new rules into the ktlint-baseline. Since changing any files with ktlint issues in the baseline will quickly invalidate the baseline, we are making a single mass ktlint formatting change to address all the issues and adding it to the `.git-ignore-blame-revs` afterward to not affect our git blame history.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21809)

### PR DESCRIPTION
**Pull request by gabrielluong**
### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/main/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/main/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### GitHub Automation
Fixes #12939

### CODE REVIEW

**Comment by gabrielluong** [comment]
I will add a `.git-blame-ignore-revs` in a separate PR after this land because the commit hash might change due to rebasing from mergify

**Comment by jonalmeida** [comment]
Were there any manual changes made or was it all automatically applied from the formatter ?

Also, please add some content to the linked issue on why we're doing this. It'll make future debugging easier to know if there is context.

**Comment by gabrielluong** [comment]
> Were there any manual changes made or was it all automatically applied from the formatter ?
> 
> Also, please add some content to the linked issue on why we're doing this. It'll make future debugging easier to know if there is context.

This is all done by running `ktlint -F`

**Comment by gabrielluong** [comment]
Looks like we will need to divide this up since mergify isn't happy >1000 files in a PR.

**Comment by Mugurell** [comment]
> Looks like we will need to divide this up since mergify isn't happy >1000 files in a PR.

I'd imagine splitting the patch might be a bit tedious.
We could get someone with superpowers to merge this instead of using mergify. If so then this could also contain the `.git-blame-ignore-revs` addition.

**Comment by rocketsroger** [comment]
I'm assuming we're landing this on Monday?

**Comment by gabrielluong** [comment]
> I'm assuming we're landing this on Monday?

Ya, definitely after the cut at this point.

**Comment by csadilek** [comment]
> We could get someone with superpowers to merge this instead of using mergify. If so then this could also contain the .git-blame-ignore-revs addition.

Happy to merge this when you're ready so you don't have to break it up.

**Comment by jonalmeida** [comment]
With the branch cut, could we land this soon?

**Review by rocketsroger — APPROVED** [review]
Looks good.  Did spot checks by scrolling randomly down the change and only see formatting and trailing comma changes.  🚢

**Review by csadilek — APPROVED** [review]

**Pull request merged**
