### PR TITLE
docs: Update jekyll and dependencies.

### PR DESCRIPTION
**Pull request by pocmo**

### CODE REVIEW

**Comment by Amejia481** [comment]
It looks like `feature-pwa:jacocoDebug` task is falling

```
Task :feature-pwa:jacocoDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':feature-pwa:jacocoDebug'.
> There was a failure while executing work items
   > A failure occurred while executing com.android.build.gradle.internal.tasks.JacocoTaskDelegate$JacocoWorkerAction
      > java.lang.ExceptionInInitializerError (no error message)

```

**Comment by pocmo** [comment]
Mh, that seems unrelated.

bors retry

**Comment by jonalmeida** [comment]
bors retry

(attempt 2)

**Comment by pocmo** [comment]
bors retry

**Comment by pocmo** [comment]
bors r-

Turns out this needs a codeowner review. From the error log: `waiting on code owner review from mozilla-mobile/act.`

**Comment by pocmo** [comment]
bors retry

**Comment by pocmo** [comment]
@Amejia481 Can you approve? :)

**Comment by Amejia481** [comment]
Sure!

**Pull request merged**
