### PR TITLE
For 11040 - Distinct suggestions from CombinedHistorySuggestionProvider

### PR DESCRIPTION
**Pull request by Mugurell**
### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/main/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/main/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Review by csadilek — APPROVED** [review]

**Comment by Mugurell** [comment]
```
> Could not resolve org.mozilla.geckoview:geckoview-nightly-omni:94.0.20210928095433.
  Required by:
      project :samples-browser > project :browser-engine-gecko
   > Module 'org.mozilla.geckoview:geckoview-nightly-omni' has been rejected:
        Cannot select module with conflict on capability 'org.mozilla.telemetry:glean-native:41.1.0' also provided by [org.mozilla.telemetry:glean-native:40.1.0(runtime)]
> Could not resolve org.mozilla.telemetry:glean-native:40.1.0.
  Required by:
      project :samples-browser > project :service-glean > org.mozilla.telemetry:glean:40.1.0
   > Module 'org.mozilla.telemetry:glean-native' has been rejected:
        Cannot select module with conflict on capability 'org.mozilla.telemetry:glean-native:40.1.0' also provided by [org.mozilla.geckoview:geckoview-nightly-omni:94.0.20210928095433(withGeckoBinariesDebugRuntimePublication)]
 
```

Restarting CI.

**Comment by Mugurell** [comment]
The CI failure seem related to the last update to GV 94.0.20210928095433

**Comment by csadilek** [comment]
Let's see if https://github.com/mozilla-mobile/android-components/pull/11045 fixes this.

**Comment by csadilek** [comment]
ok reverting GV upgrade in https://github.com/mozilla-mobile/android-components/pull/11047 for now.

**Pull request merged**
