### PR TITLE
For fenix#17816: add Action.IMPLEMENTATION_DETAIL & emit for profiler markers

### PR DESCRIPTION
**Pull request by mcomella**
See the commit summaries for extra details.

I wasn't sure if we wanted to add Action.IMPLEMENTATION_DETAIL to the changelog since it's more of a fenix implementation detail but I could do that if desired. :)

I haven't posted the fenix PR yet but I have a working local prototype. The Processor bascially looks like this:
```
    override fun process(fact: Fact) {
        if (fact.action != Action.IMPLEMENTATION_DETAIL) {
            return
        }

        // explain no early return
        val profiler = profilerProvider()
        val markerName = fact.item

        // explain why main thread thing
        if (Looper.myLooper() == mainHandler.looper) {
            profiler?.addMarker(markerName)
        } else {
            val markerTime = profiler?.getProfilerTime()
            mainHandler.post {
                // why start end the same?
                profiler?.addMarker(markerName, markerTime, markerTime, null)
            }
        }
    }
```

I need to add more comments.

### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Review by pocmo — APPROVED** [review]
👍 Let's try this approach.

Just note that we are very far with refactoring `SessionManager` away, so hopefully soon you may not see those facts anymore... :)

**Comment by mcomella** [comment]
@pocmo My PR build failed via mergify. It looks like there was a test failure in a component I didn't touch. Is there anything I need to do to resolve this or will mergify take care of it?

**Comment by mcomella** [comment]
Amejia481 mentioned this is a flaky test so I'll have to close/reopen or re-push.

**Comment by mcomella** [comment]
Failures seem unrelated, let's try again.

**Pull request merged**
