### PR TITLE
Fix breaking API changes in GeckoWebPushHandler.

### PR DESCRIPTION
**Pull request by jonalmeida**
---

This change is needed for the breaking API the next GV nightly build.

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- [x] **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- [x] **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Comment by Amejia481** [comment]
Let's make TC happy! :)

```
[task 2020-02-12T20:33:36.252Z] > Task :browser-engine-gecko-nightly:compileDebugKotlin FAILED
[task 2020-02-12T20:33:36.252Z] e: /builds/worker/checkouts/src/components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/webpush/GeckoWebPushHandler.kt: (29, 57): Type mismatch: inferred type is String but WebPushSubscription was expected
[task 2020-02-12T20:33:36.252Z] 
[task 2020-02-12T20:33:36.252Z] > Task :browser-engine-system:bundleLibCompileDebug
[task 2020-02-12T20:33:36.252Z] 
[task 2020-02-12T20:33:36.252Z] FAILURE: Build failed with an exception.
```

**Comment by jonalmeida** [comment]
jcenter failures, this can still be reviewed since bors re-runs everything.

```
[task 2020-02-13T15:36:31.973Z] * What went wrong:
[task 2020-02-13T15:36:31.973Z] Could not determine the dependencies of task ':browser-awesomebar:jacocoTestReport'.
[task 2020-02-13T15:36:31.973Z] > Could not resolve all task dependencies for configuration ':browser-awesomebar:jacocoAnt'.
[task 2020-02-13T15:36:31.973Z]    > Could not resolve org.jacoco:org.jacoco.ant:0.8.5.
[task 2020-02-13T15:36:31.973Z]      Required by:
[task 2020-02-13T15:36:31.973Z]          project :browser-awesomebar
[task 2020-02-13T15:36:31.973Z]       > Could not resolve org.jacoco:org.jacoco.ant:0.8.5.
[task 2020-02-13T15:36:31.973Z]          > Could not get resource 'https://jcenter.bintray.com/org/jacoco/org.jacoco.ant/0.8.5/org.jacoco.ant-0.8.5.pom'.
[task 2020-02-13T15:36:31.973Z]             > Could not GET 'https://jcenter.bintray.com/org/jacoco/org.jacoco.ant/0.8.5/org.jacoco.ant-0.8.5.pom'. Received status code 502 from server: Bad Gateway
[task 2020-02-13T15:36:31.973Z] 
```

**Comment by jonalmeida** [comment]
Looks like we're getting test failures from nightly with this new build that seem unrelated to the breaking API changes in this PR.

```
java.lang.NullPointerException
	at org.mozilla.geckoview.GeckoSession.open(GeckoSession.java:1436)
	at mozilla.components.browser.engine.gecko.GeckoEngineSession.createGeckoSession(GeckoEngineSession.kt:840)
	at mozilla.components.browser.engine.gecko.GeckoEngineSession.<init>(GeckoEngineSession.kt:97)
	at mozilla.components.browser.engine.gecko.GeckoEngineSession.<init>(GeckoEngineSession.kt:62)
	at mozilla.components.browser.engine.gecko.prompt.GeckoPromptDelegateTest.Calling onAuthPrompt must provide an Authentication PromptRequest(GeckoPromptDelegateTest.kt:606)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:601)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:260)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:130)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:42)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:84)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at androidx.test.ext.junit.runners.AndroidJUnit4.run(AndroidJUnit4.java:104)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
```

**Comment by csadilek** [comment]
Closing to put up a new version adressing the test failures.

**Pull request closed without merging**
