### PR TITLE
Update to Glean v34.0.0

### PR DESCRIPTION
**Pull request by badboy**
### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Review by travis79 — APPROVED** [review]

**Comment by badboy** [comment]
```
Errors found:

/builds/worker/checkouts/src/samples/sync/src/main/res/layout/activity_main.xml:133: Error: Replace the <fragment> tag with FragmentContainerView. [FragmentTagUsage]
            <fragment android:name="org.mozilla.samples.sync.DeviceFragment"
             ~~~~~~~~
```

That's not our code. Did we accidentally upgrade some dependency again or did something else go wrong?
@pocmo, are you able to help here?

**Review by jonalmeida — APPROVED** [review]
Rubber stamping ✅

**Comment by jonalmeida** [comment]
toolchain task is still failing with the same error as before:

```
[task 2021-02-10T10:24:34.664Z]   /builds/worker/checkouts/src/samples/sync/src/main/res/layout/activity_main.xml:133: Error: Replace the <fragment> tag with FragmentContainerView. [FragmentTagUsage]
[task 2021-02-10T10:24:34.664Z]               <fragment android:name="org.mozilla.samples.sync.DeviceFragment"
[task 2021-02-10T10:24:34.664Z]                ~~~~~~~~
```

**Comment by badboy** [comment]
> toolchain task is still failing with the same error as before:
> 
> ```
> [task 2021-02-10T10:24:34.664Z]   /builds/worker/checkouts/src/samples/sync/src/main/res/layout/activity_main.xml:133: Error: Replace the <fragment> tag with FragmentContainerView. [FragmentTagUsage]
> [task 2021-02-10T10:24:34.664Z]               <fragment android:name="org.mozilla.samples.sync.DeviceFragment"
> [task 2021-02-10T10:24:34.664Z]                ~~~~~~~~
> ```

But ... that's not our code.

...


Wait, didn't we had that before because we accidentally triggered some dependency upgrades? Grrr, guess I need to look into that.

**Comment by pocmo** [comment]
Yeah, that is likely. If you run `./gradlew samples-sync:dependencies` and search for glean then you may see what transitive dependencies it comes with and which may have caused an upgrade.

**Comment by mdboom** [comment]
It looks like a-c upgraded `androidx.lifecycle` from 2.1.0 to 2.2.0, and Glean upgraded `androidx.lifecycle-extensions` from 2.1.0 to 2.2.0 to match.  This forces an upgrade of `androidx.fragment` from 1.1.0 to 1.2.0, which introduces this deprecated.  I don't think this is resolvable other than (a) rolling back `androidx.lifecycle*` to 2.1.0 or (b) trying to update to the new `fragment` usage [following these instructions in the CHANGELOG](https://developer.android.com/jetpack/androidx/releases/fragment#1.2.0)

**Comment by mdboom** [comment]
> b) trying to update to the new `fragment` usage [following these instructions in the CHANGELOG](https://developer.android.com/jetpack/androidx/releases/fragment#1.2.0)

This works for me -- see https://github.com/badboy/android-components/pull/1

**Comment by badboy** [comment]
```
[task 2021-02-10T16:33:36.785Z] Execution failed for task ':browser-engine-gecko-nightly:packageDebugAndroidTest'.
[task 2021-02-10T16:33:36.785Z] > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
[task 2021-02-10T16:33:36.785Z]    > java.lang.OutOfMemoryError (no error message)
```


Uhm ....

**Comment by jonalmeida** [comment]
This looks like a random CI event. Let's restart the build.

**Pull request merged**
