### PR TITLE
For #10871 - Remove permissions matching block

### PR DESCRIPTION
**Pull request by Mugurell**
We'll rely on the hosts declared in content_scripts[*].matches to control on
which hosts these extensions will work and only on these will they get the
declared permissions.

The extensions should otherwise function exactly as before.

### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/main/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/main/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Review by csadilek — APPROVED** [review]
@Mugurell 👍 Can you trigger an uplift with mergify to A-C 92 when this lands? Thanks!

**Comment by Mugurell** [comment]
`build-samples-browser-gecko` failed because of 
```
Plugin [id: 'com.jetbrains.python.envs', version: '0.0.26'] was not found in any of the following sources:
```

Restarting CI.

**Comment by Mugurell** [comment]
@Mergifyio backport releases/92.0

**Comment by mcomella** [comment]
I cherry-picked the commit from this PR 4b2eaa3e003e1c2f780e3f45b7e85a6c2b022c4c on top of the commit from 7/20 that I was measuring the regression on 5630e1f65cb681fc33800e71aa7ba87a43c00922:
- before this commit (results from yesterday): 2748ms
- after this commit: 2589ms
- after this commit + clear data (i.e. not using data from yesterday): 2403ms. https://share.firefox.dev/3zfprmG

In both cases, the regression appears to be fixed. Note: I only ran 5 replicates for each test (I usually run 25) so these results aren't _super_ stable but given the large difference in performance before and after, I think we can say the regression is addressed locally. Perhaps doing only 5 replicates is why the results are so different with this commit before and after clearing data.

**Comment by csadilek** [comment]
@Mergifyio backport releases/92.0

**Pull request merged**
