### PR TITLE
For #7265 Add @WorkerThread to functions on SitePermissionStorage which needs to work in background thread

### LINKED ISSUE #7265: Make noticiable that operations on SitePermissionsStorage must be performed on a background thread

### PR DESCRIPTION
**Pull request by RotBolt**
Closes #7265 

### Pull Request checklist

- [X] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [X] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/main/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/main/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Comment by RotBolt** [comment]
cc @Amejia481 could give a review?
This one is a small PR

**Comment by Amejia481** [comment]
> hi @Amejia481 I am not able to see why TaskCluster is failing some builds I ran these o local with `./gradlew assembleDebug` and it built fine
> 
> Could you help me to the stacktrace on TaskCluster CI ?

It looks like there was an issue with the glean dependencies, it's already [fixed](https://github.com/mozilla-mobile/android-components/issues/11714#issuecomment-1038857921) If think, if close/re-open the PR should be enough.

**Comment by RotBolt** [comment]
Ok great. I see all the tests are passing now

**Comment by RotBolt** [comment]
@Amejia481 @csadilek could you folks review this PR again ? 
It's a small PR

**Comment by Amejia481** [comment]
Thanks for the PR @RotBolt. 

Initially when I filed https://github.com/mozilla-mobile/android-components/issues/7265 [SitePermissionsStorage](https://github.com/mozilla-mobile/android-components/blob/cfc360e0587ccb7eb49689d08212f05ff0966fbb/components/feature/sitepermissions/src/main/java/mozilla/components/feature/sitepermissions/SitePermissionsStorage.kt#L33) was completely different, back then, there wasn't a clear way to know that the operations could happen in another thread, as we updated it to use the co-routine APIs we have moved to adding the `suspend` keyword to the operations, that implies that the operations could happen in a different thread, I think it's enough for the initial intention, I think we won't need to at `@WorkerThread`.  Sorry for the misunderstanding, I'll close this for now, but please feel free to re-open if you feel we really need to add this.

**Comment by RotBolt** [comment]
Umm just a wild thought even with coroutines a person just launch a coroutine without using any dispatcher 

In this case they could use Main dispatcher as well. 

Something to look into 

WDYT ? @Amejia481

**Comment by Amejia481** [comment]
> Umm just a wild thought even with coroutines a person just launch a coroutine without using any dispatcher
> 
> In this case they could use Main dispatcher as well.
> 
> Something to look into
> 
> WDYT ? @Amejia481

Yes, that it's correct. 

The `@WorkerThread` annotation was created before coroutines,  and with it give consumers of a function a hint on which thread   it should be execute,  with the `suspend` keyword we are giving the same hints, one example of the same pattern is the Room [APIs with coroutines](https://medium.com/androiddevelopers/room-coroutines-422b786dc4c5), most of the database operations should be performed on background thread or you will get runtime exception, the room API only rely on the `suspend` keyword to indicate that. In my opinion, the `suspend` keyword should be enough for covering the initial idea of the bug, mixing the `@WorkerThread` annotation with the `suspend` keyword feels a bit strange as they are different APIs that I think were not meant to be used together.

**Pull request closed without merging**
