### PR TITLE
Handle breaking changes from a-s 83.0.0

### PR DESCRIPTION
**Pull request by bendk**
### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/main/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/main/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Comment by jonalmeida** [comment]
bors try

**Review by grigoryk — APPROVED** [review]
Changes look good to me; if we can't land this today, let's wait until Monday.

**Comment by jonalmeida** [comment]
> Changes look good to me; if we can't land this today, let's wait until Monday.

👍 

Elise and I are going to pair on the smoke test and if we're done soon we can land this and kick off an a-c build after as well so we have the entire next day to verify in Fenix.

**Comment by grigoryk** [comment]
Linter failure:
```
[task 2021-09-09T18:19:20.300Z] > Task :ktlint
[task 2021-09-09T18:19:20.301Z] /builds/worker/checkouts/src/components/service/firefox-accounts/src/test/java/mozilla/components/service/fxa/FxaDeviceConstellationTest.kt:7:1: Imports must be ordered in lexicographic order without any empty lines in-between with "java", "javax", "kotlin" and aliases in the end
[task 2021-09-09T18:19:20.499Z] /builds/worker/checkouts/src/components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/FxaDeviceConstellation.kt:7:1: Imports must be ordered in lexicographic order without any empty lines in-between with "java", "javax", "kotlin" and aliases in the end
```

**Comment by grigoryk** [comment]
Another issue, more interesting:
```
[task 2021-09-09T20:00:04.012Z] > Task :service-firefox-accounts:compileReleaseUnitTestKotlin FAILED
[task 2021-09-09T20:00:04.012Z] e: /builds/worker/checkouts/src/components/service/firefox-accounts/src/test/java/mozilla/components/service/fxa/FxaAccountManagerTest.kt: (797, 29): Cannot access '<init>': it is protected in 'FxaException'
[task 2021-09-09T20:00:04.012Z] e: /builds/worker/checkouts/src/components/service/firefox-accounts/src/test/java/mozilla/components/service/fxa/FxaAccountManagerTest.kt: (797, 29): Sealed types cannot be instantiated
```

**Review by jonalmeida — APPROVED** [review]
Elise and I ran through the [smoke test list](https://mozac.org/contributing/app-services-upgrades) and verified everything still works in Fenix. Let's land this!

**Comment by eliserichards** [comment]
Fenix PR: https://github.com/mozilla-mobile/fenix/pull/21215

**Pull request merged**
