### PR TITLE
Closes #5644: Update MigrationStore from FennecMigrator after every migration step.

### LINKED ISSUE #5644: FennecMigrator/MigrationStore: Report state after every step.
Currently `FennecMigrator` sets the state of the migration in `MigrationStore` after everything has completed. However to show an ongoing state in the UI we should update the store after every step.

### PR DESCRIPTION
**Pull request by pocmo**
This should fix some of the UI issues that have been filed. I tested this in a Fenix build and now:
* "Settings" is part of the list.
* Items appeared one after the other after they are completed.

### CODE REVIEW

**Comment by pocmo** [comment]
This will need a small change in Fenix once it lands in a snapshot (We need to pass a `MigrationStore` instance to `FennecMIgrator`).

**Comment by jonalmeida** [comment]
bors=me

**Comment by pocmo** [comment]
> bors=me

You need coffee. :D

**Comment by jonalmeida** [comment]
bors=jonalmeida

> > bors=me
> 
> You need coffee. :D

Why does this not work!?

**Comment by pocmo** [comment]
> bors=jonalmeida
> 
> > > bors=me
> > 
> > 
> > You need coffee. :D
> 
> Why does this not work!?

First of all you only need `bors r+`. Second, if you want to specify a name then it's `bors r=jonalmeida` :)

**Comment by pocmo** [comment]
Merging manually because `bors` is wobbly right now.

**Pull request merged**
