### PR TITLE
Refactor packages from mozilla => org.mozilla

### PR DESCRIPTION
**Pull request by csadilek**
Just a package refactoring: mozilla => org.mozilla, it's easier to fix now than later.

If intentional, we can just close the PR :).

### CODE REVIEW

**Comment by csadilek** [comment]
Ah, now that ErrorPages is in a Java src folder, detekt found some issues. Fixing.

**Comment by pocmo** [comment]
> If intentional, we can just close the PR :).

So far this was intentional. I saw a bunch of popular libraries drop their prefixes (e.g. Square's okhttp). Here I thought there's really no additional value coming from the "org" prefix. It's not like we distinguish between "de.mozilla" or "org.mozilla". And "mozilla" is pretty unique already. What do you think?

**Comment by csadilek** [comment]
Interesting. I wasn't aware people started doing that, but shorter is definitely better, I agree. The only concern is that we'd have a mix of org.mozilla and mozilla in focus and fennec when we start using these components. If that's OK we can close this PR.

I can send a follow-up though to put ErrorPages into a Java package and fix the detekt warning.

**Comment by pocmo** [comment]
> The only concern is that we'd have a mix of org.mozilla and mozilla in focus and fennec when we start using these components.

Mh. That's true. I wonder whether it would be helpful to see the difference between app code and library code in the imports? I'd keep "org" in app code as it matches the app package name that will still need the prefix.

> I can send a follow-up though to put ErrorPages into a Java package and fix the detekt warning.

I had to fix that to get PR #18 green too :-)

**Comment by csadilek** [comment]
OK, great. Let's close this one then.

**Pull request closed without merging**
