### PR TITLE
Lazily register ktlintFormat task

### PR DESCRIPTION
**Pull request by grigoryk**
### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/main/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/main/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Comment by grigoryk** [comment]
```
....
[task 2021-09-09T20:10:33.338Z] > Task :support-base:lintAnalyzeRelease
[task 2021-09-09T20:10:33.338Z] mozilla.components.tooling.lint.LintIssueRegistry in /builds/worker/checkouts/src/components/tooling/lint/build/libs/tooling-lint.jar does not specify a vendor; see IssueRegistry#vendor
[task 2021-09-09T20:10:50.638Z] 
[task 2021-09-09T20:10:50.638Z] > Task :support-base:lintRelease
[task 2021-09-09T20:10:50.738Z] 
[task 2021-09-09T20:10:50.738Z] BUILD SUCCESSFUL in 2m 57s
[task 2021-09-09T20:10:50.738Z] 191 actionable tasks: 142 executed, 49 from cache
[fetches 2021-09-09T20:10:51.066Z] removing /builds/worker/fetches
[fetches 2021-09-09T20:10:51.563Z] finished
[taskcluster 2021-09-09 20:10:51.926Z] === Task Finished ===
[taskcluster:error] Error uploading "public/reports/jacoco/jacocoReleaseTestReport/html/mozilla.components.support.base.log/index.source.html" artifact. Artifact already exists with different properties, and none of the allowed exceptions apply: {
  "storageType": "s3",
  "contentType": "text/html",
  "expires": "2021-10-07T19:33:15.848Z"
}
---
* method:     createArtifact
* errorCode:  RequestConflict
* statusCode: 409
* time:       2021-09-09T20:11:28.463Z
[taskcluster:error] Error: Error calling 'stopped' for artifactHandler : Error: Encountered error when uploading artifact(s)
    at Artifacts.stopped (/home/ubuntu/docker-worker/src/lib/features/artifacts.js:218:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)
    at Task.run (/home/ubuntu/docker-worker/src/lib/task.js:973:7)
    at Task.start (/home/ubuntu/docker-worker/src/lib/task.js:700:17)
    at TaskListener.runTaskset (/home/ubuntu/docker-worker/src/lib/task_listener.js:524:9)
    at async Promise.all (index 0)
[taskcluster 2021-09-09 20:11:51.804Z] Unsuccessful task run with exit code: -1 completed in 276.733 seconds
```

**Comment by jonalmeida** [comment]
```
[task 2021-09-09T21:10:58.205Z] * What went wrong:
[task 2021-09-09T21:10:58.206Z] A problem occurred configuring project ':buildSrc'.
[task 2021-09-09T21:10:58.207Z] > Could not resolve all artifacts for configuration ':buildSrc:classpath'.
[task 2021-09-09T21:10:58.208Z]    > Could not download kotlin-compiler-embeddable-1.4.31.jar (org.jetbrains.kotlin:kotlin-compiler-embeddable:1.4.31)
[task 2021-09-09T21:10:58.209Z]       > Could not get resource 'https://plugins.gradle.org/m2/org/jetbrains/kotlin/kotlin-compiler-embeddable/1.4.31/kotlin-compiler-embeddable-1.4.31.jar'.
[task 2021-09-09T21:10:58.209Z]          > Premature end of Content-Length delimited message body (expected: 46,699,904; received: 42,729,152)
[task 2021-09-09T21:10:58.210Z] 
```

**Comment by grigoryk** [comment]
... and now an intermittent (i think..?):
```
[task 2021-09-10T02:04:32.745Z]   TEST: BrowserAwesomeBar forwards input to providers
[task 2021-09-10T02:04:32.745Z]     [Robolectric] mozilla.components.browser.awesomebar.BrowserAwesomeBarTest.BrowserAwesomeBar forwards input to providers: sdk=28; resources=binary
[task 2021-09-10T02:04:32.745Z]     I/MonitoringInstr: Instrumentation started!
[task 2021-09-10T02:04:32.842Z]   FAILURE
[task 2021-09-10T02:04:32.843Z] 
[task 2021-09-10T02:04:32.843Z] java.lang.AssertionError: expected:<4> but was:<3>
[task 2021-09-10T02:04:32.843Z] 	at org.junit.Assert.fail(Assert.java:88)
[task 2021-09-10T02:04:32.843Z] 	at org.junit.Assert.failNotEquals(Assert.java:834)
[task 2021-09-10T02:04:32.843Z] 	at org.junit.Assert.assertEquals(Assert.java:118)
[task 2021-09-10T02:04:32.843Z] 	at org.junit.Assert.assertEquals(Assert.java:144)
[task 2021-09-10T02:04:32.843Z] 	at mozilla.components.browser.awesomebar.BrowserAwesomeBarTest$BrowserAwesomeBar forwards input to providers$1.invokeSuspend(BrowserAwesomeBarTest.kt:80)
```

**Comment by jonalmeida** [comment]
> ... and now an intermittent (i think..?):

Yeah, it was. It was filed [here](https://github.com/mozilla-mobile/android-components/issues/10713).

The new `feature-containers` [failures](https://firefox-ci-tc.services.mozilla.com/tasks/ACQ3Xv_hRKy-c03QXhsQeg/runs/0/logs/public/logs/live.log) is another network error.

This failure looks similar to something we were seeing with [another CI build for Focus](https://firefox-ci-tc.services.mozilla.com/tasks/DzVBYDtbR9SUBOmKJF18wA/runs/0/logs/public/logs/live.log#L323) earlier today, so it's an intermittent but I don't know what to do next except waiting and retrying again later. 😄

**Review by jonalmeida — APPROVED** [review]

**Pull request merged**
