### PR TITLE
Upgrade Glean to 42.2.0

### PR DESCRIPTION
**Pull request by wlach**
Needed for mozilla-mobile/fenix#22954

### CODE REVIEW

**Comment by wlach** [comment]
Link to changelog: https://github.com/mozilla/glean/blob/main/CHANGELOG.md#v4232-2021-12-15

It doesn't appear there are any major changes since the previous upgrade.

**Review by csadilek — COMMENTED** [review]
@badboy should we be on 42.3.0 already? Looks like that's what's used in m-c/geckoview.

(Looking forward to https://github.com/mozilla-mobile/relbot/pull/67 which will be ⭐ )

**Comment by badboy** [comment]
gnah, yes. Let me send a PR.

@csadilek who can take care of relbot#67? I updated it the other day (I should make sure it actually still does the right thing)

**Comment by csadilek** [comment]
Thanks, @badboy. Will get back to you about the relbot PR.

**Pull request merged**
