### PR TITLE
A-S 0.58.1 update; Support for v34 (history) and v23 (bookmarks) fennec db migrations.

### PR DESCRIPTION
**Pull request by grigoryk**
Requires the just-published A-S 0.55.1 dot release. https://github.com/mozilla/application-services/releases/tag/v0.55.1

---

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Comment by pocmo** [comment]
@grigoryk I cherry-picked this onto the release branch. On master this seems to conflict with an update to `0.57.0` that seems to have happened in parallel.

**Comment by grigoryk** [comment]
> @grigoryk I cherry-picked this onto the release branch. On master this seems to conflict with an update to `0.57.0` that seems to have happened in parallel.

We'll need to wait until there's a 0.57.* (or greater) A-S release which includes necessary changes; so far they've just been released off of the 0.55 branch.

**Comment by eoger** [comment]
Heads up Application Services v0.58.0 is out

**Comment by grigoryk** [comment]
@eoger thanks for the heads up! Update this PR to include the A-S version bump to 0.58.0.

@pocmo I'll smoke test this A-S update locally in Fenix to see if it passes a sanity check.

**Comment by grigoryk** [comment]
@eoger @vladikoff Seeing problems with the 0.58.0 a-s version in local builds. Specifically, networking seems busted?

When trying to sign-in (in this case via pairing, but i get the same results via email flow as well):
```
04-23 15:37:47.745 15466 15524 E viaduct::backend::ffi: Viaduct Ffi Error: doFetch failed: null
04-23 15:37:47.746 15466 15524 E viaduct::backend::ffi: Missing HTTP status
04-23 15:37:47.746 15466 15524 W fxa_client::ffi: Network error: Error(
04-23 15:37:47.746 15466 15524 W fxa_client::ffi:
04-23 15:37:47.746 15466 15524 W fxa_client::ffi: Network error: Backend error: Missing HTTP status)
04-23 15:37:47.746 15466 15524 E FirefoxAccount: Error while running: complete oauth flow
04-23 15:37:47.746 15466 15524 E FirefoxAccount: mozilla.appservices.fxaclient.FxaException$Network: Network error: Backend error: Missing HTTP status
04-23 15:37:47.746 15466 15524 E FirefoxAccount: 	at mozilla.appservices.fxaclient.rust.RustError.intoException(RustError.kt:43)
04-23 15:37:47.746 15466 15524 E FirefoxAccount: 	at mozilla.appservices.fxaclient.FirefoxAccount.completeOAuthFlow(FirefoxAccount.kt:687)
04-23 15:37:47.746 15466 15524 E FirefoxAccount: 	at mozilla.components.service.fxa.FirefoxAccount$completeOAuthFlowAsync$1$1.invoke(FirefoxAccount.kt:196)
04-23 15:37:47.746 15466 15524 E FirefoxAccount: 	at mozilla.components.service.fxa.FirefoxAccount$completeOAuthFlowAsync$1$1.invoke(FirefoxAccount.kt:29)
04-23 15:37:47.746 15466 15524 E FirefoxAccount: 	at mozilla.components.service.fxa.UtilsKt$handleFxaExceptions$7.invokeSuspend(Utils.kt:68)
04-23 15:37:47.746 15466 15524 E FirefoxAccount: 	at mozilla.components.service.fxa.UtilsKt$handleFxaExceptions$7.invoke(Unknown Source:10)
04-23 15:37:47.746 15466 15524 E FirefoxAccount: 	at mozilla.components.service.fxa.UtilsKt.handleFxaExceptions(Utils.kt:28)
04-23 15:37:47.746 15466 15524 E FirefoxAccount: 	at mozilla.components.service.fxa.UtilsKt.handleFxaExceptions(Utils.kt:60)
04-23 15:37:47.746 15466 15524 E FirefoxAccount: 	at mozilla.components.service.fxa.UtilsKt.handleFxaExceptions(Utils.kt:67)
04-23 15:37:47.746 15466 15524 E FirefoxAccount: 	at mozilla.components.service.fxa.FirefoxAccount$completeOAuthFlowAsync$1.invokeSuspend(FirefoxAccount.kt:195)
04-23 15:37:47.746 15466 15524 E FirefoxAccount: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
04-23 15:37:47.746 15466 15524 E FirefoxAccount: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
04-23 15:37:47.746 15466 15524 E FirefoxAccount: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
04-23 15:37:47.746 15466 15524 E FirefoxAccount: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
04-23 15:37:47.746 15466 15524 E FirefoxAccount: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
04-23 15:37:47.746 15466 15524 E FirefoxAccount: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

And when already signed-in, hitting similar errors at some points when fxaclient needs to access its servers. Devices are online.

So, Sync and FxA appear busted.

I'm also seeing other problems. `UnsupportedOperationException` protobuf thing is still there. This happens anytime storage is accessed (places, logins). For example:
```
04-23 15:47:42.998 16447 17213 D logins_ffi: sync15_passwords_get_by_base_domain
04-23 15:47:43.036 16447 16492 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-3
04-23 15:47:43.036 16447 16492 E AndroidRuntime: Process: org.mozilla.fenix.debug, PID: 16447
04-23 15:47:43.036 16447 16492 E AndroidRuntime: java.lang.UnsupportedOperationException
04-23 15:47:43.036 16447 16492 E AndroidRuntime: 	at com.google.protobuf.UnsafeUtil$Android64MemoryAccessor.getByte(UnsafeUtil.java:716)
04-23 15:47:43.036 16447 16492 E AndroidRuntime: 	at com.google.protobuf.UnsafeUtil.getByte(UnsafeUtil.java:255)
04-23 15:47:43.036 16447 16492 E AndroidRuntime: 	at com.google.protobuf.CodedInputStream$UnsafeDirectNioDecoder.readRawVarint32(CodedInputStream.java:1719)
04-23 15:47:43.036 16447 16492 E AndroidRuntime: 	at com.google.protobuf.CodedInputStream$UnsafeDirectNioDecoder.readTag(CodedInputStream.java:1337)
04-23 15:47:43.036 16447 16492 E AndroidRuntime: 	at com.google.protobuf.CodedInputStreamReader.getFieldNumber(CodedInputStreamReader.java:81)
04-23 15:47:43.036 16447 16492 E AndroidRuntime: 	at com.google.protobuf.MessageSchema.mergeFromHelper(MessageSchema.java:3862)
04-23 15:47:43.036 16447 16492 E AndroidRuntime: 	at com.google.protobuf.MessageSchema.mergeFrom(MessageSchema.java:3844)
04-23 15:47:43.036 16447 16492 E AndroidRuntime: 	at com.google.protobuf.GeneratedMessageLite.parsePartialFrom(GeneratedMessageLite.java:1532)
04-23 15:47:43.036 16447 16492 E AndroidRuntime: 	at com.google.protobuf.GeneratedMessageLite.parseFrom(GeneratedMessageLite.java:1695)
04-23 15:47:43.036 16447 16492 E AndroidRuntime: 	at com.google.protobuf.GeneratedMessageLite.parseFrom(GeneratedMessageLite.java:1688)
04-23 15:47:43.036 16447 16492 E AndroidRuntime: 	at mozilla.appservices.logins.MsgTypes$PasswordInfos.parseFrom(MsgTypes.java:1752)
04-23 15:47:43.036 16447 16492 E AndroidRuntime: 	at mozilla.appservices.logins.DatabaseLoginsStorage.getByBaseDomain(DatabaseLoginsStorage.kt:230)
04-23 15:47:43.036 16447 16492 E AndroidRuntime: 	at mozilla.components.service.sync.logins.SyncableLoginsStorage$getByBaseDomain$2.invokeSuspend(SyncableLoginsStorage.kt:253)
04-23 15:47:43.036 16447 16492 E AndroidRuntime: 	at mozilla.components.service.sync.logins.SyncableLoginsStorage$getByBaseDomain$2.invoke(Unknown Source:10)
04-23 15:47:43.036 16447 16492 E AndroidRuntime: 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
04-23 15:47:43.036 16447 16492 E AndroidRuntime: 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:154)
04-23 15:47:43.036 16447 16492 E AndroidRuntime: 	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
04-23 15:47:43.036 16447 16492 E AndroidRuntime: 	at mozilla.components.service.sync.logins.SyncableLoginsStorage.getByBaseDomain(SyncableLoginsStorage.kt:252)
04-23 15:47:43.036 16447 16492 E AndroidRuntime: 	at mozilla.components.service.sync.logins.GeckoLoginStorageDelegate$onLoginFetch$1.invokeSuspend(GeckoLoginStorageDelegate.kt:66)
04-23 15:47:43.036 16447 16492 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
04-23 15:47:43.036 16447 16492 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
04-23 15:47:43.036 16447 16492 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
04-23 15:47:43.036 16447 16492 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
04-23 15:47:43.036 16447 16492 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
04-23 15:47:43.036 16447 16492 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
04-23 15:47:43.036 16447 16492 I Process : Sending signal. PID: 16447 SIG: 9
```

**Comment by rfk** [comment]
For completeness, I wanted to check whether the pre-release QA tasks in the checklist [here](https://github.com/mozilla/application-services/blob/master/docs/howtos/cut-a-new-release.md#make-a-new-release-from-latest-master) could or should have caught this.  Running the various `smoke-test-*` scripts doesn't trigger the error, and neither does just compiling and running the sync sample app. But attempting to sign in to the sample app does reveal the error immediately on my machine.

**Comment by grigoryk** [comment]
@rfk wording of that checklist highlights that there's an inherent assumption of soundness - that is, checklist assumes that tests are exhaustive enough, and that if application code compiles then things are good (e.g. breaking changes are the main concern). Putting aside for a minute what to do _in case_ there are breaking changes - they need to be integrated by consuming teams...

```
 - Build and run the sync sample app in android-components against your local checkout using the local publishing flow.

If these tests fail, it indicates a breaking change. Check that such a change is called out in the changelog, and file downstream bugs to track the work of integrating it.
```

My approach usually is to assume that the release isn't sound, and to prove it to myself otherwise. As you noted, actually trying to use the `samples-sync` app to sign-in and sync instantly highlights the error. Further, we're querying the storage in the app - so, even if the network problem was absent, I'd expect it will hit the `UnsupportedOperationException` exception after syncing.

So we should _at least_ change the checklist to require running through the few buttons `samples-sync` provides to exercise the code. Given that Fenix-against-A-S builds are now easier to obtain, I'd consider adding that to the checklist as well (and actually trying things out in the app).

In a perfect world integration tests would catch problems like this, minimize manual steps and backtracking...

**Comment by grigoryk** [comment]
Investigating why our own tests didn't catch these failures - they're all green, and pass locally. What I think is happening is that a different`MemoryAccessor` implementation is used when running on device (or emulator) vs locally (or on CI).

https://github.com/protocolbuffers/protobuf/blob/master/java/core/src/main/java/com/google/protobuf/UnsafeUtil.java#L616-L625 - `JvmMemoryAccessor` has a `getByte` implementation.

... while `Android32/64MemoryAccessor` https://github.com/protocolbuffers/protobuf/blob/master/java/core/src/main/java/com/google/protobuf/UnsafeUtil.java#L708-L717 does not and throws.

**Comment by grigoryk** [comment]
In retrospect this makes sense, but https://github.com/mozilla-mobile/android-components/pull/6636#issuecomment-618772780 highlights that at least right now, we can't entirely depend on tests that don't actually run in a real or emulated android environment.

**Comment by pocmo** [comment]
> So we should at least change the checklist to require running through the few buttons samples-sync provides to exercise the code.

Just a side note: We do have the capability now to run sample apps as well as other on-device tests on Firebase device lab for all components with just a couple of lines of config. Is this something we can write a UI test for that uses the sample app? I am not sure about test credentials or similar - they would be readable by anyone?

**Comment by grigoryk** [comment]
> > So we should at least change the checklist to require running through the few buttons samples-sync provides to exercise the code.
> 
> Just a side note: We do have the capability now to run sample apps as well as other on-device tests on Firebase device lab for all components with just a couple of lines of config. Is this something we can write a UI test for that uses the sample app? I am not sure about test credentials or similar - they would be readable by anyone?

I thought about it as an option. It's not clear to me if it's worth the added costs and slower CI cycles. I guess we've wasted enough time on these issues that it does sound worth it over time...

**Comment by eoger** [comment]
> @eoger @vladikoff Seeing problems with the 0.58.0 a-s version in local builds. Specifically, networking seems busted?
> 
> When trying to sign-in (in this case via pairing, but i get the same results via email flow as well):
> 
> ```
> 04-23 15:37:47.745 15466 15524 E viaduct::backend::ffi: Viaduct Ffi Error: doFetch failed: null
> 04-23 15:37:47.746 15466 15524 E viaduct::backend::ffi: Missing HTTP status
> 04-23 15:37:47.746 15466 15524 W fxa_client::ffi: Network error: Error(
> 04-23 15:37:47.746 15466 15524 W fxa_client::ffi:
> 04-23 15:37:47.746 15466 15524 W fxa_client::ffi: Network error: Backend error: Missing HTTP status)
> 04-23 15:37:47.746 15466 15524 E FirefoxAccount: Error while running: complete oauth flow
> 04-23 15:37:47.746 15466 15524 E FirefoxAccount: mozilla.appservices.fxaclient.FxaException$Network: Network error: Backend error: Missing HTTP status
> 04-23 15:37:47.746 15466 15524 E FirefoxAccount: 	at mozilla.appservices.fxaclient.rust.RustError.intoException(RustError.kt:43)
> 04-23 15:37:47.746 15466 15524 E FirefoxAccount: 	at mozilla.appservices.fxaclient.FirefoxAccount.completeOAuthFlow(FirefoxAccount.kt:687)
> 04-23 15:37:47.746 15466 15524 E FirefoxAccount: 	at mozilla.components.service.fxa.FirefoxAccount$completeOAuthFlowAsync$1$1.invoke(FirefoxAccount.kt:196)
> 04-23 15:37:47.746 15466 15524 E FirefoxAccount: 	at mozilla.components.service.fxa.FirefoxAccount$completeOAuthFlowAsync$1$1.invoke(FirefoxAccount.kt:29)
> 04-23 15:37:47.746 15466 15524 E FirefoxAccount: 	at mozilla.components.service.fxa.UtilsKt$handleFxaExceptions$7.invokeSuspend(Utils.kt:68)
> 04-23 15:37:47.746 15466 15524 E FirefoxAccount: 	at mozilla.components.service.fxa.UtilsKt$handleFxaExceptions$7.invoke(Unknown Source:10)
> 04-23 15:37:47.746 15466 15524 E FirefoxAccount: 	at mozilla.components.service.fxa.UtilsKt.handleFxaExceptions(Utils.kt:28)
> 04-23 15:37:47.746 15466 15524 E FirefoxAccount: 	at mozilla.components.service.fxa.UtilsKt.handleFxaExceptions(Utils.kt:60)
> 04-23 15:37:47.746 15466 15524 E FirefoxAccount: 	at mozilla.components.service.fxa.UtilsKt.handleFxaExceptions(Utils.kt:67)
> 04-23 15:37:47.746 15466 15524 E FirefoxAccount: 	at mozilla.components.service.fxa.FirefoxAccount$completeOAuthFlowAsync$1.invokeSuspend(FirefoxAccount.kt:195)
> 04-23 15:37:47.746 15466 15524 E FirefoxAccount: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
> 04-23 15:37:47.746 15466 15524 E FirefoxAccount: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
> 04-23 15:37:47.746 15466 15524 E FirefoxAccount: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
> 04-23 15:37:47.746 15466 15524 E FirefoxAccount: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
> 04-23 15:37:47.746 15466 15524 E FirefoxAccount: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
> 04-23 15:37:47.746 15466 15524 E FirefoxAccount: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
> ```
> 
> And when already signed-in, hitting similar errors at some points when fxaclient needs to access its servers. Devices are online.
> 
> So, Sync and FxA appear busted.
> 
> I'm also seeing other problems. `UnsupportedOperationException` protobuf thing is still there. This happens anytime storage is accessed (places, logins). For example:
> 
> ```
> 04-23 15:47:42.998 16447 17213 D logins_ffi: sync15_passwords_get_by_base_domain
> 04-23 15:47:43.036 16447 16492 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-3
> 04-23 15:47:43.036 16447 16492 E AndroidRuntime: Process: org.mozilla.fenix.debug, PID: 16447
> 04-23 15:47:43.036 16447 16492 E AndroidRuntime: java.lang.UnsupportedOperationException
> 04-23 15:47:43.036 16447 16492 E AndroidRuntime: 	at com.google.protobuf.UnsafeUtil$Android64MemoryAccessor.getByte(UnsafeUtil.java:716)
> 04-23 15:47:43.036 16447 16492 E AndroidRuntime: 	at com.google.protobuf.UnsafeUtil.getByte(UnsafeUtil.java:255)
> 04-23 15:47:43.036 16447 16492 E AndroidRuntime: 	at com.google.protobuf.CodedInputStream$UnsafeDirectNioDecoder.readRawVarint32(CodedInputStream.java:1719)
> 04-23 15:47:43.036 16447 16492 E AndroidRuntime: 	at com.google.protobuf.CodedInputStream$UnsafeDirectNioDecoder.readTag(CodedInputStream.java:1337)
> 04-23 15:47:43.036 16447 16492 E AndroidRuntime: 	at com.google.protobuf.CodedInputStreamReader.getFieldNumber(CodedInputStreamReader.java:81)
> 04-23 15:47:43.036 16447 16492 E AndroidRuntime: 	at com.google.protobuf.MessageSchema.mergeFromHelper(MessageSchema.java:3862)
> 04-23 15:47:43.036 16447 16492 E AndroidRuntime: 	at com.google.protobuf.MessageSchema.mergeFrom(MessageSchema.java:3844)
> 04-23 15:47:43.036 16447 16492 E AndroidRuntime: 	at com.google.protobuf.GeneratedMessageLite.parsePartialFrom(GeneratedMessageLite.java:1532)
> 04-23 15:47:43.036 16447 16492 E AndroidRuntime: 	at com.google.protobuf.GeneratedMessageLite.parseFrom(GeneratedMessageLite.java:1695)
> 04-23 15:47:43.036 16447 16492 E AndroidRuntime: 	at com.google.protobuf.GeneratedMessageLite.parseFrom(GeneratedMessageLite.java:1688)
> 04-23 15:47:43.036 16447 16492 E AndroidRuntime: 	at mozilla.appservices.logins.MsgTypes$PasswordInfos.parseFrom(MsgTypes.java:1752)
> 04-23 15:47:43.036 16447 16492 E AndroidRuntime: 	at mozilla.appservices.logins.DatabaseLoginsStorage.getByBaseDomain(DatabaseLoginsStorage.kt:230)
> 04-23 15:47:43.036 16447 16492 E AndroidRuntime: 	at mozilla.components.service.sync.logins.SyncableLoginsStorage$getByBaseDomain$2.invokeSuspend(SyncableLoginsStorage.kt:253)
> 04-23 15:47:43.036 16447 16492 E AndroidRuntime: 	at mozilla.components.service.sync.logins.SyncableLoginsStorage$getByBaseDomain$2.invoke(Unknown Source:10)
> 04-23 15:47:43.036 16447 16492 E AndroidRuntime: 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
> 04-23 15:47:43.036 16447 16492 E AndroidRuntime: 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:154)
> 04-23 15:47:43.036 16447 16492 E AndroidRuntime: 	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
> 04-23 15:47:43.036 16447 16492 E AndroidRuntime: 	at mozilla.components.service.sync.logins.SyncableLoginsStorage.getByBaseDomain(SyncableLoginsStorage.kt:252)
> 04-23 15:47:43.036 16447 16492 E AndroidRuntime: 	at mozilla.components.service.sync.logins.GeckoLoginStorageDelegate$onLoginFetch$1.invokeSuspend(GeckoLoginStorageDelegate.kt:66)
> 04-23 15:47:43.036 16447 16492 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
> 04-23 15:47:43.036 16447 16492 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
> 04-23 15:47:43.036 16447 16492 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
> 04-23 15:47:43.036 16447 16492 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
> 04-23 15:47:43.036 16447 16492 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
> 04-23 15:47:43.036 16447 16492 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
> 04-23 15:47:43.036 16447 16492 I Process : Sending signal. PID: 16447 SIG: 9
> ```

v0.58.1 (out now) should resolve these issues, let us know if it doesn't!

**Comment by grigoryk** [comment]
Okay, local Fenix builds with 0.58.1 appear to behave well. Let's land this and see if anything else blows up :)

**Comment by grigoryk** [comment]
`build-browser-awesomebar` failure on CI is an intermittent (dependency resolution failure).

**Comment by rfk** [comment]
> Just a side note: We do have the capability now to run sample apps as well as other on-device
> tests on Firebase device lab for all components with just a couple of lines of config. Is this
> something we can write a UI test for that uses the sample app?

@pocmo I'm very interested in seeing what's possible here, do you have an existing sample app that would be a good example for how to write such a thing?

> I am not sure about test credentials or similar - they would be readable by anyone?

I think we can make this a tractable problem, either via CI secrets or by having a set of well-know credentials that we don't care very much about...

> It's not clear to me if it's worth the added costs and slower CI cycles.
> I guess we've wasted enough time on these issues that it does sound worth it over time...

In appservices we have a pattern of tagging "high risk" PRs with metadata to trigger additional tests, so I'd be interested in having such on-device tests run on such PRs even if they don't run all the time. For example we could make sure they get run of the PR that cuts a new appservices release, to decrease the chance of it shipping with issues like this in future.

**Comment by pocmo** [comment]
> > Just a side note: We do have the capability now to run sample apps as well as other on-device
> > tests on Firebase device lab for all components with just a couple of lines of config. Is this
> > something we can write a UI test for that uses the sample app?
> 
> @pocmo I'm very interested in seeing what's possible here, do you have an existing sample app that would be a good example for how to write such a thing?

Here are some smoke tests that instrument our sample browser:
https://github.com/mozilla-mobile/android-components/blob/master/samples/browser/src/androidTest/java/org/mozilla/samples/browser/SmokeTests.kt

> > I am not sure about test credentials or similar - they would be readable by anyone?
> 
> I think we can make this a tractable problem, either via CI secrets or by having a set of well-know credentials that we don't care very much about...
> 
> > It's not clear to me if it's worth the added costs and slower CI cycles.
> > I guess we've wasted enough time on these issues that it does sound worth it over time...
> 
> In appservices we have a pattern of tagging "high risk" PRs with metadata to trigger additional tests, so I'd be interested in having such on-device tests run on such PRs even if they don't run all the time. For example we could make sure they get run of the PR that cuts a new appservices release, to decrease the chance of it shipping with issues like this in future.

Currently we only run "on-device" (UI) tests for branches pushed to the repo for the same reason (and bors will push to the repo before trying to merge). However if we'd would need to inject secrets into that task then the setup will be a bit more complicated here than just landing tests and instructing TC to run them.

**Pull request merged**
