### PR TITLE
Closes #11252: fix for not hiding the keyboard after edit toolbar loses focus

### LINKED ISSUE #11252: [Bug]: when edittext loses focus, keyboard gets called again on android 12
This one relates to [mozilla-mobile/fenix#22205](https://github.com/mozilla-mobile/fenix/issues/22205)

Initially, we thought that it has something to do with deprecated `toggleSoftInput` method, the change that came with android 12.
It has some text regarding changes in how focus works

```
* In particular during focus changes, the current visibility of the IME is not
     * well defined. Starting in {@link Build.VERSION_CODES#S Android S}, this only
     * has an effect if the calling app is the current IME focus.
     */
```

However, testing inside a dummy app reviled that this method still works correctly on android 12.
We came by the `showKeyboard(flags = InputMethodManager.SHOW_FORCED)` line, which was causing the hide/show-again affect. It turned out to be a fix for Fire TV projects, on which keyboard didn't work correctly unless was called by `SHOW_FORCED`.

Related issues are 
https://github.com/mozilla-mobile/android-components/issues/358
https://github.com/mozilla-mobile/firefox-connect/issues/114

### PR DESCRIPTION
**Pull request by mavduevskiy**
Initially, we thought that it has something to do with deprecated `toggleSoftInput` method, the change that came with android 12.
It has some text regarding changes in how focus works

```
* In particular during focus changes, the current visibility of the IME is not
     * well defined. Starting in {@link Build.VERSION_CODES#S Android S}, this only
     * has an effect if the calling app is the current IME focus.
     */
```

However, testing inside a dummy app reviled that this method still works correctly on android 12.
We came by the `showKeyboard(flags = InputMethodManager.SHOW_FORCED)` line, which was causing the hide/show-again affect. It turned out to be a fix for Fire TV projects, on which keyboard didn't work correctly unless was called by `SHOW_FORCED`.

Related issues could be check inside the #11252 issue.

### CODE REVIEW

**Review by Amejia481 — APPROVED** [review]
✅

**Comment by Amejia481** [comment]
A small nit from `ktlint`

```

[task 2021-11-10T20:39:05.499Z] > Task :ktlint
[task 2021-11-10T20:39:05.499Z] WARNING: An illegal reflective access operation has occurred
[task 2021-11-10T20:39:05.499Z] WARNING: Illegal reflective access by org.jetbrains.kotlin.com.intellij.util.ReflectionUtil (file:/builds/worker/fetches/android-gradle-dependencies/central/org/jetbrains/kotlin/kotlin-compiler-embeddable/1.4.31/kotlin-compiler-embeddable-1.4.31.jar) to method java.util.ResourceBundle.setParent(java.util.ResourceBundle)
[task 2021-11-10T20:39:05.500Z] WARNING: Please consider reporting this to the maintainers of org.jetbrains.kotlin.com.intellij.util.ReflectionUtil
[task 2021-11-10T20:39:05.500Z] WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[task 2021-11-10T20:39:05.500Z] WARNING: All illegal access operations will be denied in a future release
[task 2021-11-10T20:39:13.399Z] /builds/worker/checkouts/src/components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/edit/EditToolbar.kt:12:1: Unused import
[task 2021-11-10T20:39:13.899Z] 
```

**Review by pocmo — APPROVED** [review]

**Comment by Amejia481** [comment]
@Mergifyio backport releases/95.0

**Comment by Amejia481** [comment]
@Mergifyio backport releases/95.0

**Pull request merged**
