### PR TITLE
Preserve parent id during convert from tab session to state

### PR DESCRIPTION
**Pull request by mawen7**
---

For https://github.com/mozilla-mobile/fenix/issues/2483

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- [ ] **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- [ ] **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Comment by pocmo** [comment]
@csadilek Actually, I just noticed that we need to add all the new properties to `toContentState()` etc. for `Session`s that are getting added (as opposed to using `Session.foo = bar`). In most cases that is probably not an issue in reality most of the time because those values get set on the `Session` after it was added to the `SessionManager`.

**Comment by mawen7** [comment]
@pocmo That seems more maintainable for me. Shall I update my PR to move `parentId` from `TabSessionState` to `ContentState` or are we waiting for feedback from @csadilek ?

**Comment by pocmo** [comment]
@mawen7 Sorry for the confusion. Your PR is fine as-is. I was discussing some potential follow-up work that your PR helped uncover. :)

**Pull request merged**
