### PR TITLE
For #12034 - Support reverse landscape orientation for fullscreen videos

### PR DESCRIPTION
**Pull request by indurs**
This allows users to view the full screen video both in landscape and reverse landscape even when auto rotate option is disabled in device settings

https://user-images.githubusercontent.com/12825812/164383906-a2b40084-ee57-432b-9b57-7c73092c690c.mp4

### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/main/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/main/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Comment by Mugurell** [comment]
Seems like a test needs to be updated

```
 SUITE: mozilla.components.feature.media.fullscreen.MediaSessionFullscreenFeatureTest
   TEST: screen orientation is updated correctly
   FAILURE

 Argument(s) are different! Wanted:
 activity.setRequestedOrientation(11);
 -> at android.app.Activity.setRequestedOrientation(Activity.java)
 Actual invocations have different arguments:
 activity.setRequestedOrientation(6);
 -> at mozilla.components.feature.media.fullscreen.MediaSessionFullscreenFeature.processFullscreen(MediaSessionFullscreenFeature.kt:55)
```

**Comment by indurs** [comment]
Ok.. Thank You !  I will update the MediaSessionFullscreenFeatureTest

**Review by Mugurell — APPROVED** [review]
This looks good, thank you @indurs .
Can you please add a note in `changelog.md` about this change and then we can land this?

**Comment by indurs** [comment]
@Mugurell , I've updated the changelog.md

**Pull request merged**
