### PR TITLE
Enable incremental room kapt processing

### PR DESCRIPTION
**Pull request by NotWoods**
This saves us nearly 6 minutes in the artifact transformations stage.

### CODE REVIEW

**Comment by grigoryk** [comment]
How stable is it? Looking at their issue tracker (https://issuetracker.google.com/issues/160042657, https://issuetracker.google.com/issues/159501719) it seems like people run into some issues here and there. Did you see any locally?

**Comment by grigoryk** [comment]
Also, I'd love to see a before/after build scans for this. Can you share links for them?

**Comment by NotWoods** [comment]
I haven't seen local problems yet, we can always remove this flag per-module if we run into problems.

I'll send the HTML files to you on Slack since I can't attach them on Github. Here's the relevant numbers:

|                     | Control  | Incremental |
| ------------------- | -------: | ----------: |
| Artifact Transforms | 5m54.44s | 8.669s      |

**Comment by grigoryk** [comment]
bors retry

**Pull request merged**
