### PR TITLE
Closes #4425 Remove Padding When Both URL and Title is Visible In Bro…

### LINKED ISSUE #4425: Custom Tab URL and Website Name Text is Too Small
When using Custom Tab where there is both the website name and the URL.  The text in the URL bar is too small after auto adjusting.  This needs to be fixed so the texts should take more room in the URL bar.

### PR DESCRIPTION
**Pull request by rocketsroger**
…wserToolBar

---

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- [ ] **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- [ ] **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Comment by rocketsroger** [comment]
Due to the padding between both the URL and Title, It caused the text to shrink till its 1/3 the toolbar size.  I've remove the padding between the URL and Title, since TextViews have default padding already.

**Comment by Amejia481** [comment]
@jonalmeida Do you think the actual padding between the url and the title is too big? Or this was part of the original design?   

**The actual fix**
image

**Chrome**
image

**Comment by jonalmeida** [comment]
> @jonalmeida Do you think the padding between the url and the title is too big? Or this was part of the original design?

Correct, the padding seems a little too much. It should look like the original that we had before:
Screen Shot 2019-09-17 at 4 44 21 PM

**Comment by rocketsroger** [comment]
Figured out it wasn't the padding.  There is actually no padding between the two textviews.  The text was set to 15sp and that was how big the text are.  I'm looking into how best fix this problem.  
1. If we add padding to push these two textviews closer, we end up having issue when user set the display size larger.  
2. If we remove the padding, then the textviews are taking the same amount of space but now the distance between the textviews are too much.

**Comment by rocketsroger** [comment]
Gravity is the solution.  I've made the Title textview gravity bottom and URL textview gravity top.  If only URL then gravity vertical center.  This allows us to remove the padding while still keep the textviews closer together when text is small.

**Comment by jonalmeida** [comment]
Excellent! Keep in mind, these are the UX specs that we're (eventually) trying to get close to for handheld devices. Our toolbar needs to work with tablets and tv screens (Echo Show) as well so we're taking each implementation bit in small steps. 👌

**Comment by rocketsroger** [comment]
Agreed.  Maybe we need to allow the user of BrowserBar to be able to specify the text size?

**Comment by jonalmeida** [comment]
> Agreed. Maybe we need to allow the user of BrowserBar to be able to specify the text size?

Sounds like follow-up work.

**Comment by rocketsroger** [comment]
Sure, I'll create a issue to track it.  Thanks,

**Pull request merged**
