### PR TITLE
Closes #2978 runWithSessionIdOrSelected incorrectly runs for provided AND selected session.

### LINKED ISSUE #2978: SessionManager#runWithSessionIdOrSelected incorrectly runs for provided AND selected session

### PR DESCRIPTION
**Pull request by Amejia481**
### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### CODE REVIEW

**Comment by csadilek** [comment]
@Amejia481 @pocmo to me the code does something different than the commit message and test name claim. I might be missing context but:

"must only run on the SessionId when the session manager has both a selected session and the provided sessionId" is not what's happening here? The block runs if there's a session with that ID, if not it runs on the selected session, if one exists.

Like I said, maybe I am misreading, but seems like the name/commmit msg need an update.

**Comment by Amejia481** [comment]
@csadilek [Before this commit](https://github.com/mozilla-mobile/android-components/pull/2956), the block was running on both the provided `sessionId` and the `selectedSession` when both were available. The intention is to fix that. Run on the  provided sessionId and if not available run on the **selected session**.

**Previous code:**
```kotlin
fun SessionManager.runWithSessionIdOrSelected(
    sessionId: String?,
    block: SessionManager.(Session) -> Unit
): Boolean {
    var blockWasRun = false
    sessionId?.let {
        findSessionById(sessionId)?.let { session ->
            block(session)
            blockWasRun = true
        }
    }
    selectedSession?.let {
        block(it)
        blockWasRun = true
    }
    return blockWasRun
}
```

**Actual code**
```kotlin
fun SessionManager.runWithSessionIdOrSelected(
    sessionId: String?,
    block: SessionManager.(Session) -> Unit
): Boolean {
    sessionId?.let {
        findSessionById(sessionId)?.let { session ->
            block(session)
            return true
        }
    }
    selectedSession?.let {
        block(it)
        return true
    }
    return false
}
```

Maybe the actual long commit message is not clearly conveying the intention. Any suggestions to improve can be pretty helpful.

**Actual commit message.**
Making sure runWithSessionIdOrSelected only runs on the provided sessionid when the session manager has both the provided SessionId and a selected session.

**Comment by csadilek** [comment]
@Amejia481 yes, the change is clear. It's just that's not how I read the test name and commit message. I would file a bug "runWithSessionIdOrSelected incorrectly runs for provided AND selected selected session" and the commit to "Closes #....: ....".

The test name could be "runWithSessionIdOrSelected should run for either provided or selected session, but not both".

Just a comment though because it confused me.

**Comment by Amejia481** [comment]
@csadilek  Thanks the help :)

**Pull request merged**
