### PR TITLE
For #11387 - Remove deprecated constructor from PromptFeature.kt

### LINKED ISSUE #11387: Remove deprecated constructor from PromptFeature.kt
Remove this constructor https://github.com/mozilla-mobile/android-components/blob/main/components/feature/prompts/src/main/java/mozilla/components/feature/prompts/PromptFeature.kt

````
@Depreceated("Pass only activity or fragment instead")
 constructor(
        activity: Activity? = null,
        fragment: Fragment? = null,
        store: BrowserStore,
        customTabId: String? = null,
        fragmentManager: FragmentManager,
        loginPickerView: SelectablePromptView<Login>? = null,
        onManageLogins: () -> Unit = {},
        creditCardPickerView: SelectablePromptView<CreditCard>? = null,
        onManageCreditCards: () -> Unit = {},
        onSelectCreditCard: () -> Unit = {},
        onNeedToRequestPermissions: OnNeedToRequestPermissions
    )
`````
Double check that neither Fenix or Focus uses it.

Created out of a discussion from https://github.com/mozilla-mobile/android-components/pull/10247#discussion_r631362523

### PR DESCRIPTION
**Pull request by sarah541**
Fixes #11387 

### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/main/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/main/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Review by gabrielluong — APPROVED** [review]
Can you update the PR and commit description to add a bit more detail that its removing the deprecated constructor in PromptFeature

**Comment by gabrielluong** [comment]
Le's go with "Remove deprecated constructor in PromptFeature" to not have anything in braces inside of our commit msg.

**Review by gabrielluong — APPROVED** [review]

**Comment by Amejia481** [comment]
This looks good as it's. We normally also add an entry to the [changelog file](https://github.com/mozilla-mobile/android-components/blob/main/docs/changelog.md) you can see an example  [here](https://github.com/mozilla-mobile/android-components/commit/0e963caf28a900dae6bc5a408d8cc3d12acb863a).

**Comment by sarah541** [comment]
> This looks good as it's. We normally also add an entry to the [changelog file](https://github.com/mozilla-mobile/android-components/blob/main/docs/changelog.md), when we update a public API, you could see an example [here](https://github.com/mozilla-mobile/android-components/commit/0e963caf28a900dae6bc5a408d8cc3d12acb863a).

The change was opened as a separate PR since this one was merged : https://github.com/mozilla-mobile/android-components/pull/11442

**Pull request merged**
