### PR TITLE
Add extension function InputStream.readAll()

### PR DESCRIPTION
**Pull request by espertus**
This will be used by my P2P library and is sufficiently general to belong in support.
---

### Pull Request checklist

- [X] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [X] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [X] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [X] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- [ ] **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- [ ] **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Comment by jonalmeida** [comment]
@espertus Ah shoot, looks like a changelog conflict. We can retry after it's fixed.

Cancelled bors, so that it doesn't try (and fail) to merge.

**Comment by Amejia481** [comment]
@espertus Do you still want bring this patch in? :)

If so I think that we have to move the changelog entry to the `20.0.0` section, also would you mind squashing the commits?

**Comment by espertus** [comment]
I will accept your judgment on whether this is worth checking in, in which
case I will make the other changes.

**Comment by pocmo** [comment]
We looked at this in triage and decided to not land this extension function for now. Nevertheless thank you for constantly trying to improve our code and documentation. :)

**Pull request closed without merging**
