### PR TITLE
For #10555 - Dont auto show toolbar after short taps

### PR DESCRIPTION
**Pull request by Mugurell**
We need to wait until having a response from GeckoView on how it handled the
touch only after which we'll know whether to animate the toolbar or not.

The edgecase scenario of having pull to refresh enabled even before having a
response from GeckoView will still work because "canOverscrollTop()" only
checks for the touch to not be handled by the browser to pan the page.

https://user-images.githubusercontent.com/11428869/124614670-2819f480-de7d-11eb-91dc-9c327ff03685.mp4

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Review by pocmo — APPROVED** [review]

**Comment by Mugurell** [comment]
Thank you @pocmo !

I see one test was failing, because [here](https://github.com/Mugurell/android-components/blob/e15ec2074e58f22a6602e45b872751e56862cd24/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/NestedGeckoViewTest.kt#L145) I haven't updated it based on the proposed changes - inputResult is not `unhandled` but `unknown`.

Everything should be green now but even if the changes are small I'd prefer landing this after the merge and after some time in Nightly uplift it if needed.

**Comment by Mugurell** [comment]
```
[36mINFO[0m[0062] Running: [/bin/sh -c URL_FLANK_BIN="$($CURL --silent 'https://api.github.com/repos/Flank/flank/releases/latest' | jq -r '.assets[].browser_download_url')"     && $CURL --output "${TEST_TOOLS}/flank.jar" "${URL_FLANK_BIN}"     && chmod +x "${TEST_TOOLS}/flank.jar"] 
curl: (3) Illegal characters found in URL
error building image: error building stage: failed to execute command: waiting for process to exit: exit status 3
Error: Could not build image.
[taskcluster 2021-07-14 16:23:57.527Z] === Task Finished ===
[taskcluster 2021-07-14 16:23:57.596Z] Artifact "public/image.tar.zst" not found at "/workspace/image.tar.zst"
[taskcluster 2021-07-14 16:23:57.664Z] Unsuccessful task run with exit code: 1 completed in 71.923 seconds
```

One more try.

**Comment by Mugurell** [comment]
I'm seeing the same error as above for the `build-docker-image-ui-tests` task.
Rebasing and trying again.

**Comment by Mugurell** [comment]
@Mergifyio backport releases_v91.0.0

**Comment by Mugurell** [comment]
@Mergifyio backport releases_91.0

**Comment by Mugurell** [comment]
@Mergifyio backport releases/91.0

**Comment by Mugurell** [comment]
@Mergifyio backport releases/91.0

**Comment by Mugurell** [comment]
Not sure why this fails.
Hoping that if works now after some time left to rest.

**Comment by Mugurell** [comment]
@Mergifyio backport releases/91.0

**Comment by Mugurell** [comment]
@Mergifyio backport releases/91.0

**Comment by Mugurell** [comment]
@Mergifyio backport releases/91.0

**Pull request merged**
