### PR TITLE
Update Kotlin to 1.4.21 and Coroutines to 1.4.2.

### PR DESCRIPTION
**Pull request by pocmo**
Building and testing some random components worked without issues. Let's test on taskcluster..

### CODE REVIEW

**Comment by pocmo** [comment]
Found at least one deprecated method in the stdlib. Will push an update.

**Comment by pocmo** [comment]
> [task 2020-12-04T17:41:10.041Z] * What went wrong:
[task 2020-12-04T17:41:10.041Z] Gradle build daemon disappeared unexpectedly (it may have been killed or may have crashed)

:|

**Comment by pocmo** [comment]
Looking better now, just needs some warnings fixed.

**Review by rocketsroger — APPROVED** [review]

**Comment by pocmo** [comment]
Added "do not land". Fenix is not on that version yet and I am not sure what the impact will be if it will be upgraded through us. Let's test that first. Which will probably mean this is a PR for 2021. :)

**Comment by pocmo** [comment]
I had no problems building and testing Fenix with those changes. Let's land!

**Pull request merged**
