### PR TITLE
Added Icons PNGs and Updated Icons ReadMe. Fixes Issue #260

### PR DESCRIPTION
**Pull request by wajahatkarim3**
This Pull Request adds:
* Icon PNGs of Vector XMLs for easily viewing
* Updated Icons Read me by adding a list of all icons with links to the respective vector XML files
* Fixes issue #260

### CODE REVIEW

**Comment by pocmo** [comment]
We have [a website](https://mozilla-mobile.github.io/android-components/) now (we didn't at the time the issue was filed). So I wonder if there are ways to render the drawable XML files directly with the help of some JavaScript.

**Comment by wajahatkarim3** [comment]
That's a good idea. I think I will look into it and see if anything can work about it. 👍

**Comment by pocmo** [comment]
Awesome, thank you! :)

Alex Lockwood as written a bunch of tools that work with vector drawables and SVGs, maybe there's something helpful:
https://github.com/alexjlockwood

**Comment by pocmo** [comment]
Closing this for now. Let's re-open if you find some way to make this easier to update and keep in sync. :)

**Pull request closed without merging**
