### PR TITLE
Bump a-s dependency to 67.1.0

### PR DESCRIPTION
**Pull request by lougeniaC64**
Changes: https://github.com/mozilla/application-services/releases/tag/v67.1.0

### CODE REVIEW

**Comment by st3fan** [comment]
@lougeniaC64 how urgent is this update? Do you want this to ship in Fenix 84? Do we need to uplift this to A-C 67.0.x? 

cc @grigoryk

**Comment by lougeniaC64** [comment]
> @lougeniaC64 how urgent is this update? Do you want this to ship in Fenix 84? Do we need to uplift this to A-C 67.0.x?
> 
> cc @grigoryk

@st3fan I don't think this is urgent enough for an uplift. @badboy please correct me if I'm wrong.

**Comment by badboy** [comment]
Nothing from the Glean side. Currently Glean is only bundled into application-services for the iOS release.
The Android releases are still shipped separately.

**Comment by lougeniaC64** [comment]
> Nothing from the Glean side. Currently Glean is only bundled into application-services for the iOS release.
> The Android releases are still shipped separately.

Thanks, for the explanation @badboy!

@st3fan none of the other changes in a-s v67.1.0 require an uplift.

**Comment by jonalmeida** [comment]
bors try

**Comment by jonalmeida** [comment]
bors try

```
[task 2020-12-07T18:25:43.373Z] The message received from the daemon indicates that the daemon has disappeared.
[task 2020-12-07T18:25:43.373Z] Build request sent: Build{id=0d7b37a4-16d9-4d0f-8cdc-57bd13f011b2, currentDir=/builds/worker/checkouts/src}
[task 2020-12-07T18:25:43.373Z] Attempting to read last messages from the daemon log...
[task 2020-12-07T18:25:43.373Z] Daemon pid: 1664
```

Daemon crashed. Restarting.

**Comment by jonalmeida** [comment]
> ## try
> 
> Already running a review

raw

**Comment by jonalmeida** [comment]
bors try

**Comment by jonalmeida** [comment]
bors try

**Comment by rfk** [comment]
I think we can just close this out, @travis79 is going to be making a change to the nimbus wrapper for https://jira.mozilla.com/browse/SDK-126 which requires a `v68.0.0` release, and things will probably be simplest if we do the version bump inline in that PR.

**Pull request closed without merging**
