### PR TITLE
[wip] attempt to optimize gradle dependency task

### PR DESCRIPTION
**Pull request by bhearsum**
Ideally, this is going to just download deps and skip all the build/test/lint parts.

### CODE REVIEW

**Comment by bhearsum** [comment]
@pocmo - this is obviously not working yet (it's not quite getting the right dependencies, as evidenced by the failed builds), but it _is_ getting most of them, and doing it without executing any builds, et. al. In trying to compare this vs. current tasks I was surprised to see that the current ones only take ~20min (I thought they took hours?), but maybe they only take that long in certain circumstances? I'm also a little bit concerned that my new version isn't actually doing anything (or maybe it's somehow retrieving already cached versions?) - I'm having trouble getting it to log verbosely enough to verify that sort of thing.

In any case, I'm curious what you think about this. If I can sort out the accuracy, and verify that is indeed faster in a case where the old code would take a very long time, is this a viable path forward to improve the toolchain task situation?

**Comment by pocmo** [comment]
> In any case, I'm curious what you think about this. If I can sort out the accuracy, and verify that is indeed faster in a case where the old code would take a very long time, is this a viable path forward to improve the toolchain task situation?

This definitely sounds interesting, yeah!

I was wondering if we could avoid a lot of downloads by unpacking the dependencies from the "old" toolchain task (basically to "bootstrap" the new toolchain task). But I guess this would mean we would accumulate all the unused dependencies and the archive would get bigger and bigger over time.

> In trying to compare this vs. current tasks I was surprised to see that the current ones only take ~20min (I thought they took hours?), but maybe they only take that long in certain circumstances?

Yeah, my impression is that the runtime fluctuates over the day - depending on the other taskcluster workload (is this possible?). It definitely gets more annoying if there are intermittent failures, that require a rerun, and if you need to land in A-C and Fenix.

**Comment by bhearsum** [comment]
@pocmo - this is obviously not working yet (it's not quite getting the right dependencies, as evidenced by the failed builds), but it _is_ getting most of them, and doing it without executing any builds, et. al. In trying to compare this vs. current tasks I was surprised to see that the current ones only take ~20min (I thought they took hours?), but maybe they only take that long in certain circumstances? I'm also a little bit concerned that my new version isn't actually doing anything (or maybe it's somehow retrieving already cached versions?) - I'm having trouble getting it to log verbosely enough to verify that sort of thing.

In any case, I'm curious what you think about this. If I can sort out the accuracy, and verify that is indeed faster in a case where the old code would take a very long time, is this a viable path forward to improve the toolchain task situation?

> > In any case, I'm curious what you think about this. If I can sort out the accuracy, and verify that is indeed faster in a case where the old code would take a very long time, is this a viable path forward to improve the toolchain task situation?
> 
> This definitely sounds interesting, yeah!
> 
> I was wondering if we could avoid a lot of downloads by unpacking the dependencies from the "old" toolchain task (basically to "bootstrap" the new toolchain task). But I guess this would mean we would accumulate all the unused dependencies and the archive would get bigger and bigger over time.

I can't decide how I feel about this :rofl:. We could reset it at points in time to fix the ever-increasing-size issue, but it still feels awfully hacky.

> > In trying to compare this vs. current tasks I was surprised to see that the current ones only take ~20min (I thought they took hours?), but maybe they only take that long in certain circumstances?
> 
> Yeah, my impression is that the runtime fluctuates over the day - depending on the other taskcluster workload (is this possible?). It definitely gets more annoying if there are intermittent failures, that require a rerun, and if you need to land in A-C and Fenix.

I don't think runtime would fluctutate based on Taskcluster load. These tasks are largely network bound AFAIK so they be influenced by various factors in AWS beyond our control, and even beyond our ability to have insight into :(.

The pending times (time spent waiting for the task to start) could be influenced by Taskcluster load. This is measured by the difference between the "Started" time and "Scheduled" time.

**Comment by bhearsum** [comment]
> In any case, I'm curious what you think about this. If I can sort out the accuracy, and verify that is indeed faster in a case where the old code would take a very long time, is this a viable path forward to improve the toolchain task situation?

@rvandermeulen - I'm also curious what you think here, as I know you deal with the fallout from toolchain failures at times.

**Comment by bhearsum** [comment]
I've been trying to sort out the missing dependencies, and in doing so, may have discovered that this approach is impossible. It turns out that some (maybe all) of the missing dependencies in my attempt are from so-called "detached configurations". According to [this bit of gradle documentation](https://docs.gradle.org/current/userguide/dependency_management.html):

> The difference is that Gradle may discover more dependencies and artifacts depending on the tasks you execute. As a matter of fact, Gradle cannot automatically discover detached configurations, which are basically dependency graphs resolved as an internal implementation detail of the execution of a task: they are not, in particular, declared as an input of the task because they effectively depend on the configuration of the task at execution time.

If this is all correct, my attempt to skip task execution to speed up downloads simply will not work.

**Comment by bhearsum** [comment]
closing this because it is impossible to achieve AFAICT

**Pull request closed without merging**
