### PR TITLE
For #12361 - Implement equals and hashCode methods for SearchRequest

### PR DESCRIPTION
**Pull request by Alexandru2909**
Fixes [Fenix bug.](https://github.com/mozilla-mobile/fenix/issues/25047) 

Implemented `equals` and `hashCode` methods for `SearchRequest` in order to allow the user to [perform](https://github.com/mcarare/android-components/blob/be0d8903cd7b6378d9057af19c78c47de17b734b/components/feature/search/src/main/java/mozilla/components/feature/search/SearchFeature.kt#L48) the same query multiple times.

### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/main/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/main/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Review by csadilek — CHANGES_REQUESTED** [review]
Thanks @Alexandru2909. This is on the right track, but I think the cause of this problem really is in the implementation of `SearchFeature`. In particular, the workaround here is causing this. The feature observes too many state changes and then tries to filter them after `map`. So, we should fix this workaround instead.

This change to the feature should fix the problem, by relying on our `ifChanged` utility we filter state changes before we `map`: 
https://github.com/csadilek/android-components/commit/2757fd960c698f045a5dd840727b5822480e98ce

This would also make the feature consistent with all our other implementations. Wdyt? I just tried this and it seems to work fine.

**Comment by csadilek** [comment]
We should also add a test to `SearchFeatureTest` when we're fixing this.

**Comment by Alexandru2909** [comment]
Thanks for reviewing this! Your implementation works just fine for me too! What I tried before creating this PR was to move the `mapNotNull` call after the `distinctUntilChangedBy`, but making the changes in `SearchRequest` instead seemed safer.

I'll add the changes you requested.

**Review by csadilek — APPROVED** [review]
👍 🚢

**Pull request merged**
