### PR TITLE
 GeckoView update (nightly) (20191018-141230)

### PR DESCRIPTION
**Pull request by MickeyMoz**

### CODE REVIEW

**Comment by Amejia481** [comment]
bors -r

**Comment by Amejia481** [comment]
Yes, bors r- !
thanks

**Comment by pocmo** [comment]
Why `r-`? :)

**Comment by pocmo** [comment]
(Btw. this is still scheduled in bors. the bors command need to be at the beginning of a line!)

**Comment by Amejia481** [comment]
I'm not sure if we want to commit `metrics.md`.  Should we?

**Comment by pocmo** [comment]
Yes! :)

https://github.com/mozilla-mobile/android-components/blob/master/automation/taskcluster/action/update_geckoview.sh#L71-L75

**Comment by Amejia481** [comment]
Got it thanks!

**Comment by Amejia481** [comment]
bors retry

**Pull request merged**
