### PR TITLE
Bug 1663967 - Ship v16.0.0 of feature-webcompat.

### PR DESCRIPTION
**Pull request by denschub**
This is version 16 of the WebCompat feature, aka "Website Interventions"!

Besides the usual "add and remove some interventions", this version also includes a new and improved JS console notification, so that web developers who debug their own site will be made aware that there is, in fact, a WebCompat issue being hotfixed. This also contains a change that prevents our addon from changing the User Agent string if the user is in "Request Desktop Site" mode, as that mode spoofs the User Agent anyway.

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Comment by jonalmeida** [comment]
@Amejia481 would you know what list of things should be tested when verifying this PR? Happy to help. 🙂

**Comment by denschub** [comment]
I'll temporarily push this back by marking it as a draft. We have some weird test failures on desktop, and even though they look like an issue with the tests, I want to make sure.

**Comment by Amejia481** [comment]
> @Amejia481 would you know what list of things should be tested when verifying this PR? Happy to help. 🙂

We normally  do a manual test, to confirm the extension is still visible in the menu and working in Fenix, additionally we check that every time the extension is updated the `version` number on `manifest.json` is increased, if this is not done the changes are not going to be available. Maybe @csadilek could add some additional tips.

**Comment by denschub** [comment]
Okay, we temporarily backed out the fancy new console log notification until we have figured out the broken tests. The new notification will ship in v16.1.0, but for now, we just want to get these new interventions out into the world. :)

**Comment by denschub** [comment]
>  would you know what list of things should be tested when verifying this PR?

Little-known fun fact! There is https://webcompat-addon-testbed.herokuapp.com/, which we built for our manual QA cycles. Loading this site should show you five green squares on Android. (That is, if you load the site. We're aware of that not working when the testbed is restored from a previous session, but that's not a priority right now). If there's something red, then we goofed up.

And a second bonus fact: in `about:config`, there are two prefs, `extensions.webcompat.perform_injections` and `extensions.webcompat.perform_ua_overrides`. If you toggle those to `false` and then reload that testbed, it's all red. 🧙

**Comment by pocmo** [comment]
I always ✅ the PR if there's nothing weird about it. I feel like we can trust the webcompat team to completely maintain this (which reminds me that I never merged the CODEOWNER changes).

**Pull request merged**
