### PR TITLE
Initialize sentry client lazily #3445

### PR DESCRIPTION
**Pull request by KKS161994**
---

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- [ ] **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- [ ] **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Comment by KKS161994** [comment]
I have ressolved the ktlint issues and its included in the pull request .

**Comment by rocketsroger** [comment]
@KKS161994 Looks like because the client is now initialized lazily.  There are some automated test failure.  Can you please take a look at the tests and see if you can fix them also?  

You can run these tests by right clicking the crash [lib-crash] -> test -> java folder in Android Studio project tree.  Then selecting the "run tests in 'java' " option.

**Comment by KKS161994** [comment]
I had to mock Crash.UncaughtExceptionCrash to in following function
1-`SentryService disables exception handler and forwards tags`
2-`SentryService passes an environment or null`
3-`SentryService adds default tags`
So as to call .report with Sentry Service so that it can call the client initialisation call which was described in lazy.
Since lazy variables are only during its first invocation.
All tests are up an running,

**Comment by KKS161994** [comment]
I had to mock Crash.UncaughtExceptionCrash to in following function
1-SentryService disables exception handler and forwards tags
2-SentryService passes an environment or null
3-SentryService adds default tags
So as to call .report with Sentry Service so that it can call the client initialisation call which was described in lazy.
Since lazy variables are only during its first invocation.
All tests are up and running,

**Comment by KKS161994** [comment]
I had to mock Crash.UncaughtExceptionCrash to in following function
1-SentryService disables exception handler and forwards tags
2-SentryService passes an environment or null
3-SentryService adds default tags
So as to call .report with Sentry Service so that it can call the client initialisation call which was described in lazy.
Since lazy variables are only during its first invocation.
All tests are up and running,

**Comment by KKS161994** [comment]
I had to mock Crash.UncaughtExceptionCrash to in following function
1-SentryService disables exception handler and forwards tags
2-SentryService passes an environment or null
3-SentryService adds default tags
So as to call .report with Sentry Service so that it can call the client initialisation call which was described in lazy.
Since lazy variables are only during its first invocation.
All tests are up and running,

**Comment by KKS161994** [comment]
I have also resolved resolved the ktlint issues which I received on invocation of .report(). 
Please sir can you check it out and let me know if their are errors.

**Comment by rocketsroger** [comment]
@KKS161994 Everything looks good.   :thumbsup:
One more thing and we're good to go.  Please squash your commits into one commit.  Here's a good link on how to do it:
https://github.com/wprig/wprig/wiki/How-to-squash-commits

**Comment by rocketsroger** [comment]
bors r=rocketsroger

**Comment by KKS161994** [comment]
Sir , for bors its giving pending and running. And in details it shows permission denied . Do I have to do something about it.

**Pull request merged**
