### PR TITLE
No issue: Update A-S to 93.8.0 and Glean to 51.0.1.

### PR DESCRIPTION
**Pull request by mcarare**
### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/main/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/main/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### GitHub Automation

Used by GitHub Actions.

### CODE REVIEW

**Comment by mcarare** [comment]
`Could not find org.jacoco:org.jacoco.ant:0.8.7.`

**Review by badboy — CHANGES_REQUESTED** [review]
We have not yet landed Glean 51.0.1 in m-c ([bug 1781030](https://bugzilla.mozilla.org/show_bug.cgi?id=1781030)). I didn't want to land that on a Friday.

I'll land that now, that should bring it into a-c with the next geckoview bump then.

**Comment by mcarare** [comment]
@badboy So this is still an issue: https://github.com/mozilla-mobile/android-components/issues/11276. And this PR should not have build successfully.

**Comment by badboy** [comment]
I wasn't aware of #11276.
I'll look into why my assumption that this would fail is wrong.

**Comment by rvandermeulen** [comment]
@mcarare IIUC, we should update this PR to include the equivalent change for 93.8.0 that #12567 was attempting to make also.

**Comment by badboy** [comment]
Hm, ok. so this builds fine and so does Fenix with this change, but it will then runtime-crash because it uses a different Glean Kotlin version than the native code provided by GeckoView.

**Comment by badboy** [comment]
Anyway, let's wait for the GeckoView update and bundle these things together.

**Comment by rvandermeulen** [comment]
Fixed by way of #12587.

**Pull request closed without merging**
