### PR TITLE
Closes #2511: Adds optional icon to SearchSuggestionProvider.

### LINKED ISSUE #2511: Add ability to choose a different icon for SearchSuggestionProvider

### PR DESCRIPTION
**Pull request by sblatz**
### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### CODE REVIEW

**Comment by pocmo** [comment]
Can you help me understand the use case? The issue has no text and is not linked to anything in Fenix. :)

**Comment by sblatz** [comment]
Sorry about that! Here are the designs it’s used in: https://mozilla.invisionapp.com/m/share/U8R4ASRNZ59#/353418990

**Comment by pocmo** [comment]
> Sorry about that! Here are the designs it’s used in: https://mozilla.invisionapp.com/m/share/U8R4ASRNZ59#/353418990

Ah, okay. Makes sense. Thanks!

* Do you think we can cover that in `SearchSuggestionProviderTest`?
* Today was release day and need to move that to the 0.49.0-SNAPSHOT changelog now :)

**Comment by sblatz** [comment]
Added tests and updated change log!

**Pull request merged**
