### PR TITLE
For #8837 - Reverse new child tabs order

### PR DESCRIPTION
**Pull request by codrut-topliceanu**
### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks.
- [x] **Tests**: This PR does not include any tests as it is only a minor change.
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md).
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md).

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Review by pocmo — CHANGES_REQUESTED** [review]
This will probably have to wait a bit since we haven't fully migrated away from `SessionManager` to use `BrowserStore` exclusively and this change will cause both sources to be out of sync.

For a similar reason we haven't implemented tab reordering yet, which runs into the same problem.

CC @csadilek

**Comment by pocmo** [comment]
Side note: Looking at the desktop implementation it seems like this is only the behavior while you are on the tab and opening new tabs. If you go to a different tab and back then it will start from the beginning and add tabs next to it in order.

**Comment by codrut-topliceanu** [comment]
@pocmo 
> For a similar reason we haven't implemented tab reordering yet, which runs into the same problem.

You mean this : https://github.com/mozilla-mobile/fenix/pull/16245 ? :)

**Comment by csadilek** [comment]
> You mean this : mozilla-mobile/fenix#16245 ? :)

@codrut-topliceanu Ah no, it was discussed in the context of tabs re-ordering in this ticket: https://github.com/mozilla-mobile/fenix/issues/10344

We decided not to go ahead until the `SessionManager` -> `BrowserStore` refactoring is complete, as otherwise it would cause a lot of duplicate work. The same applies to your change here, which you'd have to implement for both the store and the `SessionManager`. So, I think we should also wait with this until we can get rid of `SessionManager` as the authority on tabs. This can be done soon (in theory anyway) once no component observers or reads sessions from `SessionManager` anymore.

**Comment by tukusejssirs** [comment]
> until we can get rid of `SessionManager` as the authority on tabs.

@csadilek, may I ask what does this mean? What are the consequencies of removing the `SessionManager` as  the authority on tabs? Is it so on the desktop browser too?

**Pull request closed without merging**
