### PR TITLE
Add ability to reset Nimbus telemetry identifiers.

### PR DESCRIPTION
**Pull request by rfk**
This should be called when the user opts out of telemetry. In the future we may also need to call it when they opt back in, so that we can provide the updated `AvailableRandomizationUnits`.

The corresponding SDK method was added in https://github.com/mozilla/nimbus-sdk/pull/80, and is currently waiting for a new release of nimbus-sdk and application-services before we can merge this PR.

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- ~~[ ] **Tests**: This PR includes thorough tests or an explanation of why it does not~~
  - Like other methods of the `NimbusClient` class, this is a thin pass-through wrapper to the underlying SDK that doesn't have any interesting behaviours to test.
- ~~[ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one~~
  - Covered by the Nimbus SDK changelog.
- ~~[ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features~~
  - No user facing features.

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Comment by rfk** [comment]
See also https://github.com/mozilla-mobile/fenix/pull/17087 for how this might be called from a consuming application.

**Comment by rfk** [comment]
There's a new nimbus release out with this method available, but the change here still depend on https://github.com/mozilla-mobile/android-components/pull/9168 for the `recordExperimentTelemetryEvents` method.

**Comment by rfk** [comment]
@travis79 could I trouble you for a review of this one once #9168 has landed?

**Review by travis79 — APPROVED** [review]
Looks good to me

**Comment by rfk** [comment]
I've rebased this atop the other PR, but looks like some unrelated build bustage. @travis79 it's not clear to me how to move this forward to landing from here with all the bots and what-not in this repo, is that something you can help walk me through?

**Comment by travis79** [comment]
Closing and reopening the PR will retrigger the CI, another approach might be using "bors try" in a comment to trigger bors to trigger it.

**Comment by travis79** [comment]
> This pull request has conflicts when rebasing. Could you fix it @rfk? 🙏

Doh!

**Comment by rfk** [comment]
> This pull request has conflicts when rebasing

Rebased, and updated to do what I *think* is the right thing with `dbScope.launch`; @jhugman could you please check my work on that front?

**Pull request merged**
