### PR TITLE
WIP Update to Kotlin 1.6

### PR DESCRIPTION
**Pull request by grigoryk**
Still working through the tests (see https://github.com/Kotlin/kotlinx.coroutines/blob/master/kotlinx-coroutines-test/MIGRATION.md)

### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/main/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/main/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Comment by jonalmeida** [comment]
Was hoping for a final release of the Compose upgrade, but we got an [RC03](https://developer.android.com/jetpack/androidx/releases/compose-animation#1.1.0-rc03) instead.

**Comment by jonalmeida** [comment]
[Stable release](https://developer.android.com/jetpack/androidx/releases/compose-animation#1.1.0) is out! 🎉

**Comment by grigoryk** [comment]
Fenix side of this work: https://github.com/mozilla-mobile/fenix/pull/23736

**Comment by Mugurell** [comment]
@grigoryk https://github.com/mozilla-mobile/android-components/pull/11754 Would update to latest compose and kotlin versions.
Seems like the test are still passing without updating to the newest `kotlin-coroutines-test` being a blocker.
I've created https://github.com/mozilla-mobile/android-components/issues/11755 for updating the tests before knowing of this PR.

**Comment by Mugurell** [comment]
Will work on adding this on top of https://github.com/mozilla-mobile/android-components/pull/12000 and continue with what's left.

**Comment by csadilek** [comment]
This will be completed in https://github.com/mozilla-mobile/android-components/pull/12006.

**Pull request closed without merging**
