### PR TITLE
Closes #2487: Added support for Beta and Stable channels for GV version verifier plugin..

### LINKED ISSUE #2487: Automate GeckoView Beta update
We have automated updating GeckoView Nightly. Now that we start to use Beta in Fenix it would be helpful if we automate updating Beta too.

### PR DESCRIPTION
**Pull request by Amejia481**
Added two new task `updateGVBetaVersion` and `updateGVStableVersion`. The `updateGVNightlyVersion` task should keep working as it was.

### CODE REVIEW

**Comment by Amejia481** [comment]
@pocmo Would be `updateGVBetaVersion` enough for this issue?

**Comment by Amejia481** [comment]
👍

**Comment by pocmo** [comment]
@Amejia481 ktlint found two issues:

```
/build/android-components/buildSrc/src/main/java/GVVersionVerifierPlugin.kt:103:41: Parameter should be on a separate line (unless all parameters can fit a single line)
/build/android-components/buildSrc/src/main/java/GVVersionVerifierPlugin.kt:103:67: Parameter should be on a separate line (unless all parameters can fit a single line)
```

**Comment by Amejia481** [comment]
PR update :)

**Comment by pocmo** [comment]
🎉

**Pull request merged**
