### PR TITLE
Update search engines

### PR DESCRIPTION
**Pull request by mkaply**
---

### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Comment by pocmo** [comment]
Looks like this broke some of our tests:

```
    AssetsSearchEngineProviderTest. Load search engines for de-DE with global US region override
    AssetsSearchEngineProviderTest. Load search engines for en-US from assets
    AssetsSearchEngineProviderTest. Load search engines for en-US with local RU region override
    AssetsSearchEngineProviderTest. Load search engines for en-US with with filter
    AssetsSearchEngineProviderTest. Load search engines for ru_RU locale with engines not in searchOrder
    AssetsSearchEngineProviderTest. Load search engines for trs locale with non-google initial engines and no default
    AssetsSearchEngineProviderTest. Load search engines for zh-CN_CN locale with searchDefault override
    AssetsSearchEngineProviderTest. load search engines for locale not in configuration
    AssetsSearchEngineProviderTest. provider loads additional identifiers
    AssetsSearchEngineProviderTest. provider loads additional identifiers if search order specified
```

@mkaply Can you double check if the tests need to be updated or if there's an actual problem?

**Comment by mkaply** [comment]
I'm sure this is just test updates. I'll try to get a Fenix build environment together.

**Comment by st3fan** [comment]
@mkaply can you give us an idea of urgency for this patch?

**Comment by mkaply** [comment]
It's really your call. I know there are a lot of bug reports on the missing DDG for certain locales, but it's totally up to you.

**Comment by liuche** [comment]
@st3fan asked vesta in the Fenix bug, and she'd like to get this into the Firefox 81 release for September, so that would put us at either a) picking this up in the AC 57 cut on Tuesday, or picking it up in a dot release.

**Review by pocmo — APPROVED** [review]
All 🟢. Let's land.

bors r+

**Pull request merged**
