### PR TITLE
Issue #5460: Fennec Migration: Keep supported add-ons enabled

### PR DESCRIPTION
**Pull request by csadilek**
Update to keep supported add-ons enabled. This matches against our AMO collection and falls back to a hard-coded list.

### CODE REVIEW

**Comment by grigoryk** [comment]
We tested the following cases:
- no addons to migrate
- v2 version runs for the first time, supported addons are enabled, others disabled
- v1 version runs first, all addons disabled; v2 version runs on top, supported addons enabled

**Comment by csadilek** [comment]
bors r=grigoryk

**Comment by grigoryk** [comment]
bors retry

**Comment by csadilek** [comment]
bors retry

**Comment by csadilek** [comment]
bors retry

(network failuer)

**Comment by sv-ohorvath** [comment]
> We tested the following cases:
> 
> * no addons to migrate
> * v2 version runs for the first time, supported addons are enabled, others disabled
> * v1 version runs first, all addons disabled; v2 version runs on top, supported addons enabled

@grigoryk When you say the available add-ons should be enabled, do you mean just listed as available, or already installed? 
The curent behavior is: if I had ublock installed on Fennec, it will not be installed by default on Fenix too, it's just displayed in the add-ons manager as available.

**Comment by sv-ohorvath** [comment]
Verified as fixed on Build #7

**Pull request merged**
