### PR TITLE
Closes #4636 - Add ShareTarget data class

### LINKED ISSUE #4636: Support ShareTarget in `WebAppManifest`
To support the [Web Share Target API](https://wicg.github.io/web-share-target/#sharetarget-and-its-members), we need to parse the share target data from the web app manifest.

```webidl
dictionary ShareTargetFiles {
  required USVString name;
  required (USVString or sequence<USVString>) accept;
};

dictionary ShareTargetParams {
  USVString title;
  USVString text;
  USVString url;
  (ShareTargetFiles or sequence<ShareTargetFiles>) files;
};

dictionary ShareTarget {
  required USVString action;
  DOMString method = "GET";
  DOMString enctype = "application/x-www-form-urlencoded";
  required ShareTargetParams params;
};

partial dictionary WebAppManifest {
  ShareTarget share_target;
};
```

The `files` property is in the [Level 2](https://wicg.github.io/web-share-target/level-2/) spec.

### PR DESCRIPTION
**Pull request by NotWoods**
---

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- [ ] **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- [ ] **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Comment by Amejia481** [comment]
Could we add some additional tests to the uncovered sections? :)  https://codecov.io/gh/mozilla-mobile/android-components/pull/4649/diff

**Comment by NotWoods** [comment]
bors r=Amejia481

**Comment by NotWoods** [comment]
bors retry

**Comment by NotWoods** [comment]
bors retry

**Pull request merged**
