### PR TITLE
Closes #8867: Correctly handle PageAction enabled state

### LINKED ISSUE #8867: PageActions should not be enabled by default
We have a leftover in `GeckoWebExtension` that enables page actions by default causing: https://github.com/mozilla-mobile/fenix/issues/15544

From the docs:
`While browser actions are displayed by default, page actions are hidden by default. They can be shown for a particular tab by calling pageAction.show()`

Bug is here on the global (session-independent) action handler:
https://github.com/mozilla-mobile/android-components/blob/master/components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/webextension/GeckoWebExtension.kt#L187

### PR DESCRIPTION
**Pull request by csadilek**
We had two problems here:

- Leftover logic that enabled all page actions by default
- We didn't correctly handle the page action enabled state. Unlike browser actions, page actions should be hidden if not enabled: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/page_action

This is the cause of https://github.com/mozilla-mobile/fenix/issues/15544.

### CODE REVIEW

**Review by Amejia481 — APPROVED** [review]
Great job!
Tested locally and worked like a charm!
We could add a change log entry apart, from that 🚢 it!

**Comment by dessant** [comment]
Would it be possible to uplift this into Firefox 83?

**Comment by csadilek** [comment]
@dessant yes, we did. Next 83 build will have the fix.

**Comment by dessant** [comment]
That's awesome, thanks a lot!

**Pull request merged**
