### PR TITLE
Closes #450: Fetch libjnidispatch at build-time and remove from tree.

### LINKED ISSUE #450: Fetch libjnidispatch at build-time and remove from tree
We are currently checking in libjnidispatch because I couldn't find it anywhere...seems we should version and publish it?

### PR DESCRIPTION
**Pull request by csadilek**
Alright, that's kinda cool that this works. 💥 

The android libjnidispatch.so files are not part of the published jna.jar, but luckily there are tagged releases of the distribution on GitHub. So, fetching those instead, unzipping and putting in the right folder.

Also, I tested that this all this works :).

### CODE REVIEW

**Comment by csadilek** [comment]
We should refactor this into a separate module, when we bring in additional libraries that use JNA...

**Comment by ncalexan** [comment]
> /cc @ncalexan This landed now. I plan to refactor this to a generic android-jna module which other android components (that use Rust) can then depend on.

Oh, nice -- I will steal this.  There's at least one Android JNA module around -- that's where @thomcc grabbed the libraries from to begin with, IIUC.  @thomcc?

**Comment by thomcc** [comment]
Nope, I grabbed them from https://github.com/mozilla/mentat/tree/master/sdks/android/Mentat/library/src/main/jniLibs, not sure where I'd find them otherwise.

**Pull request merged**
