### PR TITLE
Fix bookmarks crash

### PR DESCRIPTION
**Pull request by skhamis**
Fixes [#1433](https://github.com/mozilla-mobile/fenix/issues/14331)

### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/main/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/main/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Review by Amejia481 — CHANGES_REQUESTED** [review]
Thanks for the patch, could we add some tests to validate that we don't regress again?

**Comment by Amejia481** [comment]
Normally, we squash changes into a single commit. This helps to manage all the related changes/features as whole :)

**Comment by skhamis** [comment]
Thanks for the feedback @Amejia481! I have added a test, and squashed my commits (previously I relief on mergify doing it's magic) -- let me know if there is anything else missing!

**Review by mhammond — CHANGES_REQUESTED** [review]
As @skhamis and I discussed, this isn't the correct approach - but I'll let him close it!

**Comment by skhamis** [comment]
Mark is correct in that we should fix this in both a-s and fenix
For the crashing on navigating to a URL
- https://github.com/mozilla/application-services/pull/4793

And for crashing when adding a invalid url as a bookmark
- https://github.com/mozilla-mobile/fenix/pull/23390

As such, closing this

**Comment by Amejia481** [comment]
No problem, thanks for quickly addressing the bug.

**Pull request closed without merging**
