### PR TITLE
Update androidx.lifecycle to 2.4.0

### PR DESCRIPTION
**Pull request by MatthewTighe**
A matching upgrade is opened for Fenix in [this PR](https://github.com/mozilla-mobile/fenix/pull/22944)

### CODE REVIEW

**Comment by pocmo** [comment]
Looks like something went wrong on taskcluster. Let's rerun this.

**Comment by MatthewTighe** [comment]
Ah, looks like there was some deprecated usages that weren't caught when I ran tests locally. Interesting that the warning causes compilation errors with app builds but not test builds. I've updated the usages that were causing the issue

**Review by csadilek — COMMENTED** [review]
Thanks for working through the update. Since we're at the end of the 97 Nightly cycle, let's please merge this next Tuesday after we cut the new release branch.

**Comment by MatthewTighe** [comment]
We no longer need this dependency update in Fenix. Should we punt on this until needed, or go ahead and merge in both repos since the work is done?

**Comment by csadilek** [comment]
@MatthewTighe I think we can go ahead an upgrade in both repos. We currently run into this with an A-C upgrade in Fenix too and trying to figure out how the new lifecycle 2.4.0 came in there. So might need it sooner.

**Review by csadilek — APPROVED** [review]

**Comment by jonalmeida** [comment]
bors try

**Pull request merged**
