### PR TITLE
Closes #11365: Address breaking changes on GV 96.0.20211204095400

### LINKED ISSUE #11365: Address breaking changes on GV 96.0.20211204095400
```
[task 2021-12-06T12:44:32.558Z] e: /builds/worker/checkouts/src/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/TrackingProtectionExceptionFileStorage.kt: (199, 55): Unresolved reference: ContentBlockingException
[task 2021-12-06T12:44:32.558Z] e: /builds/worker/checkouts/src/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/TrackingProtectionExceptionFileStorage.kt: (201, 59): Unresolved reference: restoreExceptionList

```

### PR DESCRIPTION
**Pull request by Amejia481**
### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/main/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/main/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Review by pocmo — APPROVED** [review]
👍 

Are there any downsides for Focus users that upgrade from an older version?

**Comment by pocmo** [comment]
I'll cherry-pick this onto the new 96 branch, to unblock releasing with our first GeckoView 96 Beta.

**Comment by Amejia481** [comment]
> Are there any downsides for Focus users that upgrade from an older version?

I think users shouldn't have any issues :)

As this is a different migration from the one that we are doing on Focus.

Focus was relying on its **own stored exceptions** (shared preference based) that we are migrating to the actual **gecko permission storage API**.

The migration code that we are deleting was meant to migrate **tracking protection exceptions that were store directly on AC** to **gecko permissions storage API**.

That reminds me that I have to rename `TrackingProtectionExceptionFileStorage` 😄  as it's not based on file anymore XD

**Comment by Amejia481** [comment]
> I'll cherry-pick this onto the new 96 branch, to unblock releasing with our first GeckoView 96 Beta.

👍🏽

**Pull request merged**
