### PR TITLE
For #8515: Fix setIncludePending deprecation in SDK 30.

### PR DESCRIPTION
**Pull request by mcarare**
### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Review by Amejia481 — COMMENTED** [review]
So far looks good 👍🏽 !
Could we create a test to verify both scenarios ? :)

**Comment by mcarare** [comment]
@Amejia481 I could extract the `queryCollection` setting into a method and test that method, but I cannot verify the return value, because I cannot call `MediaStore.setIncludePending` below SDK 29, and robolectric uses 28 for the moment.

**Comment by Amejia481** [comment]
Thanks for the clarification, I will do a manual test just to verify that everything work as expected, but so far looks great, thanks for the patch!

**Review by Amejia481 — APPROVED** [review]
🚢 !

**Pull request merged**
