### PR TITLE
Remove photobucket.com from domains

### PR DESCRIPTION
**Pull request by cassidyjames**
The site never loads.

### Quality

Unsure how to test this, but it's a one-line change to a list of domains.

### Tests

Includes a one-line change to the list of domains. I'm not sure if that would affect any tests.

### Changelog

If this is notable enough for a changelog, where would I provide that information?

### Accessibility

Does not include any user-facing features.

### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes a changelog entry or does not need one
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### CODE REVIEW

**Comment by cassidyjames** [comment]
@pocmo could you please detail why this PR is considered blocked?

**Comment by pocmo** [comment]
@cassidyjames Your changes look absolutely reasonable. The only reason why I marked them as "blocked" is because we have a strict process for those domain lists:
https://firefox-source-docs.mozilla.org/mobile/android/fennec/defaultdomains.html

The only thing I want to do here is to request an additional review before merging the changes. :)

**Comment by cassidyjames** [comment]
@pocmo understood, thanks for the reply!

**Comment by jonalmeida** [comment]
screen shot 2019-02-25 at 5 00 34 pm

This seems to load just fine for me. Is this the only reason for the removal?

**Comment by cassidyjames** [comment]
@jonalmeida it seems it was down the few times I checked the other day (both on my connection and downforeveryoneorjustme.com). Looks like it's back. I wasn't aware if it had shut down or was just a bad outage. Seeing as how it looks like it was just an outage, we can probably just close this.

**Pull request closed without merging**
