### PR TITLE
For #9840: Add a compound toolbar item menu.

### PR DESCRIPTION
**Pull request by mcarare**
### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Comment by mcarare** [comment]
I had multiple options to implement this: [bookmarks toolbar](https://user-images.githubusercontent.com/43795363/106789941-8285ff00-6618-11eb-938c-0fe0e61d806d.png).

 a) I could have used the existing `BrowserMenuItemToolbar` with some changes: 
- option 1: Use `Button`. `bind` with either an `AppCompatButton` or a `MaterialButton` instead of `ImageView`. 
    Using `MaterialButton` would be a breaking change as all clients would have to have their base theme extend a `MaterialComponents` theme. Other than that, it would require some tweaking of icons and text, padding, etc. 
    Using `AppCompatButton` has some problems with theming and placing the compound drawable. 
    Either option would also require changing  `BrowserMenuItemToolbar` or extending it to have a different layout and/or placement inside it. 
 - option 2: Create a `BaseButton` class as a parent of `Button` to implement labeled variants of the button, as the current ones only have icons, not text. It would mean a massive refactoring, including the Menu candidates. 

b) Create an item similar to `BrowserMenuItemToolbar` with buttons just for text,  hierarchically independent from the `Button` class in `BrowserMenuItemToolbar`, partially duplicating functionality.

c) Extend `BrowserMenuCompoundButton`. However, IMO it differs so much in functionality, behavior, and appearance that I do not see it as a candidate for extending to obtain the desired toolbar. 

The above solutions would add some complexity to the code but it would help if we need to create different toolbar-like items in the future (do we need this though?)

The present draft is a targeted solution for the specific implementation of the requested feature but it has less extensibility.
 Other than that, I was wondering if we still need to support the `MenuCandidate` functionality so should I implement `asCandidate` or not. 

I would appreciate some input on these options (or others). Also, other naming proposals are welcomed 😄 . Thank you!

**Comment by jonalmeida** [comment]
I'd suggest the path with minimal effort because we have [`browser-menu2`](https://github.com/mozilla-mobile/android-components/tree/master/components/browser/menu2) that we want to migrate to eventually so might not be worth larger refactoring to `browser-menu`.

It would be nice if we could start using it today, but I'm not sure what that effort would look like with the current 3-dot menu refactoring.

**Comment by mcarare** [comment]
@jonalmeida Should I implement `asCandidate` for the new item and add a new `MenuCandidate`?

**Comment by jonalmeida** [comment]
> @jonalmeida Should I implement `asCandidate` for the new item and add a new `MenuCandidate`?

If it's not too much extra work, that would be great!

**Comment by mcarare** [comment]
Due to the design changes, closing this in favor of https://github.com/mozilla-mobile/android-components/pull/9943.

**Pull request closed without merging**
