### PR TITLE
For #9638: name various threads

### PR DESCRIPTION
**Pull request by mcomella**
See commit summaries for a few more details.

### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Review by csadilek — APPROVED** [review]
👍 

Somewhat related: One thing I was curious of is if we could shut down some of those executor services e.g. the `Nimbus` ones as they only seem to be used once during startup....needs more discussion but this will definitely help!

**Comment by mcomella** [comment]
> 👍
> 
> Somewhat related: One thing I was curious of is if we could shut down some of those executor services e.g. the `Nimbus` ones as they only seem to be used once during startup....needs more discussion but this will definitely help!

@csadilek I had planned to ask you about something related in triage. It seems we create single threaded Executors to guarantee serial execution of tasks but we could save resources by re-using existing thread pools and using other constructs to guarantee serial execution (Channels?). Let's discuss then.

**Comment by mcomella** [comment]
Rebasing due to conflicts with docs/changelog...

**Comment by csadilek** [comment]
> @csadilek I had planned to ask you about something related in triage. It seems we create single threaded Executors to guarantee serial execution of tasks but we could save resources by re-using existing thread pools and using other constructs to guarantee serial execution (Channels?). Let's discuss then.

@mcomella yes, I also filed https://github.com/mozilla-mobile/android-components/issues/9424 recently to investigate.

**Pull request merged**
