### PR TITLE
Bug 1721675 - Use the local server for testing

### PR DESCRIPTION
**Pull request by badboy**
We don't actually need to send pings, so we don't bother setting up a server.
However that results in Glean being put into test mode, ensuring
internal assertions that assume test mode don't trigger.

---

I currently can't run the tests myself. Is there a way to trigger them for the PR, @pocmo?
If not I can fix my local setup next week.

### CODE REVIEW

**Comment by badboy** [comment]
Locally it worked for me now:

```
❯ ./gradlew samples-glean:connectedAndroidTest
Local configuration: loaded local.properties
Disabled auto-publication of application-services. Enable it by settings 'autoPublish.application-services.dir' in local.properties
Local configuration: glean substitution path missing. You may specify it via 'substitutions.glean.dir' setting.
Configuration on demand is an incubating feature.

> Configure project :samples-glean
Requires glean_parser==3.4.0

> Configure project :samples-glean-library
Requires glean_parser==3.4.0

> Task :samples-glean:connectedDebugAndroidTest
Starting 2 tests on Pixel_3a_API_30_x86(AVD) - 11

BUILD SUCCESSFUL in 11s
387 actionable tasks: 3 executed, 4 from cache, 380 up-to-date
```

**Review by travis79 — APPROVED** [review]
LGTM!

**Review by pocmo — APPROVED** [review]

**Comment by pocmo** [comment]
> I currently can't run the tests myself. Is there a way to trigger them for the PR, @pocmo?

- Using the try command of bors. But I am not sure if that is still working, I will try in a separate comment.
- Pushing to a branch in this repository (as opposed to a fork)

**Comment by pocmo** [comment]
bors try

**Comment by pocmo** [comment]
https://firefox-ci-tc.services.mozilla.com/tasks/GNzhS2g4TdqiCVMuUEL5fw

**Pull request merged**
