### PR TITLE
Closes #291 - Unified lint warnings as error and fail on error

### LINKED ISSUE #291: Android lint issues do not break the build
Just saw that in the logs:

```
Ran lint on variant debug: 2 issues found
Wrote HTML report to file:///build/android-components/samples/browser/build/reports/lint-results.html
Wrote XML report to file:///build/android-components/samples/browser/build/reports/lint-results.xml
:samples-toolbar:lint
Ran lint on variant debug: 12 issues found
Ran lint on variant release: 12 issues found
Wrote HTML report to file:///build/android-components/samples/toolbar/build/reports/lint-results.html
Wrote XML report to file:///build/android-components/samples/toolbar/build/reports/lint-results.xml
```

### PR DESCRIPTION
**Pull request by CaptnBlubber**
This enables lint for all current and upcoming modules. 
Currently the automation should fail as the actual lint failures were not touched. Looking into that now

### CODE REVIEW

**Comment by pocmo** [comment]
Nice! Thank you so far.. :)

**Comment by CaptnBlubber** [comment]
I just fixed the remaining Lint errors.

I was a bit unsure about 'ui-autocomplete' where I ignored the missing `onClick` event.

**Comment by pocmo** [comment]
Travis failed for an unrelated resolver issue (Thanks jcenter). Just re-triggered it.

**Comment by pocmo** [comment]
Just wanted to merge this in and noticed that there are three issues in the new sample that merged Friday:

```
  The first 3 errors (out of 6) were:
  /build/android-components/samples/fxa/src/main/AndroidManifest.xml:32: Error: <uses-permission> tag appears after <application> tag [ManifestOrder]
      <uses-permission android:name="android.permission.INTERNET" />
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  /build/android-components/samples/fxa/src/main/AndroidManifest.xml:8: Error: On SDK version 23 and up, your app data will be automatically backed up and restored on app install. Consider adding the attribute android:fullBackupContent to specify an @xml resource which configures which files to backup. More info: https://developer.android.com/training/backup/autosyncapi.html [AllowBackup]
      <application
      ^
  /build/android-components/samples/fxa/src/main/res/values/ic_launcher_background.xml:6: Error: The resource R.color.ic_launcher_background appears to be unused [UnusedResources]
      <color name="ic_launcher_background">#45A1FF</color>
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by csadilek** [comment]
Open a PR for the issues introduced by the new sample (my mistake): https://github.com/mozilla-mobile/android-components/pull/360

**Comment by pocmo** [comment]
Thank you @CaptnBlubber :)

**Pull request merged**
