### PR TITLE
For #9382: Disable task optimization for pushes to 'master'

### PR DESCRIPTION
**Pull request by grigoryk**
See https://github.com/mozilla-mobile/android-components/issues/9382#issuecomment-760506327 for context. In summary, we'd like to run _every_ task whenever a push to master happens. This will get us complete test coverage reports.

@bhearsum I'm not familiar with this code. At first glance, this seems correct?

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Comment by escapewindow** [comment]
This looks right, but I'll leave it to @bhearsum since he knows best :)

**Review by bhearsum — APPROVED** [review]
For posterity, I want to note that this somewhat regresses the cost optimizations done in #7598. This seems like a good reason to change it on master though, and it's ultimately up to you anyways :).

**Comment by grigoryk** [comment]
> For posterity, I want to note that this somewhat regresses the cost optimizations done in #7598. This seems like a good reason to change it on master though, and it's ultimately up to you anyways :).

Do ya'll monitor duration of a-c CI jobs? I wonder if we'll notice a regression in either stability or duration.

For Fenix, I've put together [this CI dashboard](https://sql.telemetry.mozilla.org/dashboard/fenix-ci-status?p_w57980_time_period=3&p_w57980_with_tasks=OR%20job_type.symbol%20%3D%20%27gradle-dependencies%27%20OR%20job_type.symbol%20%3D%20%27ui-test-x86%27&p_w57985_time_period=3&p_w57985_with_ui_tests=OR%20job_type.symbol%20%3D%20%27gradle-dependencies%27%20OR%20job_type.symbol%20%3D%20%27ui-test-x86%27&p_w57988_time_period=3&p_w57988_with_tasks=OR%20job_type.symbol%20%3D%20%27ui-test-x86%27&p_w57990_time_period=3&p_w57990_with_tasks=OR%20job_type.symbol%20%3D%20%27gradle-dependencies%27%20OR%20job_type.symbol%20%3D%20%27ui-test-x86%27&p_w57991_time_period=3&p_w57991_with_tasks=OR%20job_type.symbol%20%3D%20%27ui-test-x86%27&p_w58003_task=T&p_w58003_time_period=3&p_w58004_task=ui-test-x86&p_w58004_time_period=3&p_w58006_task=gradle-dependencies&p_w58006_time_period=3&p_w58007_task=Bat&p_w58007_time_period=3&refresh=43200) a while back - it'll be nice to have one for A-C, as well :)

**Comment by bhearsum** [comment]
> > For posterity, I want to note that this somewhat regresses the cost optimizations done in #7598. This seems like a good reason to change it on master though, and it's ultimately up to you anyways :).
> 
> Do ya'll monitor duration of a-c CI jobs? I wonder if we'll notice a regression in either stability or duration.
> 
> For Fenix, I've put together [this CI dashboard](https://sql.telemetry.mozilla.org/dashboard/fenix-ci-status?p_w57980_time_period=3&p_w57980_with_tasks=OR%20job_type.symbol%20%3D%20%27gradle-dependencies%27%20OR%20job_type.symbol%20%3D%20%27ui-test-x86%27&p_w57985_time_period=3&p_w57985_with_ui_tests=OR%20job_type.symbol%20%3D%20%27gradle-dependencies%27%20OR%20job_type.symbol%20%3D%20%27ui-test-x86%27&p_w57988_time_period=3&p_w57988_with_tasks=OR%20job_type.symbol%20%3D%20%27ui-test-x86%27&p_w57990_time_period=3&p_w57990_with_tasks=OR%20job_type.symbol%20%3D%20%27gradle-dependencies%27%20OR%20job_type.symbol%20%3D%20%27ui-test-x86%27&p_w57991_time_period=3&p_w57991_with_tasks=OR%20job_type.symbol%20%3D%20%27ui-test-x86%27&p_w58003_task=T&p_w58003_time_period=3&p_w58004_task=ui-test-x86&p_w58004_time_period=3&p_w58006_task=gradle-dependencies&p_w58006_time_period=3&p_w58007_task=Bat&p_w58007_time_period=3&refresh=43200) a while back - it'll be nice to have one for A-C, as well :)

At this point, not really. We do have some alerts for large changes in cost week over week, but nothing specific for a-c.

**Pull request merged**
