### PR TITLE
Close #11017: Update lastAccess for Collection extensions

### LINKED ISSUE #11017: Update lastAccess when tabs are restored
When a tab is restored, we should update our `lastAccess` to be at the point of restoration.

This is for mozilla-mobile/fenix#20900 but the outcome also seems reasonable for other uses of `TabsUseCases.RestoreUseCase`.

### PR DESCRIPTION
**Pull request by jonalmeida**
Taking another route from https://github.com/mozilla-mobile/android-components/pull/11018, we could solve this problem by providing the caller with the list of successfully restored tabs in the helper extension.

The caller in the app can then choose how to handle the result. In the Fenix case, we would then invoke `browserStore.dispatch(LastAccessAction.UpdateLastAccessAction(it.id))` for each tab in the callback.

This would also make the extension consistent with the other that provides a callback with the `tabId` when it is done restoring.

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/main/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/main/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Review by csadilek — COMMENTED** [review]
Yes, this would work! However, I think we should add an additional `UseCase`. I don't quite like that the app has to use `browserStore.dispatch`. We usually hide those state updates in use cases, so would be nice to add another one.

So you could have this change here with the lambda, and `onTabsRestored` the app calls `TabsUseCases.UpdateLastAccessUseCase(tabs)` for example.

**Comment by jonalmeida** [comment]
> So you could have this change here with the lambda, and `onTabsRestored` the app calls `TabsUseCases.UpdateLastAccessUseCase(tabs)` for example.

That sounds fair to me. Updated. 🙂

**Review by csadilek — APPROVED** [review]
👍 

We can also uplift to release/94.0, so will need to coordinate landing the corresponding change in Fenix.

**Comment by jonalmeida** [comment]
> > The caller in the app can then choose how to handle the result. In the Fenix case, we would then invoke browserStore.dispatch(LastAccessAction.UpdateLastAccessAction(it.id)) for each tab in the callback.
> 
> This seems like a big downside though. How does a caller know when to do it? It seems like this is easy to miss - and something we would have to do in every app. 🤔

That's a fair point. I think our options came down to, how do we get notified of an action that is _only_ related to collections being restored, and a suggestion that Christian hinted at offline was to have a separate action that we dispatch when collections are restoring which sounds great, but I wasn't sure where that could live today without introducing more overhead. I'm happy to re-visit this again and do it better (in 95).

> 👍
> 
> We can also uplift to release/94.0, so will need to coordinate landing the corresponding change in Fenix.

The Fenix change would also need to be uplifted once it lands there too.

**Comment by jonalmeida** [comment]
> This seems like a big downside though. How does a caller know when to do it? It seems like this is easy to miss - and something we would have to do in every app. 🤔

Sorry, Christian explained your comment to me offline. I am a dumdum. 

Updating to include a flag to our TabsUseCase extension to fire the UpdateLastAccess action instead.

**Pull request merged**
