### PR TITLE
Closes #3857: Use `hasUserGesture` to determine if Content is Triggered by User

### LINKED ISSUE #3857: Android Intents URLs shouldn't start without user's gesture
*Background:*
With the implementation of android intents now it is possible to launch apps from a webpage.
See https://github.com/mozilla-mobile/android-components/issues/1132 and  https://developer.chrome.com/multidevice/android/intents for the background on it.
As Chrome's documentation says browser shouldn't launch an external app in the following cases:
  * When the Intent URI is redirected from a typed in URL.
  * When the Intent URI is initiated without a user gesture.

*Problem:*
Currently, it is possible to launch an external app through the intent without a user gesture through the usage of iframes.

*To reproduce:*
create a  page  with the following content:

```html
<html>
<head>
  <title>Android Intents URLs test</title>
</head>
<body>
  <iframe src="intent://mozilla.org#Intent;scheme=https;package=org.mozilla.firefox;action=android.intent.action.VIEW;end" style="display: none;"></iframe>
</body>
</html>
```
Open it in Firefox Mobile it will automatically open a new page https://mozilla.org

*Expected result:* Nothing happens.

Chrome implements it correctly. I didn't dig into the code logic, but we seem have something related to user gesture here: https://github.com/mozilla-mobile/android-components/blob/53fb640ccfc0ca9070bd4951f3adb204828935c7/components/browser/engine-system/src/main/java/mozilla/components/browser/engine/system/SystemEngineView.kt#L250

Here is a  PR where these changes were introduced first: https://github.com/mozilla-mobile/android-components/pull/3058/commits/5ae7c1551b1ed550f67ab39a690a862827384dff#

### PR DESCRIPTION
**Pull request by rocketsroger**
---

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- [ ] **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- [ ] **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Comment by rocketsroger** [comment]
> The change looks great to me. Have you tested this a bit in the browser to see if it is working as expected?
Yes, I tested in both sample browser and Fenix to confirm that it is working as expected.  It does change the behaviour in one case (microsoft team app) but I'm looking at another issue related to it and will make a change to fix it.
> I also wonder whether that will get uplifted to beta. Can you check the GV bug?
Currently its in GV v72.  We're not using that version in Beta.  Do you want me to update GV version in Beta?

**Comment by rocketsroger** [comment]
Opened https://github.com/mozilla-mobile/android-components/issues/5073 and https://github.com/mozilla-mobile/android-components/issues/5074 when GV is updated in beta and release

**Comment by pocmo** [comment]
> Currently its in GV v72. We're not using that version in Beta. Do you want me to update GV version in Beta?

In this case I mean the Gecko team making this functionality available in GeckoView 71.0 by uplifting the patch from 72.0 to 71.0. It's an option that we can ask for if we want to get something earlier - since Fenix Release is shipping with beta/71 and we would need to wait until 72 goes to beta otherwise. Anyhow, if this is something we think we need earlier in Fenix (if it fixes some critical bug) then we can ask for an uplift and they will look if that is feasible and what the risk is and then either do it or decide against it. :)

**Comment by rocketsroger** [comment]
> ...if this is something we think we need earlier in Fenix (if it fixes some critical bug) then we can ask for an uplift...

I see, sure I will request for uplift to 71.  Thanks,

**Pull request merged**
