### PR TITLE
For #11783 Improve Perceived Performance of Browser tab thumbnails

### PR DESCRIPTION
**Pull request by RotBolt**
### Pull Request checklist

- [X] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [X] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/main/docs/changelog.md) or does not need one
- [X] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/main/android/accessibility_guide.md) or does not include any user facing features

Closes #11784 
Closes https://github.com/mozilla-mobile/fenix/issues/21547

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Comment by RotBolt** [comment]
**Before Video**  : https://drive.google.com/file/d/11Yv59b1CNl9-lOrnGKpWiL2wKvQyY1cN/view?usp=sharing

**After Video** : https://drive.google.com/file/d/1nsdLEJTBCst4qFujra8Vtc_8ckv18O79/view?usp=sharing

**Comment by RotBolt** [comment]
Hello @jonalmeida could you have a look at this?

**Comment by RotBolt** [comment]
Hello @jonalmeida it's been quite while could you please look at this?

**Comment by mcomella** [comment]
@gabrielluong Do you have free cycles to review this change?

**Comment by mcomella** [comment]
Triage: @csadilek will find a reviewer

**Comment by RotBolt** [comment]
Thanks @jonalmeida on this

**Comment by RotBolt** [comment]
I will be moving on to next tickets

**Pull request merged**
