### PR TITLE
For #12151 - Add support for empty step value in TimePicker

### LINKED ISSUE #12151: Support step attribute in <input type="time"> etc
This is from https://github.com/mozilla-mobile/fenix/issues/25020

I expose `step` attribute by https://bugzilla.mozilla.org/show_bug.cgi?id=1499635, so android-component should handle it (`PromptDelegate.DateTimePrompt.stepValue`) to support step attribute in Date/Time picker.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20448)

### PR DESCRIPTION
**Pull request by Alexandru2909**
Fixes [Fenix #26943](https://github.com/mozilla-mobile/fenix/issues/26943).

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/main/docs/changelog.md) or does not need one
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/main/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### GitHub Automation
Fixes #12151

### CODE REVIEW

**Comment by rocketsroger** [comment]
Let's wait till the branch is cut before landing this.  Once this is soaked in Nightly and we see the crash is fixed, we can lift it to beta.  Thanks

**Review by Amejia481 — APPROVED** [review]
LGTM!
Let's try to add formatting only to the areas that has been changed, as adding formatting to files makes reviewing a bit hard, as it's not straightforward what have been changed 😄.

**Comment by Alexandru2909** [comment]
> Thanks for the patch, LGTM! Let's try to add formatting only to the areas that has been changed, as adding formatting to files makes reviewing a bit hard, as it's not straightforward what have been changed 😄.

I tried formatting only the lines I changed but for me `ktlint` fails locally for the whole file, so I think we need to add the formatting for both `GeckoPromptDelegateTest.kt` and `GeckoPromptDelegate.kt` in this PR. I separated the formatting in another commit so it's easier to follow and review.

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue on Fenix Nightly 107.0a1 and the issue no longer occurs. Seconds and milliseconds can be selected without crashing from the example provided here: https://github.com/mozilla-mobile/android-components/pull/12632.
### Device used:
- Samsung Galaxy S22 Ultra (Android 12)
- Huawei MediaPad M3 (Android 7)

**Comment by rocketsroger** [comment]
@Mergifyio backport releases_v106.0.0

**Comment by rocketsroger** [comment]
@Mergifyio backport releases/106.0

**Pull request merged**
