### PR TITLE
Remove LiveData.awaitValue

### PR DESCRIPTION
**Pull request by NotWoods**
This function is causing a lot of headache because it forces support-android-test to depend on LiveData, which causes issues with other components that depend on support-android-test. We're working on switching from LiveData to Flow everywhere, so this change switches all the components that use the `awaitValue` function.

---

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Comment by NotWoods** [comment]
`.asLiveData()` can be added to the function calls and that'll fix the breaking change. I'll set up a Fenix PR

**Comment by Amejia481** [comment]
@NotWoods awesome, please link it to this one!

**Comment by NotWoods** [comment]
https://github.com/mozilla-mobile/fenix/pull/11481

**Comment by NotWoods** [comment]
bors r=Amejia481

**Pull request merged**
