### PR TITLE
Add dummy multiplatform component.

### PR DESCRIPTION
**Pull request by pocmo**
This patch adds a dummy multiplatform component for testing purposes, with targets for Android and iOS.

### CODE REVIEW

**Review by escapewindow — APPROVED** [review]
Stamping for releng.

**Comment by pocmo** [comment]
@escapewindow In a future PR I may ask you how to publish this to maven. But not yet. :)

**Comment by escapewindow** [comment]
That may just happen automatically. We'll see?

**Comment by pocmo** [comment]
For now I have `publish: false` in .buildconfig. Locally I have some additional gradle code that sets up the publishing. But other than our other components this module creates multiple artifacts instead of just one. But yeah, let's see once I add the publish code to a PR... :)

**Pull request merged**
