### PR TITLE
Update version of GeckoView Nightly to 66.0.20190107093040.

### PR DESCRIPTION
**Pull request by pocmo**
Needed to update some things since the GV team added `@Nullable` and `@NonNull` annotations.

### CODE REVIEW

**Comment by pocmo** [comment]
Aye, needs some more work.

**Comment by pocmo** [comment]
Updated the PR and now everything (including tests) is covered.

@Amejia481 I have a problem with our implementation of `GeckoPromptDelegate.onChoicePrompt`. 

```Kotlin
                    onPromptRequest(SingleChoice(choices) { selectedChoice ->
                        val geckoChoice = mapChoicesToGeckoChoices[selectedChoice]
                        callback.confirm(geckoChoice!!)
                    })
```

`geckoChoice` can be nullable here. I added `!!` however the tests fail since it's actually `null` which doesn't seem to be expected.

**Comment by Amejia481** [comment]
@pocmo I will take a look!

**Comment by Amejia481** [comment]
@pocmo I updated the PR, the tests are fixed. If you need any additional help just let me know :)

As `org.mozilla.geckoview.GeckoSession.PromptDelegate.ChoiceCallback.confirm(@NonNull Choice item)` is non-null, the test should provide a non-null value, I  updated the test to reflect that. 

https://github.com/mozilla-mobile/android-components/blob/eed39b32c0973b5aab7f6f817202f867640e89ad/components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegateTest.kt#L74

https://github.com/mozilla-mobile/android-components/blob/eed39b32c0973b5aab7f6f817202f867640e89ad/components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegateTest.kt#L87


https://github.com/mozilla-mobile/android-components/blob/eed39b32c0973b5aab7f6f817202f867640e89ad/components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegateTest.kt#L159

https://github.com/mozilla-mobile/android-components/blob/eed39b32c0973b5aab7f6f817202f867640e89ad/components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegateTest.kt#L177

**Comment by pocmo** [comment]
@Amejia481 Perfect. Thanks! Maybe a review? :D

**Pull request merged**
