### PR TITLE
Closes #1862: Adds support for picture-in-picture mode

### LINKED ISSUE #1862: Move Picture-In-Picture feature to components
The feature currently lives in the [Reference Browser](https://github.com/mozilla-mobile/reference-browser/blob/master/app/src/main/java/org/mozilla/reference/browser/pip/PictureInPictureFeature.kt) but it's abstract enough that we can move it to an existing feature component.

Probably `feature-session` since that's where the `FullScreenFeature` resides as well (although maybe we want to move both to some better place?).

### PR DESCRIPTION
**Pull request by ArazAbishov**
### Pull Request checklist

- [X] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [X] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [X] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [X] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### CODE REVIEW

**Comment by ArazAbishov** [comment]
Should I resolve this conflicts myself or you guys will do it before merging?

**Comment by pocmo** [comment]
> Should I resolve this conflicts myself or you guys will do it before merging?

Yeah, that would be helpful if you could rebase and resolve that conflict and update the PR. :)

**Comment by ArazAbishov** [comment]
@pocmo done :)

**Comment by pocmo** [comment]
Thank you!

https://github.com/mozilla-mobile/android-components/commit/b88794d117b389fb10f84c6520c0f5256533d7ae

**Pull request closed without merging**
