### PR TITLE
Update detekt and its configuration

### PR DESCRIPTION
**Pull request by BraisGabin**
As commented on https://github.com/mozilla-mobile/fenix/pull/23123 this PR cleans a bit the current config, sync it with the default config of detekt and then update detekt along with it's configuration.

The sync is a manual work but the update of the config is done using these scripts: https://github.com/detekt/detekt/discussions/3558#discussioncomment-483027 (It had conflicts so there was a manual component there too).

I recommend to review this PR commit by commit because the merge of all the changes is a mess but each commit does one and only one thing so it should be easier to follow.

---

The new version of detekt found some new issues of already enabled issues (I assume they were old false-negatives) So I added them to the baseline. For that reason before adding those to the baseline I updated it.

### CODE REVIEW

**Comment by BraisGabin** [comment]
I have no idea what's wrong here. I can't see any log with the errors that CI found.

**Comment by gabrielluong** [comment]
@BraisGabin Just for my own reference when reviewing and comparing the changes to detek.yml. Can I assuming you are adding the missing defaults that are seen in https://github.com/detekt/detekt/blob/main/detekt-core/src/main/resources/default-detekt-config.yml?

**Comment by BraisGabin** [comment]
Yes, that's exactly what I did.

**Comment by gabrielluong** [comment]
Sorry for the ongoing delay on the review, will try to get to this soon!

**Comment by BraisGabin** [comment]
Is there something I can do to help you reviewing this PR? I know it's big.

**Comment by gabrielluong** [comment]
@BraisGabin I am so sorry for the delay. Other priorities took me hostage and kept me from investing the needed time to look at this thoroughly. I went through comparing your work, all our prior changes and the original config with the latest defaults and add some changes to try to align as closely with the defaults as possible. I made 2 minor changes in https://github.com/mozilla-mobile/android-components/pull/11867 (which is where I will try to land this) to try to align as much as possible to the base defaults available. I don't think this would've gone as smoothly without your contribution and help. So thank you!

**Pull request closed without merging**
