### PR TITLE
Closes #6149: Notify push observers for onSubscriptionChange events

### LINKED ISSUE #6149: Notify observers on subscription changes from new API
When the changes for a-s land and release, we can consume the new breaking API changes.

See: https://github.com/mozilla/application-services/issues/2049

### PR DESCRIPTION
**Pull request by jonalmeida**
Incorporates the breaking API changes that will come out in the next release of a-s - cannot be merged until then.

---

Closes #6149

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- [ ] **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- [ ] **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Comment by jonalmeida** [comment]
We have a new a-s build and I've done a simple smoke test with it in Fenix: sign in/out, send tab, verify history syncs.

cc: @grigoryk

**Comment by jonalmeida** [comment]
Blocking again so we can get bump this up with the next a-s release that is more urgently needed.

**Comment by jonalmeida** [comment]
Or maybe not..

**Comment by jonalmeida** [comment]
bors=pocmo

**Comment by pocmo** [comment]
> bors=pocmo

I am not bors :P

**Comment by jonalmeida** [comment]
bors r=pocmo

**Pull request merged**
