### PR TITLE
Closes #2262: Rename Response.X to isX..

### LINKED ISSUE #2262: :concept-fetch Response.success & .clientError breaks Java naming conventions
Conventionally, `.success` would be `.isSuccess` and `.clientError` would be `.isClientError`. Because of the non-standard naming conventions, I found it difficult to find these methods.

### PR DESCRIPTION
**Pull request by mcomella**
This follows Java naming conventions.

**N.B.:** this is a breaking change so we may not want to make it.

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
  - No additional tests: no behavior changes
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### CODE REVIEW

**Comment by pocmo** [comment]
@mcomella Since this is a breaking change.. can you mention this in the changelog?

**Comment by mcomella** [comment]
> @mcomella Since this is a breaking change.. can you mention this in the changelog?

Done.

**Comment by mcomella** [comment]
FYI: I had to rebase this on:
- Changes to the changelog
- My PR which added PocketEndpointRaw, which used `Response.success`

**Comment by pocmo** [comment]
`HttpPingUploader` was something we refactored to use `concept-fetch` recently. Seems like this will need an update too. If I get to that today I'll add a follow-up commit to this PR and push it.

> e: /build/android-components/components/service/glean/src/main/java/mozilla/components/service/glean/net/HttpPingUploader.kt: (12, 41): Unresolved reference: clientError
> e: /build/android-components/components/service/glean/src/main/java/mozilla/components/service/glean/net/HttpPingUploader.kt: (13, 41): Unresolved reference: success
> e: /build/android-components/components/service/glean/src/main/java/mozilla/components/service/glean/net/HttpPingUploader.kt: (105, 26): Unresolved reference: success
> e: /build/android-components/components/service/glean/src/main/java/mozilla/components/service/glean/net/HttpPingUploader.kt: (114, 26): Unresolved reference: clientError

**Comment by pocmo** [comment]
Added a commit for that. But today we merged `service-experiments` and this one needs an update now too :)

**Comment by mcomella** [comment]
> Added a commit for that. But today we merged `service-experiments` and this one needs an update now too :)

Done. Back to you! 🏀

**Comment by pocmo** [comment]
Awesome, thanks! Looks like we ran into the `ConcurrentModificationException` issue (#2297). I'll re-trigger.

**Comment by pocmo** [comment]
And green. Now let's merge that quickly :D

**Pull request merged**
