### PR TITLE
Closes #5573: Remove isAutoInitEnabled from AbstractFirebasePushService

### LINKED ISSUE #5573: Remove isAutoInitEnabled from AbstractFirebasePushService.stop
This fails because if we haven't started already because it's a fresh install, debug build, or non-Firebase supported app.

### PR DESCRIPTION
**Pull request by jonalmeida**
---

Removing auto-init for now until we can find a better way to add it and still make start/stop safe calls.

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- [ ] **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- [ ] **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Comment by grigoryk** [comment]
bors retry

**Comment by jonalmeida** [comment]
bors retry

**Comment by jonalmeida** [comment]
bors r+

None of these build failures are related.

**Comment by jonalmeida** [comment]
Good bot.

**Pull request merged**
