### PR TITLE
Close #9222: Revert un-subscribe on subscriptionExpired notification

### LINKED ISSUE #9222: Revert changes to unsubscribe when observing subscriptionExpired
[This patch](https://github.com/mozilla-mobile/android-components/pull/9013) ended up causing [more failures than expected](https://github.com/mozilla-services/autopush/issues/1445#issuecomment-736969390), so we're more keen to remove this until other fixes help resolve this (possibly https://github.com/mozilla/application-services/issues/3695?).

### PR DESCRIPTION
**Pull request by jonalmeida**
### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Review by grigoryk — APPROVED** [review]
Unfortunate that this is causing issues... Good signal that our underlying API surface isn't quite what it should be, I think.

**Comment by jonalmeida** [comment]
> Unfortunate that this is causing issues... Good signal that our underlying API surface isn't quite what it should be, I think.

We've definitely made some bugs in the wild more reproducible with this, so I think that's a win! Given the holiday season, it's safer to revert this until we can get more support to solving the root cause of the problem.

**Comment by jonalmeida** [comment]
@mergify backport releases/70.0

**Comment by jonalmeida** [comment]
> **Command `backport releases/70.0`: success**
> 
> > **Backports have been created**
> > 
> > * [#9253 Close #9222: Revert un-subscribe on subscriptionExpired notification (bp #9227)](https://github.com/mozilla-mobile/android-components/pull/9253) has been created for branch `releases/70.0`

Good bot.

> _Hey, I reacted but my real name is @Mergifyio_

Sorry, bot!

**Comment by pocmo** [comment]
4qp7sq

**Pull request merged**
