### PR TITLE
Treat no push subscription as though it had expired, and poll for mis…

### PR DESCRIPTION
**Pull request by mhammond**
…sed commands in both cases

This doesn't actually renew the subscription on startup for reasons outlined in https://github.com/mozilla-mobile/fenix/issues/16805#issuecomment-737667868. cc @jonalmeida @grigoryk

### CODE REVIEW

**Comment by jonalmeida** [comment]
Thanks @mhammond ! I think we need to fix the tests as well before landing.

Will peek at this in the morning.

**Review by jonalmeida — APPROVED** [review]
The push changes look good, but lets wait for @grigoryk to review it as well in case there are side-effects that we overlooked.

+ the missing unit tests.

**Comment by mhammond** [comment]
The [observer problem](https://github.com/mozilla-mobile/fenix/issues/16805#issuecomment-737667868) likely means this will actually cause a regression - now we might notify of missed commands before the observers are set up, which means they'd be missed entirely, whereas without this patch we'd check less often, but if we find missed commands they'd be actioned.

**Comment by mhammond** [comment]
> The [observer problem](https://github.com/mozilla-mobile/fenix/issues/16805#issuecomment-737667868) likely means this will actually cause a regression

The good news is that this isn't true - the observer which handles commands is not created by that state machine, but instead in the ctor of `SendTabFeature` - so these missed commands *are* going to be processed.

It's still true though that the state machinery/observer setup will prevent the subscription from being renewed - but at least the missed commands will appear after startup, so that's quite a win. Therefore I think we should land this once @grigoryk approves it.

(I had another poke at untangling the state machinery and failed - there's no obvious simple fix, and issues like #6879 and #8766 both imply some refactoring here makes sense for many reasons - so I don't plan on looking any further into this for now)

**Comment by jonalmeida** [comment]
Let's merge this for now since a beta is already cut and this can bake in Nightly for a while.

**Comment by mhammond** [comment]
After my Nightly updated I now see missed tabs come in as the browser opens - so this seems to be working as expected 🚀

**Pull request merged**
