### PR TITLE
Issue #10335: Use Java 11.

### PR DESCRIPTION
**Pull request by pocmo**
Alright, let's try this again. Everything was green and then suddenly some tests failed after it landed. Let's see how it behaves this time. Adding the "do not land" label to wait with landing.

### CODE REVIEW

**Comment by pocmo** [comment]
Ah, it passed, but we do not actually run all the things. I'll make it force building everything.

**Comment by pocmo** [comment]
Yay, it's finally green. Planning to land this next week when 92 starts.

**Comment by ahal** [comment]
This will have a conflict with [this change](https://github.com/mozilla-mobile/android-components/pull/10574/files#diff-4bc21af59ec632e7a245dae145a54599f1db3cb35d6aeebc28c57b1ffeffeaa8R16) in PR #10574 . Whoever lands last will need to remove that line.

Also noting there's a newer version of the [decision-mobile](https://hub.docker.com/layers/mozillareleases/taskgraph/decision-mobile-44b6b7b4c370220eff56efa8b508aa5157ef9c6e74847c7ecc19d640946ba49e/images/sha256-4107cbc5e154502529e4d38efa4dc89c05ee54e2cbc6e2e66023e68407502894?context=explore) image out (which the above PR updates to). So if you land last, make sure not to overwrite those changes. Alternatively it should be safe to update to the newer image here as well.

**Review by csadilek — APPROVED** [review]
⬆️ 🎬

**Pull request merged**
