### PR TITLE
 Docs update (20191206-120728) [ci skip]

### PR DESCRIPTION
**Pull request by MickeyMoz**

### CODE REVIEW

**Comment by jonalmeida** [comment]
Conflicts? 🤔 

@csadilek any ideas?

**Comment by csadilek** [comment]
> Conflicts? 🤔
> 
> @csadilek any ideas?

@jonalmeida Just double-checked that we didn't commit docs changes by mistake. Doesn't seem like it, but must have something to do with the rename. I will put up a PR to resolve.

**Comment by jonalmeida** [comment]
Will close this then since we can't edit it.

**Comment by csadilek** [comment]
> Will close this then since we can't edit it.

@jonalmeida ok, put up a new PR here: https://github.com/mozilla-mobile/android-components/pull/5251

**Pull request closed without merging**
