### PR TITLE
Fork "fretboard" and rename it to "experiments"

### PR DESCRIPTION
**Pull request by georgf**
This is the first step following the rebooted [Android experiments library spec](https://docs.google.com/document/d/1C1k68VHKEhl1fp2oA_kkn23NZxsaloIIAJiukVQKgf0/).

To not impact currently running or planned experiments using fretboard, we're forking it instead of renaming it in place.
This is building up to providing an experiments library for integration with the Fenix MVP in Q2, with the library owned by our team.

### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### CODE REVIEW

**Comment by georgf** [comment]
@pocmo I took my best shot on the build & code owner files etc., let me know what i missed.

Local tests are passing for me.

**Comment by pocmo** [comment]
This looks good to me. One tricky thing is that this is not on top of the current master (anymore). So it can't be rebased (because of the way its merged) and therefore would require another merge commit (which we try to avoid having).

**Comment by pocmo** [comment]
Mh, even merging this into the current master HEAD causes a conflict:

>  skaspari@morty /Projects/Mozilla/android-components   master  git merge georg/experiments
> CONFLICT (rename/add): Rename components/service/fretboard/README.md->components/service/experiments/README.md in HEAD. components/service/experiments/README.md added in georg/experiments
Adding as components/service/experiments/README.md-georg_experiments instead
> CONFLICT (rename/add): Rename components/service/fretboard/src/main/AndroidManifest.xml->components/service/experiments/src/main/AndroidManifest.xml in HEAD. components/service/experiments/src/main/AndroidManifest.xml added in georg/experiments
Adding as components/service/experiments/src/main/AndroidManifest.xml-georg_experiments instead
Auto-merging docs/changelog.md
Automatic merge failed; fix conflicts and then commit the result.

I wonder if we have to replay that move on top of master and then push directly.

**Comment by pocmo** [comment]
> Mh, even merging this into the current master HEAD causes a conflict:

Ah, my master wasn't clean. Now that is working.

**Pull request merged**
