### PR TITLE
 Closes #9261: Remove extra space when the permission_indicator is gone 

### LINKED ISSUE #9261: Remove extra space when the permission_indicator is gone
Related issue https://github.com/mozilla-mobile/fenix/issues/17042#issuecomment-746367323

### PR DESCRIPTION
**Pull request by Amejia481**
As we added the permission indicator, I didn't notice that the `OriginView` had a [layout_goneMarginStart](https://github.com/mozilla-mobile/android-components/blob/3320a792e13cce9dedb9f150cacd930b5f4ebea7/components/browser/toolbar/src/main/res/layout/mozac_browser_toolbar_displaytoolbar.xml#L108), intended to add some space between the `OriginView` and the security indicator when it's gone, as now the permission indicator it's in the position where the `OriginView` was we have to move the `goneMargin` to the permission indicator for when the security indicator is gone.

**With the fix**.
image
image

**Without the fix**.

image

image

### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Comment by Amejia481** [comment]
Additionally, I added this commit https://github.com/mozilla-mobile/android-components/pull/9262/commits/a636482e7866ce50c0da52f8196884fc4828691f, to reduce the space between the security indicator and the permission indicator in desktop they are also a bit closer.  

image


**With the fix**
image

image

**without the fix.**
image

image

**Review by pocmo — APPROVED** [review]
Does the reduced padding maybe look weird if the lock icon is not shown? But since no app uses that configuration, it's not super important right now. :)

**Comment by Amejia481** [comment]
> Does the reduced padding maybe look weird if the lock icon is not shown? But since no app uses that configuration, it's not super important right now. :)

Do you know any cases when the permission icon will be visible and the lock icon will be hidden?  :)
As now we only have it on nightly we can give it a try and gather user feedback.

**Comment by pocmo** [comment]
There's no such case in any of our shipping apps - we would need to add something like that to the sample toolbar app. I just mentioned it because it is a valid way to configure the toolbar currently.

**Comment by Amejia481** [comment]
I will give it a try, thanks!

**Comment by Amejia481** [comment]
If the lock icon is hidden `app:layout_goneMarginStart="8dp"` will add the reduced padding back :) 

image

image


If the permission icon is gone no extra padding will added 

image

image

**Pull request merged**
