### PR TITLE
Allow products to specify a custom path for Glean-generated docs

### PR DESCRIPTION
**Pull request by Dexterp37**
This is required by Fenix, since their docs are in `$rootDir/docs` not in `$projectDir/docs`

---

### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- [ ] **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- [ ] **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Comment by Dexterp37** [comment]
This is interesting: the parsers [always delete](https://github.com/mozilla/glean_parser/blob/04b63688266c553af67450d8c57de894997eeb90/glean_parser/translate.py#L57) the output directory. This makes sense for code, it might make less sense for docs as the target directory might contain other documentation. Question: should we add some option to the parsers in order to *not* clear the output directory? Or should we do some Gradle magic (which would need to hook up on the build script internals, probably..) in Fenix?

**Comment by pocmo** [comment]
Drive-by: Great change! Going forward I want to unify our documentation (READMEs + other .md files + website -> just website) and this will be helpful, I think. But yeah, we also wouldn't want to delete everything else. :)

**Comment by Dexterp37** [comment]
> 
> 
> Drive-by: Great change! Going forward I want to unify our documentation (READMEs + other .md files + website -> just website) and this will be helpful, I think. But yeah, we also wouldn't want to delete everything else. :)

Thank you! Your plan sounds great ;) Please, if you have any feature request for the docs that might help with that, feel free to file a bug for the Glean SDK ;)

**Comment by mdboom** [comment]
> Question: should we add some option to the parsers in order to not clear the output directory?

I think we should modify glean_parser to not do this for markdown (but continue to do it for Kotlin).  I wouldn't make a user option though.

**Comment by Dexterp37** [comment]
> 
> 
> > Question: should we add some option to the parsers in order to not clear the output directory?
> 
> I think we should modify glean_parser to not do this for markdown (but continue to do it for Kotlin). I wouldn't make a user option though.

Make sense to me. I'll proceed with that.

**Comment by Dexterp37** [comment]
Depends on mozilla/glean_parser#92

**Pull request merged**
