### PR TITLE
Use Java 11.

### PR DESCRIPTION
**Pull request by pocmo**
This is the first step towards getting Jetpack Compose support in this repository. Let's see what automation thinks about this.

### CODE REVIEW

**Comment by pocmo** [comment]
Okay, this exploded quickly. 👀

**Comment by pocmo** [comment]
```
[task 2021-05-26T09:57:02.574Z] mozilla.components.tooling.lint.LintLogChecksTest > report log error in components code only FAILED
[task 2021-05-26T09:57:02.574Z]     org.mockito.exceptions.base.MockitoException at LintLogChecksTest.kt:26
[task 2021-05-26T09:57:02.574Z]         Caused by: org.mockito.exceptions.base.MockitoException at LintLogChecksTest.kt:26
[task 2021-05-26T09:57:02.574Z]             Caused by: java.lang.IllegalStateException at LintLogChecksTest.kt:26
[task 2021-05-26T09:57:02.574Z]                 Caused by: java.lang.IllegalArgumentException at LintLogChecksTest.kt:26
```

**Comment by pocmo** [comment]
Ugh. A bunch of other test failures. 93 failures just in the gecko component.

**Comment by pocmo** [comment]
It's green.

There are 11 tests I had to add `@Ignore` to.

**Review by escapewindow — APPROVED** [review]
LGTM from a releng perspective.

**Comment by pocmo** [comment]
Locally everything still works with Java 8, so there's no need to switch locally just yet. I am going to land this.

**Pull request merged**
