### PR TITLE
Closes #54: Selectively enable kotlin warnings as errors

### LINKED ISSUE #54: Kotlin: treat warnings as errors
Kotlin 1.2 introduces a compiler flag to treat warnings as errors: https://kotlinlang.org/docs/reference/whatsnew12.html#warnings-as-errors

### LINKED ISSUE #716: kotlin-stdlib-jre7/8 is deprecated. Please use kotlin-stdlib-jdk7/8 instead
From the build log:

```
w: /Users/skaspari/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jre7/1.2.0/ec8b969e26fbcf2265a4d1a1539c4d1d4c5af380/kotlin-stdlib-jre7-1.2.0.jar: kotlin-stdlib-jre7 is deprecated. Please use kotlin-stdlib-jdk7 instead
w: /Users/skaspari/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jre8/1.2.0/505f55b9619bbc5f5e26c77427dd24a6a441eef1/kotlin-stdlib-jre8-1.2.0.jar: kotlin-stdlib-jre8 is deprecated. Please use kotlin-stdlib-jdk8 instead
```

I was expecting this to be gone since we switched to `kotlin-stdlib-jdk7` ... but it's still there?

### PR DESCRIPTION
**Pull request by mcomella**
See extended git commit summaries for details. Here is the list of warnings that are not being treated as errors: https://gist.github.com/mcomella/fabd14e3d42705f1049c3714d4396a29 See #2346 for a follow-up to enable warnings as errors on those modules.

This may close #716.

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### CODE REVIEW

**Comment by pocmo** [comment]
There's a lot of red on taskcluster 🤔

**Comment by mcomella** [comment]
I didn't compile the unit tests, some of which apparently have warnings
too. I guess I'll have to suppress those too.

**Comment by mcomella** [comment]
It looks like many of the test task compilations fail with:
- `RuntimeEnvironment.application` is deprecated (`ApplicationProvider` from androidx should be used instead)
- Something in coroutines API is experimental

I disabled their warnings as errors

**Comment by mcomella** [comment]
> There's a lot of red on taskcluster 🤔

It's green, I don't know what you're talking about.

**Comment by pocmo** [comment]
> It's green, I don't know what you're talking about.

jedi

**Comment by mcomella** [comment]
TC failures, seem unrelated:

> * What went wrong:
A problem occurred evaluating root project 'android-components'.
> Could not resolve all files for configuration ':feature-accounts:debugCompileClasspath'.
   > Could not download fxaclient.aar (org.mozilla.fxaclient:fxaclient:0.19.0)
      > Could not get resource 'https://jcenter.bintray.com/org/mozilla/fxaclient/fxaclient/0.19.0/fxaclient-0.19.0.aar'.
         > Connection reset

And glean has test failures but they're having intermittent test issues.

I think I need a rerun.

**Comment by pocmo** [comment]
Force-merging, since failure was unrelated and want to get this in before new warnings land.

**Comment by mcomella** [comment]
> Force-merging, since failure was unrelated and want to get this in before new warnings land.

🙇

**Pull request merged**
