### PR TITLE
Closes #1191: Use escaped apostrophe in CDATA strings [ci skip]

### LINKED ISSUE #1191: Apostrophe in the error pages renders incorrectly
From https://github.com/mozilla-mobile/focus-android/issues/3746

We need to change that from `’` to ~`&apos;`~ `&#8217;`.

### PR DESCRIPTION
**Pull request by jonalmeida**
In CDATA strings, you need to escape the apostrophe so that it renders
correctly. Currently, it shows some garbald text when the page is
rendered.

### CODE REVIEW

**Comment by jonalmeida** [comment]
@Pike it's causing a text rendering issue (linked issue): https://github.com/mozilla-mobile/focus-android/issues/3746

**Comment by Pike** [comment]
That's concerning. I think that implies that unicode doesn't work on that code path, and that's likely going to break localizations.

**Comment by jonalmeida** [comment]
@pocmo @Pike y'all were right. Changing the default encoding for the error page at the top level fixed this issue. Thanks! :)

**Comment by jonalmeida** [comment]
> Merging #1192 into master will decrease coverage by 0.01%.

**Pull request merged**
