### PR TITLE
Issue #8324: Delete the pinned site from the history when removing

### LINKED ISSUE #8324: Delete the pinned site from the history when removing
STR in Fenix:
1. Visit a site
2. Add visited site as a pinned site
3. Remove the pinned site
4. See the removed pinned site is also a frecent site so it remains in the list of top site

We should delete the pinned site from the history storage when removing it.

### PR DESCRIPTION
**Pull request by gabrielluong**
---

Fixes #8324.

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Review by jonalmeida — APPROVED** [review]
bors r+

Makes sense!

**Comment by jonalmeida** [comment]
@gabrielluong can't merge until `lint-detektAndKtlint` is fixed.

**Comment by liuche** [comment]
This will need an uplift into 57.0.2

**Comment by gabrielluong** [comment]
bors r=jonalmeida

**Comment by pocmo** [comment]
Uplifted to AC 57 branch.

**Pull request merged**
