### PR TITLE
WIP Sendtab tests

### PR DESCRIPTION
**Pull request by chartjes**
---

### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Comment by chartjes** [comment]
@eoger In this patch I am manually creating a Firefox account inside the tests and not sure what you mean by "live" tests. I am guessing there is some terminology I am not familiar with -- they run locally in Android Studio and do not require an actual browser.

**Comment by eoger** [comment]
@chartjes do you want to meet on Zoom to discuss what we want to do here and the approach we want to take?

**Comment by eoger** [comment]
Would you mind rebasing your patch? I'm seeing 1500 commits

**Comment by chartjes** [comment]
Hrm, I did rebase it. I will see if I can figure out a better approach.


-- 
 Chris Hartjes
chartjes@littlehart.net

**Pull request closed without merging**
