### PR TITLE
Closes #10126: Expose the new gecko API for controlling CookieBehaviorPrivateMode.

### LINKED ISSUE #10126: Expose new gecko API for controlling CookieBehaviorPrivateMode
Gecko just added some new APIs for `controllingCookieBehaviorPrivateMode`   [See](https://mozilla.github.io/geckoview/javadoc/mozilla-central/org/mozilla/geckoview/doc-files/CHANGELOG#v89). This is required for https://github.com/mozilla-mobile/fenix/issues/18627.

> ⚠️ Added setCookieBehaviorPrivateMode to control cookie behavior for private browsing mode independently of normal browsing mode. To maintain current behavior, set this to the same value as setCookieBehavior is set to.

### PR DESCRIPTION
**Pull request by Amejia481**
This will address this issue https://github.com/mozilla-mobile/focus-android/issues/4740, the same issue is also present in Fenix.

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Comment by Amejia481** [comment]
@pocmo Are you familiar with the `build-concept-engine` failures? It looks like the module hasn't run on CI in a along time, I run the same  module on master and the same test failures. It looks like I'm the first one modifying the module and for this reason they are running on CI now. Should I address those?

image

**Comment by pocmo** [comment]
> @pocmo Are you familiar with the `build-concept-engine` failures? It looks like the module hasn't run on CI in a along time, I run the same module on master and the same test failures.

It has been running and passing for all commits on `master` in automation though? 🤔 

> It looks like I'm the first one modifying the module and for this reason they are running on CI now.

This optimization only happens for PRs. They still run all on `master`.

> Should I address those? Or there is another PR address them?

I'll see if I can reproduce those.

**Review by pocmo — APPROVED** [review]
LGTM. 👍

**Comment by pocmo** [comment]
Like taskcluster, I only see 1 failure, and only on your branch: `EngineSessionTest. tracking protection policies have correct categories`

There seems to be something going wrong with your Android Studio. Do you see the same problems on the command line?

**Comment by Amejia481** [comment]
Thanks, it looks it's a local issue with my AS :(,  in the terminal is works correctly.

**Pull request merged**
