### PR TITLE
Updating Third Party Libs versions(Sentry: 1.7.14 and Okhttp: 3.12.0).

### PR DESCRIPTION
**Pull request by Amejia481**

### CODE REVIEW

**Comment by pocmo** [comment]
Since you added them to the changelog you'll need to update them there 🙃

**Comment by Amejia481** [comment]
🙃

**Comment by Amejia481** [comment]
This test is falling a lot in TC, but it doesn't fail in my environment
```
> Task :browser-session:testDebugUnitTest
mozilla.components.browser.session.storage.SessionStorageTest > AutoSave - when going to background FAILED
    org.mockito.exceptions.verification.WantedButNotInvoked at SessionStorageTest.kt:175

```

**Comment by pocmo** [comment]
Ah, I thought this one was fixed. Can you file an issue and re-run here?

**Comment by Amejia481** [comment]
Sure 👍

**Pull request merged**
