### PR TITLE
Upgrade Robolectric to version 4.2.1

### PR DESCRIPTION
**Pull request by Dexterp37**
---

### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- [ ] **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- [ ] **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Comment by pocmo** [comment]
Looks like some methods have been deprecated breaking the build on taskcluster.

**Comment by Dexterp37** [comment]
> 
> 
> Looks like some methods have been deprecated breaking the build on taskcluster.

Yeah, I was trying to fix these, but the activity ones are puzzling me a bit. I should use `ActivityScenario`, but it requires an activity. And, for example, in `engine-system` I'm not sure what to use.

**Comment by pocmo** [comment]
Okay, I'll take a look too tomorrow. :)

**Comment by pocmo** [comment]
Briefly looked into it. It's super annoying since `ActivityScenario` requires an actual `Activity` instance (while Robolectric was fine just instantiating `Activity`), .. but we do not have any in those modules. We just need an Activity `Context`.

**Comment by pocmo** [comment]
Let's skip that for now...

**Pull request closed without merging**
