### PR TITLE
For #3707 - Add feature-private component

### PR DESCRIPTION
**Pull request by NotWoods**
Adds new component for private mode features such as preventing screenshots and showing a notification when private tabs are open.

---

### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- [ ] **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- [ ] **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Comment by pocmo** [comment]
> Package 'mozilla.components.feature.private' from AndroidManifest.xml is not a valid Java package name as 'private' is a Java keyword.

Heh. We had a similar issue in the beginning where we had `abstract-*` components. We renamed them to `concept-*` components. :)

**Comment by pocmo** [comment]
* `feature-privatemode`
* `feature-privatebrowsing*
* ...

**Comment by Amejia481** [comment]
> Heh. We had a similar issue in the beginning where we had abstract-* components. We renamed them to concept-* components. :)

Nice this is from `concept-* ` came from :)

**Comment by NotWoods** [comment]
bors r=pocmo

**Comment by NotWoods** [comment]
bors retry

**Pull request merged**
