### PR TITLE
Application services 93.0.1

### PR DESCRIPTION
**Pull request by bendk**
Note: the tabs constructor commit was approved in #11799

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/main/docs/changelog.md) or does not need one
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/main/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Comment by bendk** [comment]
Note: Sammy also opened #12039 which updates a-s to `v91.1.2`.  This change contains the fix from that, plus an updated expiration date on the logins encryption key regeneration metrics, and many other changes.

I don't think any of the other changes are particularly risky, but there is a lot of them.

AFAIK, the only one that has any urgency is the logins encryption key metric expiration date update.  It would be nice to get this merged to avoid the metrics expiring.  But I don't think that it would be too bad if they expire, since I think they'll start working again once a-c does updates to `v93.0.1`.  Missing a few weeks of metrics isn't a big deal.

So I guess it's a choice between:
  - Upgrading to `v93.0.1` for the 102 release cycle.
  - Upgrading to `v91.1.2` for the 102 release cycle and `v93.0.1` for the 103 cycle

**Review by Amejia481 — APPROVED** [review]
Looks good, just a minor nit on the commit messages "Incrment".

**Comment by Amejia481** [comment]
👋🏽 
@bendk just to confirm, the only critical patch is already on https://github.com/mozilla-mobile/android-components/pull/12029? I'm asking as only have one week for this cycles to end.

**Comment by bendk** [comment]
> 👋🏽 @bendk just to confirm, the only critical patch is already on #12029? I'm asking as only have one week for this cycles to end.

Yes I think that's correct.  AFAIK, the second most important patch is extending the logins encryption key metrics, but I would not call that critical.

**Comment by Amejia481** [comment]
We already updated to `v91.1.2` on main https://github.com/mozilla-mobile/android-components/pull/12031/, maybe as we don't have anything urgent on v93.0.1 and only one week left. I think we could wait until the 102 release cycle.

**Comment by jonalmeida** [comment]
We've cut the 101 branch, so we can land this now.

**Comment by jonalmeida** [comment]
Network intermittent?
```
[task 2022-05-02T22:37:16.886Z] * What went wrong:
[task 2022-05-02T22:37:16.886Z] A problem occurred configuring root project 'vcs'.
[task 2022-05-02T22:37:16.886Z] > Could not resolve all artifacts for configuration ':classpath'.
[task 2022-05-02T22:37:16.886Z]    > Could not find com.android.tools.build:gradle:7.0.0.
[task 2022-05-02T22:37:16.886Z]      Searched in the following locations:
[task 2022-05-02T22:37:16.886Z]        - http://localhost:8081/nexus/content/repositories/google/com/android/tools/build/gradle/7.0.0/gradle-7.0.0.pom
[task 2022-05-02T22:37:16.886Z]        - http://localhost:8081/nexus/content/repositories/central/com/android/tools/build/gradle/7.0.0/gradle-7.0.0.pom
[task 2022-05-02T22:37:16.886Z]        - https://plugins.gradle.org/m2/com/android/tools/build/gradle/7.0.0/gradle-7.0.0.pom
[task 2022-05-02T22:37:16.886Z]      Required by:
[task 2022-05-02T22:37:16.887Z]          project :
```

**Comment by jonalmeida** [comment]
Ack, the changelog entry is in the old place, but I'll move it to the new one once this lands because it'll be a pain to restart CI again.

**Pull request merged**
