### PR TITLE
Closes #5359: Detect self-hosting configurations during FxA migration

### LINKED ISSUE #5359: Detect self-hosting FxA/Sync configurations, do not auto-migrate FxA for these users
For self-hosting users, we need to ensure we won't accidentally start uploading their data to our own storage servers (as will currently happen if user is using mozilla's FxA server but their own sync storage servers via tokenserver url config in Fennec).

Ideal version of this is https://github.com/mozilla-mobile/android-components/issues/5358 (full support for these users), but as Step 1, let's disable the FxA migration if we detect this scenario.

Related: https://github.com/mozilla-mobile/android-components/issues/3729

### PR DESCRIPTION
**Pull request by grigoryk**
This also adds some missing FxA failure telemetry, as well.

---

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- [ ] **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- [ ] **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Comment by grigoryk** [comment]
Tested this locally with custom token configurations and regular configs, both worked correctly (first failed, second worked). Did not test custom auth server, since I don't have setup locally to be able to actually sign-in in Fennec. No reason it shouldn't work, though.

**Comment by grigoryk** [comment]
# Request for data collection review form

**All questions are mandatory. You must receive review from a data steward peer on your responses to these questions before shipping new data collection.**

1) What questions will you answer with this data?

If custom sync/auth server configurations were detected during a migration;
Which internally tracked (and unsupported by the migration) FxA state versions were detected.

2) Why does Mozilla need to answer these questions?  Are there benefits for users? Do we need this information to address product or business requirements? 

To support our engineering efforts around Fenne -> Fenix migration.

3) What alternative methods did you consider to answer these questions? Why were they not sufficient?

Alternative is not tracking this data. We'd like to have insights into this, to both gauge product interest (in custom sync configurations) and to detect migration abnormalities.

4) Can current instrumentation answer these questions?

No.

5) List all proposed measurements and indicate the category of data collection for each measurement, using the [Firefox data collection categories](https://wiki.mozilla.org/Firefox/Data_Collection) found on the Mozilla wiki.   

**Note that the data steward reviewing your request will characterize your data collection based on the highest (and most sensitive) category.**

<table>
  <tr>
    <td>Measurement Description</td>
    <td>Data Collection Category</td>
    <td>Tracking Bug #</td>
  </tr>
  <tr>
    <td>custom token server present</td>
    <td>category 2 - interaction data</td>
    <td>#5359</td>
  </tr>
  <tr>
    <td>custom idp server present</td>
    <td>category 2 - interaction data</td>
    <td>#5359</td>
  </tr>
  <tr>
    <td>unsupported_account_version</td>
    <td>category 1 - technical data</td>
    <td>#5359</td>
  </tr>
  <tr>
    <td>unsupported_pickle_version</td>
    <td>category 1 - technical data</td>
    <td>#5359</td>
  </tr>
  <tr>
    <td>unsupported_state_version</td>
    <td>category 1 - technical data</td>
    <td>#5359</td>
  </tr>
</table>


6) How long will this data be collected?  Choose one of the following:
expires: 2020-10-01

7) What populations will you measure?
No filters - all locales, channels, etc.

8) If this data collection is default on, what is the opt-out mechanism for users?
Default Glean SDK opt-out mechanism.

9) Please provide a general description of how you will analyze this data.
By observing it in the migration dashboard (tbd).

10) Where do you intend to share the results of your analysis?
Internally in the fenix/android-components teams.

11) Is there a third-party tool (i.e. not Telemetry) that you are proposing to use for this data collection? If so:
no.

**Comment by boek** [comment]
R+

# Data Review Form (to be filled by Data Stewards)

1) Is there or will there be **documentation** that describes the schema for the ultimate data set in a public, complete, and accurate way?
Yes, metrics.yaml and metrics.md

2) Is there a control mechanism that allows the user to turn the data collection on and off?
Yes, glean provides APIs to allow the user to turn off data collection.

3) If the request is for permanent data collection, is there someone who will monitor the data over time?
Has expiry

4) Using the **[category system of data types](https://wiki.mozilla.org/Firefox/Data_Collection)** on the Mozilla wiki, what collection type of data do the requested measurements fall under?
Type1, Type 2

5) Is the data collection request for default-on or default-off?
The default is handled by the client.

6) Does the instrumentation include the addition of **any *new* identifiers** (whether anonymous or otherwise; e.g., username, random IDs, etc.  See the appendix for more details)?
no

7) Is the data collection covered by the existing Firefox privacy notice?
Yes

8) Does there need to be a check-in in the future to determine whether to renew the data?
`fenix-core` Will check-in at expiry.

9) Does the data collection use a third-party collection tool?
No

**Comment by grigoryk** [comment]
bors r=pocmo

**Pull request merged**
