### PR TITLE
Bump a-s to v61.0.13

### PR DESCRIPTION
**Pull request by linacambridge**
Heads up @gabrielluong! 😁

### CODE REVIEW

**Comment by gabrielluong** [comment]
This is a dot release that includes https://github.com/mozilla/application-services/issues/3503 to help with #7978

**Comment by pocmo** [comment]
> Could not find org.mozilla.appservices:fxaclient:61.0.13.

🤔 

Looks like it is on maven though:
https://maven.mozilla.org/?prefix=maven2/org/mozilla/appservices/fxaclient/61.0.13/

Rerunning...

**Comment by jonalmeida** [comment]
bors try

Runs sync UI automation tests. ^

**Comment by jonalmeida** [comment]
bors try

**Comment by jonalmeida** [comment]
> ## try
> 
> Build succeeded:
> 
>     * [complete-push](https://github.com/mozilla-mobile/android-components/runs/1027729715)

Good bot.

**Pull request merged**
