### PR TITLE
Closes #9439: Narrow BrowserMenu fix to only Huawei and Xiaomi devices

### LINKED ISSUE #9439: Narrow Huawei BrowserMenu fix to only Huawei devices
Currently there is a workaround for an issue that overrides where `BrowserMenu` popup location algorithm.
https://github.com/mozilla-mobile/fenix/issues/15344

This is causing other issues with tab tray menu on all devices.  Narrow this workaround down to only Huawei devices.

### PR DESCRIPTION
**Pull request by rocketsroger**
### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Review by codrut-topliceanu — CHANGES_REQUESTED** [review]
I'm afraid that some devices that aren't Huawei or Xiaomi still need to go through the `showAtAnchorLocation` workaround as the normal workflow doesn't work.

Image captured from LG k4 (android 6) going through  `showPopupWhereBestFits`:

**Comment by rocketsroger** [comment]
> I'm afraid that some devices that aren't Huawei or Xiaomi still need to go through the `showAtAnchorLocation` workaround as the normal workflow doesn't work.

As discussed, this is probably a different issue that we should open an issue to track.

**Comment by codrut-topliceanu** [comment]
https://github.com/mozilla-mobile/fenix/issues/15344#issuecomment-765393942

This patch will create a regression of https://github.com/mozilla-mobile/fenix/issues/15344 on Samsung devices. 
Additionally we're not entirely sure if all xiaomi and huawei devices are affected by previous issue, just some that have been tested on in the original issue.

**Comment by rocketsroger** [comment]
> This patch will create a regression of [mozilla-mobile/fenix#15344](https://github.com/mozilla-mobile/fenix/issues/15344) on Samsung devices.

If the workaround is needed for Samsung devices then narrowing it would not work anymore.  Thanks for confirming.  This seems like a bigger issue if all devices under M or below have the problem.  Since we're trying to guess where the menu popup should be after rotation, there will always be issues with different device resolution.  I'm now leaning towards removing the workaround completely and dismissing the menu popup when rotating like the tabs tray menu.

**Comment by rocketsroger** [comment]
Closing this pr.  Looks like a better solution will be on the Fenix side.

**Pull request closed without merging**
