### PR TITLE
For #5866: Don't crash when failed to launch new window request in custom tab

### PR DESCRIPTION
**Pull request by rocketsroger**
---

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- [ ] **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- [ ] **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Comment by jonalmeida** [comment]
I'm not sure what the context for the fix is so this may be out of place:

Shouldn't we figure out why we weren't able to handle the intent since it looks like it was meant for ourselves (`mozilla.components.pwa.category.SHORTCUT`) instead of try-catching it?

```
No Activity found to handle Intent { act=android.intent.action.VIEW cat=[mozilla.components.pwa.category.SHORTCUT] dat= pkg=org.mozilla.fennec_aurora (has extras) }
```

**Comment by rocketsroger** [comment]
> I'm not sure what the context for the fix is so this may be out of place:
> 
> Shouldn't we figure out why we weren't able to handle the intent since it looks like it was meant for ourselves (`mozilla.components.pwa.category.SHORTCUT`) instead of try-catching it?
> 
> ```
> No Activity found to handle Intent { act=android.intent.action.VIEW cat=[mozilla.components.pwa.category.SHORTCUT] dat= pkg=org.mozilla.fennec_aurora (has extras) }
> ```

Agreed, this is not a fix.  This is more to avoid these crashes by catching them and sending them as a caught exception.  There's a bigger underlying issue here.  I'm not closing this issue yet and will be continue to investigate.  However, I want to avoid crashing first.

**Comment by rocketsroger** [comment]
> LGTM but leaving it to you to merge since you might have wanted a review from Sebastian as well from the looks of it.

Your approval is just as good :)

**Comment by rocketsroger** [comment]
bors r=jonalmeida

**Comment by ValentinTimisica** [comment]
Hello @rocketsroger, @jonalmeida, I already had for a long time a PR created for this crash which actually fixes the issue.

You can check it [here](https://github.com/mozilla-mobile/android-components/pull/6122).
#6094 is the AC issue and [this](https://github.com/mozilla-mobile/fenix/issues/8412) is the Fenix issue (which contain the result of my investigation with steps to reproduce) for which I also have a [PR](https://github.com/mozilla-mobile/fenix/pull/8903) (with directions from UX to show a message to the user).

I would appreciate if you guys could review my patch.

**Comment by rocketsroger** [comment]
> Hello @rocketsroger, @jonalmeida, I already had for a long time a PR created for this crash which actually fixes the issue.

Sorry I didn't notice your PR before merging mine.  However, mine PR is not meant to fix this issue.  There is a underlying issue that we need to investigate here.  My change is just to avoid crashing but still report the crash so it is being tracked.

**Comment by ValentinTimisica** [comment]
> > Hello @rocketsroger, @jonalmeida, I already had for a long time a PR created for this crash which actually fixes the issue.
> 
> Sorry I didn't notice your PR before merging mine. However, mine PR is not meant to fix this issue. There is a underlying issue that we need to investigate here. My change is just to avoid crashing but still report the crash so it is being tracked.

I investigated and found the underlying issue: any url touches in web pages gets in AC which will then try to start a client activity to handle that specific url.

In our case (Fenix) and in other clients's cases also there might not be an activity with an intent filter to match that url's scheme and this will cause an ActivityNotFoundException in AC.
We can't fix this in AC because is a client issue that can only be fixed there by registering new intent filters for the new schemes.
The best what we can do in this case is pass that information to the client - that it cannot handle that specific url.

**Comment by rocketsroger** [comment]
> We can't fix this in AC because is a client issue that can only be fixed there by registering new intent filters for the new schemes.

Yes with the current way that we have no way of fixing this.  But I was thinking there might be another way if A-C launch new window request differently in custom tab or understand that this is not a supported URL in GeckoView and launch in a third party app. (similar to applinks feature)

**Pull request merged**
