### PR TITLE
Close #3036: Add feature to support WebAuthn

### LINKED ISSUE #3036: Support the W3C Web Authentication specification (WebAuthn)
Support the W3C Web Authentication specification in Android. Web Authentication is our best tool against phishing on the web, and now is a W3C Recommendation. Firefox supports Web Authentication on Desktop since Firefox 60.

@snorp says A-C will need some code to support Gecko WebAuthn. I don't know exactly what A-C needs to do, but @jcjones says we’ll need to move the GV's `mobile/android/geckoview/src/main/java/org/mozilla/gecko/WebAuthn*` files into A-C and figure out the Google Play Services dependency it provides via the [FIDO2 API](https://developers.google.com/android/reference/com/google/android/gms/fido/fido2/package-summary).

PI is prepared to do Fennec Beta 68 testing, so they will already have a test plan they can reuse for testing Fenix.

Fenix's WebAuthn issue: mozilla-mobile/fenix#1340
GV bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1549418

### PR DESCRIPTION
**Pull request by jonalmeida**
A couple of open questions:
 1. It would be better if we could move this to BrowserStore. How we could move the callback to the state?
 2. I placed this in `feature-session` but maybe someone else has a better suggestion where this would belong. 🙂 

Fixes #3036

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Comment by jonalmeida** [comment]
What's weird about this feature is that, reading it, it has nothing to do with WebAuthn since the delegates are just for passing over intents.

You can read some of the discussion here to make this delegate specific to WebAuthn: https://bugzilla.mozilla.org/show_bug.cgi?id=1671988

**Review by csadilek — COMMENTED** [review]
> It would be better if we could move this to BrowserStore. How we could move the callback to the state?

I don't think we should move callbacks/lamdas to the store. So, I think keeping those in the features is fine.

> I placed this in feature-session but maybe someone else has a better suggestion where this would belong. 🙂

That's the only feedback I have here too. This feature, unlike others in `feature-session`, doesn't depend or observe the session or state. To me it seems it deserves its own modules `feature-webauthn`?

**Review by csadilek — APPROVED** [review]
✨ We should add it to the root README as well: https://github.com/mozilla-mobile/android-components/blob/master/README.md

**Comment by jonalmeida** [comment]
> ✨ We should add it to the root README as well: https://github.com/mozilla-mobile/android-components/blob/master/README.md

Oops, yes!

**Pull request merged**
