### PR TITLE
Split application services gradle projects versions

### PR DESCRIPTION
**Pull request by eoger**
This allows for more flexibility on the `a-s` side.

cc @thomcc @ncalexan

### CODE REVIEW

**Comment by grigoryk** [comment]
Won't this dramatically increase amount of weirdness/bugs that will be possible in theory?

**Comment by ncalexan** [comment]
> Won't this dramatically increase amount of weirdness/bugs that will be possible in theory?

Possibly.  We expect to use this for a while and manage the "interaction windows" manually.  Fine by me if it unblocks us for the immediate time.

**Comment by csadilek** [comment]
I think using a single app_services version is preferable, but right now development productivity matters most. So, if this is better for you guys, definitely r+.

@vladikoff r?

**Comment by vladikoff** [comment]
> I think using a single app_services version is preferable, but right now development productivity matters most. So, if this is better for you guys, definitely r+.

> @vladikoff r?

Yea correct, this is dev only and if there is a PR that changes one of the versions, but not the rest it might lead to weird artifacts. Previously I would just manually do this change while I was working on component updates. This should be fine for now

**Comment by eoger** [comment]
Can we also make sure the right people are being asked when bumping the 3 versions in the future? For example right now I'd like `mozilla_fxa` to stay 0.10.0 until https://github.com/mozilla/application-services/issues/303 is done.

**Comment by pocmo** [comment]
> Can we also make sure the right people are being asked when bumping the 3 versions in the future? 

Can we add this (and which people) as a comment in the Dependencies.kt file right next to those numbers? Imho that's the only place where we will see this every time we are making or reviewing changes.

**Pull request merged**
