### PR TITLE
Close #7822: Remove deprecated BrowserTabsTray

### LINKED ISSUE #7822: Removed deprecated BrowserTabsTray in 53.0.0
In #7079, we decoupled the adapter from the `BrowserTabsTray`, we should be able to remove it since it doesn't provide any use for us (we can always re-add it back with a better API if we find a better use case).

When removing this, we should also move the `TabsTrayStyling` be a constructor param.

### PR DESCRIPTION
**Pull request by jonalmeida**
---

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Comment by jonalmeida** [comment]
external-content duckduckgo com

**Review by pocmo — APPROVED** [review]

**Comment by pocmo** [comment]
@jonalmeida Should this land? :)

**Comment by jonalmeida** [comment]
external-content duckduckgo com

**Comment by jonalmeida** [comment]
bors r=pocmo

**Pull request merged**
