### PR TITLE
Closes #11368 - CreditCardEnc scrubbing on key loss; key management refactor

### LINKED ISSUE #11368: Implement `recoverFromBadKey` for `AutofillCreditCardsAddressesStorage`
Now that we can scrub encrypted data in credit cards (see https://github.com/mozilla/application-services/issues/4015#issuecomment-987455922), we should hook up `recoverFromBadKey` in the Autofill storage to this API.

### PR DESCRIPTION
**Pull request by grigoryk**
Two parts to this:

Closes mozilla-mobile#11368 - Handle key recovery flow for credit cards storage

- remove KeyRecoveryHandler indirection, I don't think it was adding
  any value
- AutofillCrypto and LoginsCrypto are now taking shape of a 'key
  manager' type objects - they know how to get, validate and store keys,
  as well as recover corresponding storage classes from key loss.
- AutofillCrypto now scrubs credit cards - removes encrypted CC numbers
  and resets the sync engine - in case of key loss.

Closes mozilla-mobile#11099: Introduce KeyManager structure

This adds an abstract KeyManager class to our storage component, which
establishes a pattern of managing keys as used by our storage classes
that require encryption.

AutofillCrypto and LoginsCrypto become implementors of this basis class,
allowing them to explicitly share structure and some core functionality.

### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/main/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/main/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Comment by grigoryk** [comment]
TODO still: docstrings, maybe a bit of cleanup around `validateRawKey` method which is pretty weird right now (does both validation _and_ generation).

**Comment by grigoryk** [comment]
Cleaned up the `validate` bits, it's a bit less tangled up now. Should be ready for a review.

Fenix PR that fixes breaking changes: https://github.com/mozilla-mobile/fenix/pull/22773

**Review by bendk — APPROVED** [review]
Looks great.  I love the new key management code.

**Comment by grigoryk** [comment]
Going to wait until Monday to land this, just in case :)

**Review by gabrielluong — APPROVED** [review]

**Comment by gabrielluong** [comment]
> [taskcluster 2021-12-13 16:36:43.131Z] Image 'public/image.tar.zst' from task 'cDGrr5w-RUOLzsYNiEhYeQ' loaded.  Using image ID sha256:b46a948819e96a19338874bd42666995482cdce511714ec554f1a16c80b873a1.
> [taskcluster 2021-12-13 16:36:43.202Z] === Task Starting ===
> [setup 2021-12-13T16:36:43.565Z] run-task started in /builds/worker
> [volume 2021-12-13T16:36:43.567Z] changing ownership of volume /builds/worker/.cache to 1000:1000
> [volume 2021-12-13T16:36:43.567Z] changing ownership of volume /builds/worker/checkouts to 1000:1000
> [setup 2021-12-13T16:36:43.567Z] running as worker:worker
> [vcs 2021-12-13T16:36:43.567Z] executing ['git', 'clone', 'https://github.com/mozilla-mobile/android-components', '/builds/worker/checkouts/src']
> [vcs 2021-12-13T16:36:43.568Z] Cloning into '/builds/worker/checkouts/src'...
> [vcs 2021-12-13T16:36:45.208Z] error: RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.
> [vcs 2021-12-13T16:36:45.209Z] fatal: The remote end hung up unexpectedly
> [vcs 2021-12-13T16:36:45.209Z] fatal: early EOF
> [vcs 2021-12-13T16:36:45.209Z] fatal: index-pack failed
> [taskcluster 2021-12-13 16:36:45.524Z] === Task Finished ===
> [taskcluster 2021-12-13 16:36:45.629Z] Artifact "public/github/customCheckRunText.md" not found at "/builds/worker/github/customCheckRunText.md"
> [taskcluster 2021-12-13 16:36:45.717Z] Artifact "public/reports/tests" not found at "/builds/worker/checkouts/src/components/support/sync-telemetry/build/reports/tests"
> [taskcluster 2021-12-13 16:36:45.805Z] Artifact "public/reports/jacoco" not found at "/builds/worker/checkouts/src/components/support/sync-telemetry/build/reports/jacoco"
> [taskcluster 2021-12-13 16:36:45.881Z] Artifact "public/reports/lint-results-release.html" not found at "/builds/worker/checkouts/src/components/support/sync-telemetry/build/reports/lint-results-release.html"
> [taskcluster 2021-12-13 16:36:45.973Z] Unsuccessful task run with exit code: 128 completed in 3.359 seconds

Restarting

**Comment by grigoryk** [comment]
Thanks, @gabrielluong  :)

**Pull request merged**
