### PR TITLE
For #9555: Fix WEBP deprecation in SDK 30.

### PR DESCRIPTION
**Pull request by mcarare**
### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Comment by mcarare** [comment]
Tests cannot pass until we upgrade robolectric so we can use SDK 30 in tests.

**Review by jonalmeida — APPROVED** [review]
👍

**Comment by jonalmeida** [comment]
@mcarare leaving for you to land since the issue says it's blocked from landing by robolectric (but this patch runs through CI fine 🤔 ).

**Comment by mcarare** [comment]
@jonalmeida I was also going to add some tests to also check for the proper format being set when using SDK 30, but I guess we could do that afterwards. This will just mean we would have that part not covered by tests yet.

**Pull request merged**
