### PR TITLE
Ecosia

### PR DESCRIPTION
**Pull request by mkaply**
Add Ecosia search plugin for Germany.

---

### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- [ ] **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- [ ] **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Comment by mkaply** [comment]
I'm confused as to what the failure are here. This didn't really change anything I thought. I'll get a build going locally.

**Comment by pocmo** [comment]
```
[task 2019-11-14T17:05:11.223Z]   TEST: Load search engines for de-DE with global US region override
[task 2019-11-14T17:05:11.223Z]     [Robolectric] mozilla.components.browser.search.provider.AssetsSearchEngineProviderTest.Load search engines for de-DE with global US region override: sdk=28; resources=binary
[task 2019-11-14T17:05:11.223Z]     I/MonitoringInstr: Instrumentation started!
[task 2019-11-14T17:05:11.223Z]     I/MonitoringInstr: Setting context classloader to 'org.robolectric.internal.bytecode.SandboxClassLoader@3f66131d', Original: 'org.robolectric.internal.bytecode.SandboxClassLoader@3f66131d'
[task 2019-11-14T17:05:11.323Z]   FAILURE
```

```
[task 2019-11-14T17:05:12.423Z]   TEST: parser[ecosia.xml]
[task 2019-11-14T17:05:12.423Z]     [Robolectric] mozilla.components.browser.search.ParseSearchPluginsTest.parser: sdk=28; resources=binary
[task 2019-11-14T17:05:12.423Z]     I/MonitoringInstr: Instrumentation started!
[task 2019-11-14T17:05:12.423Z]     I/MonitoringInstr: Setting context classloader to 'org.robolectric.internal.bytecode.SandboxClassLoader@3f66131d', Original: 'org.robolectric.internal.bytecode.SandboxClassLoader@3f66131d'
[task 2019-11-14T17:05:12.423Z]   FAILURE
[task 2019-11-14T17:05:12.423Z] 
[task 2019-11-14T17:05:12.423Z] org.xmlpull.v1.XmlPullParserException: attr value delimiter missing! (position:START_TAG <Url type='application/x-suggestions+json' method='GET' template='null'>@9:66 in java.io.InputStreamReader@3f4aec38) 
[task 2019-11-14T17:05:12.423Z] 	at org.kxml2.io.KXmlParser.parseStartTag(KXmlParser.java:1120)
[task 2019-11-14T17:05:12.423Z] 	at org.kxml2.io.KXmlParser.next(KXmlParser.java:372)
[task 2019-11-14T17:05:12.423Z] 	at org.kxml2.io.KXmlParser.next(KXmlParser.java:313)
[task 2019-11-14T17:05:12.423Z] 	at mozilla.components.browser.search.SearchEngineParser.readSearchPlugin(SearchEngineParser.kt:86)
[task 2019-11-14T17:05:12.423Z] 	at mozilla.components.browser.search.SearchEngineParser.load(SearchEngineParser.kt:69)
[task 2019-11-14T17:05:12.423Z] 	at mozilla.components.browser.search.ParseSearchPluginsTest.parser(ParseSearchPluginsTest.kt:26)
[task 2019-11-14T17:05:12.423Z] 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
[task 2019-11-14T17:05:12.423Z] 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
[task 2019-11-14T17:05:12.423Z] 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
[task 2019-11-14T17:05:12.423Z] 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
[task 2019-11-14T17:05:12.423Z] 	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:601)
[task 2019-11-14T17:05:12.424Z] 	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:260)
[task 2019-11-14T17:05:12.424Z] 	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:130)
[task 2019-11-14T17:05:12.424Z] 	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:42)
[task 2019-11-14T17:05:12.424Z] 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
[task 2019-11-14T17:05:12.424Z] 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
[task 2019-11-14T17:05:12.424Z] 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
[task 2019-11-14T17:05:12.424Z] 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
[task 2019-11-14T17:05:12.424Z] 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
[task 2019-11-14T17:05:12.424Z] 	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:84)
[task 2019-11-14T17:05:12.424Z] 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[task 2019-11-14T17:05:12.424Z] 	at org.junit.runners.Suite.runChild(Suite.java:128)
[task 2019-11-14T17:05:12.424Z] 	at org.junit.runners.Suite.runChild(Suite.java:27)
[task 2019-11-14T17:05:12.424Z] 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
[task 2019-11-14T17:05:12.424Z] 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
[task 2019-11-14T17:05:12.424Z] 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
[task 2019-11-14T17:05:12.424Z] 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
[task 2019-11-14T17:05:12.424Z] 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
[task 2019-11-14T17:05:12.424Z] 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[task 2019-11-14T17:05:12.424Z] 	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
[task 2019-11-14T17:05:12.424Z] 	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
[task 2019-11-14T17:05:12.424Z] 	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
[task 2019-11-14T17:05:12.424Z] 	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
[task 2019-11-14T17:05:12.424Z] 	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
[task 2019-11-14T17:05:12.424Z] 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
[task 2019-11-14T17:05:12.424Z] 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
[task 2019-11-14T17:05:12.424Z] 	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
[task 2019-11-14T17:05:12.424Z] 	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
[task 2019-11-14T17:05:12.424Z] 	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
[task 2019-11-14T17:05:12.424Z] 	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:118)
[task 2019-11-14T17:05:12.424Z] 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
[task 2019-11-14T17:05:12.424Z] 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
[task 2019-11-14T17:05:12.424Z] 	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:175)
[task 2019-11-14T17:05:12.424Z] 	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:157)
[task 2019-11-14T17:05:12.424Z] 	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
[task 2019-11-14T17:05:12.424Z] 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
[task 2019-11-14T17:05:12.424Z] 	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
[task 2019-11-14T17:05:12.424Z] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[task 2019-11-14T17:05:12.424Z] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[task 2019-11-14T17:05:12.424Z] 	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
[task 2019-11-14T17:05:12.424Z] 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by pocmo** [comment]
@mkaply There's one failure left. One of the tests is using the DE list which is now different :)

```
[task 2019-11-14T19:38:13.749Z]   TEST: Load search engines for de-DE with global US region override
[task 2019-11-14T19:38:13.749Z]     [Robolectric] mozilla.components.browser.search.provider.AssetsSearchEngineProviderTest.Load search engines for de-DE with global US region override: sdk=28; resources=binary
[task 2019-11-14T19:38:13.749Z]     I/MonitoringInstr: Instrumentation started!
[task 2019-11-14T19:38:13.749Z]     I/MonitoringInstr: Setting context classloader to 'org.robolectric.internal.bytecode.SandboxClassLoader@34ce48a3', Original: 'org.robolectric.internal.bytecode.SandboxClassLoader@34ce48a3'
[task 2019-11-14T19:38:13.749Z]   FAILURE
```

**Comment by pocmo** [comment]
bors try

**Comment by mkaply** [comment]
Clearly I don't know what I'm doing :).

I'll work on getting this building locally (was having build problems)

**Comment by pocmo** [comment]
If you only want to build and test this component then you can try on the command line:
```bash
./gradlew browser-search:assemble browser-search:test`
```

**Comment by pocmo** [comment]
@mkaply Do you want me to take this over and land?

**Comment by mkaply** [comment]
> Do you want me to take this over and land?

I think you're going to have to. I don't understand how to navigate any of this stuff to figure out these failures. The test is passing locally, I don't know what these other checks are.

**Comment by pocmo** [comment]
Actually it looks like the PR should be ready to land now and there was just an intermittent on taskcluster. Let's try landing it:

bors r+

**Pull request merged**
