### PR TITLE
DeliverManager.runWithInitialized.

### PR DESCRIPTION
**Pull request by binc0**
In the AutopushFeature: DeliveryManager.with -> DeliverManager.runWithInitialized

---

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- [ ] **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- [ ] **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Comment by binc0** [comment]
#4822

**Comment by jonalmeida** [comment]
@binc0 I think we need to change the actually function name itself too. :)

**Comment by binc0** [comment]
> @binc0 I think we need to change the actually function name itself too. :)

@jonalmeida let me know when you'll change function name so I can submit a new PR

**Comment by jonalmeida** [comment]
Hey @binc0, the function was in the same class you were editing.

**Pull request closed without merging**
