### PR TITLE
Closes #5077: Renames onDownloadCompleted

### LINKED ISSUE #5077: Make `onDownloadCompleted` name more accurate
As seen in https://github.com/mozilla-mobile/fenix/issues/6434#issuecomment-554288688, this name can be confusing since `onDownloadCompleted` gets called even when a download is simply paused. 

Perhaps we should say something like `onDownloadStreamClosed`

### PR DESCRIPTION
**Pull request by sblatz**
---

### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- [ ] **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- [ ] **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Comment by sblatz** [comment]
bors r=@NotWoods

**Comment by sblatz** [comment]
bors retry

**Comment by csadilek** [comment]
@sblatz @NotWoods I think we should have deprecated before removal: https://mozac.org/contributing/deprecating

In any case, when removing we always want a PR up for Fenix and R-B to address the breaking change (see PR template above). Merging this on a Friday afternoon also isn't ideal as now R-B and Fenix master are broken over the weekend (which also affects fixes going out in Nightly).

`</oldmanyellsatcloud>`

**Comment by NotWoods** [comment]
In this case deprecation is pretty difficult, since the arguments names changed but not the types. Since the JVM can't differentiate, we can't introduce a new constructor without removing the previous one.

**Comment by csadilek** [comment]
@NotWoods Yeah, tedious, but we could have introduced `onDownloadStopped` in addition to `onDownloadCompleted` and then removed `onDownloadCompleted` in the next release. Also, looks like Fenix is using field access for it, not the constructor.

I mean I have also opted for removal, but my main point was to try not to break master for extended periods of time by preparing the PRs and ideally not landing it before the weekend. :)

Here's the quick fix for Fenix: https://github.com/mozilla-mobile/fenix/pull/6772
R-B is actually not affected.

**Comment by NotWoods** [comment]
I commented before checking Fenix so I didn't realize its not using the named argument 🙃

**Pull request merged**
