### PR TITLE
Closes #10910: Build with SDK for Android 12 / API 31.

### LINKED ISSUE #10910: Build with SDK for Android 12 / API 31
The [beta program for Android 12](https://developer.android.com/about/versions/12/overview) is now in the "stability phase" and the APIs are finalized. Now we can start using 31 as `compileSdkVersion` (not `targetSdkVersion` yet) and get blockers out of the way.

### PR DESCRIPTION
**Pull request by Amejia481**
### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/main/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/main/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Comment by mcarare** [comment]
This seems stuck.
@Amejia481 maybe [this](https://github.com/mozilla-mobile/android-components/blob/6d9f19e56cffdd994d271e536870b1c3145b1aaa/buildSrc/src/main/java/Dependencies.kt#L5) is needed to get things going?

**Comment by Amejia481** [comment]
> This seems stuck. @Amejia481 maybe [this](https://github.com/mozilla-mobile/android-components/blob/6d9f19e56cffdd994d271e536870b1c3145b1aaa/buildSrc/src/main/java/Dependencies.kt#L5) is needed to get things going?

Thanks for the tip :)
It looks like is still stuck

**Comment by mcarare** [comment]
I see 3 failures for :
`[task 2022-06-02T13:20:44.440Z] > Task :feature-containers:processDebugAndroidTestManifest FAILED
[task 2022-06-02T13:20:44.440Z] 	android:exported needs to be explicitly specified for <activity>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. 
`

Since the module does not have any activities declared, these activities might come from a dependency, and as the failure is for `DebugAndroidTestManifest` it might be one of the dependencies for `androidTestImplementation`.  Maybe you could try to upgrade the test library from 1.3.0 to 1.4.0 ?

**Comment by mcarare** [comment]
@Amejia481 confirmed it locally. Upgrading `AndroidX.tes`t to 1.4.0. solves that problem.

**Comment by mcarare** [comment]
@Amejia481 confirmed it locally. Upgrading `AndroidX.tes`t to 1.4.0. solves that problem.

**Comment by Amejia481** [comment]
Awesome, thanks, I updated the PR!

**Review by mcarare — APPROVED** [review]

**Comment by Amejia481** [comment]
🎉 !

**Pull request closed without merging**
