### PR TITLE
Closes #5541: Safer onMessageReceived error handling

### LINKED ISSUE #5541: PushProcessor's onMessageReceived shouldn't crash on bad messages
In https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/6689773/events/37079363/ we're seeing crashes because we're failing to decrypt incoming push messages. Why is a separate discussion, and there are a number of reasons, but at least we shouldn't crash at this point, and instead just submit exceptions thrown by the Rust libs to the crash reporter.

### PR DESCRIPTION
**Pull request by grigoryk**
---

### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- [ ] **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- [ ] **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Comment by jonalmeida** [comment]
@grigoryk we can merge this, but it looks like there's a build failure:

```
[task 2020-01-11T02:02:30.501Z] > Task :concept-push:compileDebugUnitTestKotlin FAILED
[task 2020-01-11T02:02:30.501Z] e: /builds/worker/checkouts/src/components/concept/push/src/test/java/mozilla/components/concept/push/PushErrorTest.kt: (24, 32): Type mismatch: inferred type is String but kotlin.Exception /* = java.lang.Exception */ was expected
[task 2020-01-11T02:02:30.601Z] 
```

**Comment by grigoryk** [comment]
bors r=jonalmeida

**Comment by ebalazs-sv** [comment]
@grigoryk Hello! Can you please provide details to reproduce this issue, if it can be verified manually? Thanks!

**Comment by jonalmeida** [comment]
@ebalazs-sv this doesn't need to be tested. We monitored the crash rates decrease in Sentry. Thanks! :)

**Pull request merged**
