### PR TITLE
Workaround for querying geckoView tracking protection exceptions for bugzilla 1723280

### PR DESCRIPTION
**Pull request by Amejia481**
This patch should address the bugzilla bug [1723280](https://bugzilla.mozilla.org/show_bug.cgi?id=1723280) until it gets fixed.

### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/main/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/main/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Review by mcarare — APPROVED** [review]
LGTM!

**Review by pocmo — APPROVED** [review]

**Comment by pocmo** [comment]
@Amejia481 Can you uplift this to 91 too? That's the first one we will release Focus with. :)

**Comment by pocmo** [comment]
One task couldn't reach GitHub to download the patch. Retrying.

**Comment by pocmo** [comment]
Same problem 🙄

**Comment by pocmo** [comment]
@Mergifyio backport releases/91.0

**Pull request merged**
