### PR TITLE
Issue #673: Engine: Allow consumers to intercept requests and inject content.

### PR DESCRIPTION
**Pull request by pocmo**
@csadilek This is not done (I need to add KDoc and tests..). But I would like to know if the proposed Settings API looks good to you?

### CODE REVIEW

**Comment by pocmo** [comment]
> The only downside is that now when you call GeckoEngineSession.settings.javascriptEnabled you no longer get an exception telling you to use the engine instead.

But I'd still get the "unsupported" exception from the interface's default implementation, right?

**Comment by pocmo** [comment]
@csadilek Okay, I think this is now ready for review. :)

**Comment by pocmo** [comment]
> decrease coverage by 0.16%.

Let's see if I can improve that.

**Comment by csadilek** [comment]
> But I'd still get the "unsupported" exception from the interface's default implementation, right?

Yes, exactly.

**Comment by pocmo** [comment]
> decrease coverage by 0.06%.

That's better.

**Pull request merged**
