### PR TITLE
GeckoView Release Day!

### PR DESCRIPTION
**Pull request by pocmo**
🍰 

* browser-engine-gecko-beta (63) -> browser-engine-gecko-release (63)
* browser-engine-gecko-nightly (64) -> browser-engine-gecko-beta (64)
* browser-engine-gecko-nightly -> 65

### CODE REVIEW

**Comment by grigoryk** [comment]
Wrong version numbers in commit messages :last_quarter_moon_with_face:

**Comment by pocmo** [comment]
> Wrong version numbers in commit messages 🌜

Wrong version numbers?

**Comment by Amejia481** [comment]
I believe he refers that in the commits message have multiple versions, and some of them don't match with the actual ones in `Gecko.kt`

```kotlin
const val nightly_version = "65.0.20181023100123"
const val beta_version = "64.0.20181022150107"
const val release_version = "63.0.20181018182531"
```

image

**Comment by pocmo** [comment]
The commit messages should mean: beta 63 becomes release 63, nightly 64 becomes beta 64 and nightly 64 becomes just nightly 65. (That's how the code is "riding the trains" from component to component).

**Pull request merged**
