### PR TITLE
For mozilla-mobile/fenix#18708: Update height for ReaderView sepia Appearance control

### PR DESCRIPTION
**Pull request by codesuperstarr**
For https://github.com/mozilla-mobile/fenix/issues/18708

Increased the height of the Dark, Sepia and Light buttons to 48dp and set the buttons radio container clickable attribute to false to make the buttons easier to click and enhance accessiblity.

### CODE REVIEW

**Comment by codesuperstarr** [comment]
@eliserichards Please take a look

**Review by eliserichards — CHANGES_REQUESTED** [review]
This looks great! Since this issue is specifically for the sepia button, let's keep dark and light as they are and only change the sepia item 😄

**Comment by codesuperstarr** [comment]
@eliserichards made the requested changes, please review.

**Comment by csadilek** [comment]
Thank you for your contribution! We're re-evaluating how we want to address this and the related issues. I will close this PR in the meantime while we get clarity. 

Please feel free to comment on any open issue if you're interesting in contributing further! Thanks again.

**Pull request closed without merging**
