### PR TITLE
downgrade a-s version

### PR DESCRIPTION
**Pull request by jeddai**
### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/main/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/main/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### GitHub Automation

Used by GitHub Actions.

### CODE REVIEW

**Comment by jonalmeida** [comment]
bors try

**Comment by Amejia481** [comment]
bors try

**Comment by jonalmeida** [comment]
bors try

**Comment by jeddai** [comment]
Do I need to make a new commit?

**Review by jonalmeida — APPROVED** [review]
We finished a quick sanity using Fenix - and this looks ready to merge (followed by an AC release and a Fenix one too).

**Comment by jonalmeida** [comment]
For future context: we were seeing crashes in our native layer that are being tracked [here](https://github.com/mozilla/application-services/issues/5165). However, we want to uplift some fixes from nightly to the beta release, but since there are multiple patches that are in the previous version, we decided to downgrade the AC version to one that has only the fixes that we want to uplift to verify that the crashes are unrelated.

Does downgrading have a negative effect on stored data? In the current version of 94.3.0/94.3.1 there are no changes that do not apply any transformations to persistent data after talking to the app services team which makes this a fairly safe change.

**Pull request merged**
