### PR TITLE
Backport shipit 67

### PR DESCRIPTION
**Pull request by JohanLorenzo**
Backports #9077, #9202, #9132, #9140, #9228, and #9231 to the `release/67.0` branch

### CODE REVIEW

**Review by escapewindow — APPROVED** [review]
Thanks!

**Comment by escapewindow** [comment]
We probably want https://github.com/mozilla-mobile/android-components/commit/f9385c38cdd2b42fd450aa5d7edb02d649bff6b9 and whatever github/version bump fixes we land on master.

**Review by pocmo — APPROVED** [review]

**Comment by pocmo** [comment]
@escapewindow Is this something that still needs to land?

**Comment by escapewindow** [comment]
@pocmo Yes, we want this at some point soon. We were debating the timing of landing this and #9268 with @st3fan to avoid breaking things before the winter break.

**Pull request merged**
