### PR TITLE
For #10624 - Adds recoverable param to `RemoveAllTabsAction`

### PR DESCRIPTION
**Pull request by codrut-topliceanu**
...to be used by UndoMiddleware.kt to prevent closed tabs from being recoverable

For https://github.com/mozilla-mobile/android-components/issues/10624

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks.
- [x] **Tests**: This PR includes thorough tests.
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md).
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md).

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

PS: thank you for the guidance @Amejia481 ❤️

### CODE REVIEW

**Review by Amejia481 — APPROVED** [review]
Awesome work🥇 !
I just added some documentation nits.

**Comment by Amejia481** [comment]
@Mergifyio backport releases/91.0

**Comment by Amejia481** [comment]
@mergify  backport releases/91.0

**Comment by Amejia481** [comment]
@Mergifyio backport releases/91.0

**Comment by Amejia481** [comment]
@Mergifyio backport codrut-topliceanu:10624_adds_recoverable_param_to_removealltabsaction releases/91.0

**Comment by Amejia481** [comment]
@Mergifyio backport 10624_adds_recoverable_param_to_removealltabsaction releases/91.0

**Comment by Amejia481** [comment]
@Mergifyio backport releases_v91.0.0

**Comment by rocketsroger** [comment]
@Mergifyio backport releases/91.0

**Pull request merged**
