### PR TITLE
Bump a-s dependency to 0.48.3.

### PR DESCRIPTION
**Pull request by vladikoff**
Changelog: https://github.com/mozilla/application-services/releases/tag/v0.48.3

@grigoryk ⚠️ important migration fixes included

### CODE REVIEW

**Comment by grigoryk** [comment]
Seems to be missing test glean dependencies; I'll push out a fix.

**Comment by grigoryk** [comment]
Okay, let's try this. `samples-sync` failure seems... strange, and I couldn't replicate it locally. Hopefully just a fluke.

bors r+

**Comment by grigoryk** [comment]
Different (but similar) `samples-sync` failure:
```
[task 2020-01-24T19:42:58.323Z] * What went wrong:
[task 2020-01-24T19:42:58.323Z] Execution failed for task ':samples-sync:mergeReleaseJavaResource'.
[task 2020-01-24T19:42:58.323Z] > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
[task 2020-01-24T19:42:58.323Z]    > More than one file was found with OS independent path 'META-INF/support-utils_release.kotlin_module'
```

let's see if bors hits it, too..

**Comment by grigoryk** [comment]
bors retry

**Comment by grigoryk** [comment]
bors cancel

**Comment by grigoryk** [comment]
Going to land this on Monday, as I won't be around to deal with the fallout over the weekend if something goes wrong.

**Comment by pocmo** [comment]
I changed our packaging options to `exclude 'META-INF/*.kotlin_module'` in order to exclude 'META-INF/support-utils_release.kotlin_module' (However the `support-utils` is fishy here) but then I get:

```
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives:
     Program type already present: mozilla.components.Build
     Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
```

... which seems to hint at the code of support-base getting shipped twice. Did anything change in the way AS uses dependencies or packages code?

**Comment by pocmo** [comment]
The only difference I see is that `places` now depends on glean (according to `pom.xml`). But I can't see how this could cause code duplication.

**Comment by rfk** [comment]
When we added metrics to the logins component, we had to do this little shuffle in `build.gradle` to resolve the circular dependency on glean:

https://github.com/mozilla-mobile/android-components/blob/fab095c4162122b2f0d5645a2d29aec745057770/components/service/sync-logins/build.gradle#L32-L36

Perhaps we need to do something similar for `places` now that it too includes glean.

**Comment by pocmo** [comment]
That could be it. Looking at the dependency tree I see `service-glean` getting in twice - once as referenced project and once as an actual dependency with a version.

```
[..]
+--- :service-glean (variant: debug)
+--- org.mozilla.appservices:places:0.48.3@aar
+--- org.mozilla.components:service-glean:24.0.0@aar
+--- org.mozilla.telemetry:glean:24.1.0@aar
[..]
```

**Comment by pocmo** [comment]
bors retry

**Comment by vladikoff** [comment]
Thank you @pocmo @grigoryk !!!

**Pull request merged**
