### PR TITLE
Use the A-S version defined in Dependencies.kt for the nimbus-fml plugin

### PR DESCRIPTION
**Pull request by rvandermeulen**

### CODE REVIEW

**Comment by jonalmeida** [comment]
bors try

**Comment by rvandermeulen** [comment]
bors try

**Comment by rvandermeulen** [comment]
It's not clear to me how to actually test this. In my last push, I intentionally add a syntax error to NimbusGradlePlugin.groovy, but no jobs broke 😦

**Comment by rvandermeulen** [comment]
Testing this is more involved than I realized and I don't have cycles to do that right now. To document a convo I had with jhugman about this, the root problem is that `Versions` isn't compiled by the time the Groovy plugin is built, hence we can't use that. The thought he had was having the A-S version defined somewhere else at a higher level that Dependencies.kt and NimbusGradlePlugin.groovy could both then reference from.

**Pull request closed without merging**
