### PR TITLE
Add toolbarVisible getter to WebAppHideToolbarFeature

### PR DESCRIPTION
**Pull request by NotWoods**
Exposing this to fix the toolbar issues in Fenix. https://github.com/mozilla-mobile/fenix/issues/10452

---

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Comment by jonalmeida** [comment]
Please add an issue as reference so we know which bug this is fixing. 🙂

**Comment by NotWoods** [comment]
Added https://github.com/mozilla-mobile/fenix/issues/10452 to the description

**Comment by NotWoods** [comment]
Fenix sets the visibility field in other places, so this is used to query what the feature thinks the toolbar visibility _should_ be, rather than what it is.

**Comment by grigoryk** [comment]
> Fenix sets the visibility field in other places, so this is used to query what the feature thinks the toolbar visibility _should_ be, rather than what it is.

That just sounds like a recipe for other bugs to crop up. Can we have a single point of responsibility for controlling toolbar visibility?

**Comment by NotWoods** [comment]
I think this is best for a quick fix (just requires an extra if statment in Fenix), and I'll work on a follow up to move most of this logic into BrowserStore. Eventually we can have something along the lines of:

```kt
fun SessionState.hideToolbar() = content.fullscreen || content.pictureInPicture || content.url.isInScope()
```

**Comment by NotWoods** [comment]
I've set up an alternative BrowserStore based solution here: #7251

**Comment by grigoryk** [comment]
We can close this, right? @NotWoods

**Pull request closed without merging**
