### PR TITLE
Update Kotlin version to 1.3.7.

### PR DESCRIPTION
**Pull request by Amejia481**
[Release notes](https://blog.jetbrains.com/kotlin/2020/03/kotlin-1-3-70-released/)

### CODE REVIEW

**Comment by pocmo** [comment]
There's a matching coroutines 1.3.4 update that we could update too, either here or in a follow-up.

**Comment by Amejia481** [comment]
Sure, I can update it on this pr :)

**Comment by pocmo** [comment]
Heh, now, 5 minutes ago, they released 1.3.5.

**Comment by Amejia481** [comment]
bors r=psymoon

**Pull request merged**
